VPR_Messenger: Messenger.Helpers.TeamHelpers.TeamBuilder Class Reference
Messenger.Helpers.TeamHelpers.TeamBuilder Class Reference
Static Public Member Functions
static async Task< IEnumerable< Team > > GetTeamsFromDatabase (UserViewModel currentUser)
static async Task< TeamViewModel > Build (this Team team, string userId)
static async Task< IEnumerable< TeamViewModel > > Build (this IEnumerable< Team > teams, string userId)
static async Task< TeamViewModel > WithMembers (this TeamViewModel viewModel, string currentUserId)
Determines the type of team and sets the corresponding member models
static async Task< TeamViewModel > WithChannels (this TeamViewModel viewModel)
Loads the children channels of the team
static async Task< TeamViewModel > WithTeamRoles (this TeamViewModel viewModel)
static async Task< MemberViewModel > WithMemberRoles (this MemberViewModel viewModel)
static async Task< TeamRoleViewModel > WithPermissions (this TeamRoleViewModel viewModel)
static async Task< IEnumerable< TeamRoleViewModel > > WithPermissions (this IEnumerable< TeamRoleViewModel > viewModels)
static TeamViewModel Map (Team team)
static TeamRoleViewModel Map (TeamRole teamRole)
static IEnumerable< TeamRoleViewModel > Map (IEnumerable< TeamRole > teamRoles)
static ChannelViewModel Map (Channel channel)
static IEnumerable< ChannelViewModel > Map (IEnumerable< Channel > channels)
static MemberViewModel Map (User user)
static IEnumerable< MemberViewModel > Map (IEnumerable< User > users)
static TeamViewModel DetermineTeamType (TeamViewModel viewModel)
Detailed Description
Definition at line 12 of file TeamBuilder.cs.
Member Function Documentation
Build() [1/2]
static async Task<IEnumerable<TeamViewModel> > Messenger.Helpers.TeamHelpers.TeamBuilder.Build (this IEnumerable< Team > teams, string userId) inline static
Definition at line 34 of file TeamBuilder.cs.
References Messenger.Helpers.TeamHelpers.TeamBuilder.Build().
Build() [2/2]
static async Task<TeamViewModel> Messenger.Helpers.TeamHelpers.TeamBuilder.Build (this Team team, string userId) inline static
Definition at line 19 of file TeamBuilder.cs.
References Messenger.Helpers.TeamHelpers.TeamBuilder.Map().
Referenced by Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeam(), and Messenger.Helpers.TeamHelpers.TeamBuilder.Build().
DetermineTeamType()
static TeamViewModel Messenger.Helpers.TeamHelpers.TeamBuilder.DetermineTeamType (TeamViewModel viewModel) inline static
Definition at line 299 of file TeamBuilder.cs.
References Messenger.ViewModels.DataViewModels.TeamViewModel.TeamName.
Referenced by Messenger.Helpers.TeamHelpers.TeamBuilder.WithMembers().
GetTeamsFromDatabase()
static async Task<IEnumerable<Team> > Messenger.Helpers.TeamHelpers.TeamBuilder.GetTeamsFromDatabase (UserViewModel currentUser) inline static
Definition at line 14 of file TeamBuilder.cs.
References Messenger.Core.Services.MessengerService.GetTeams(), and Messenger.ViewModels.DataViewModels.UserViewModel.Id.
Referenced by Messenger.Helpers.TeamHelpers.TeamManager.LoadTeamsFromDatabase().
Map() [1/7]
static ChannelViewModel Messenger.Helpers.TeamHelpers.TeamBuilder.Map (Channel channel) inline static
Definition at line 248 of file TeamBuilder.cs.
References Messenger.Core.Models.Channel.ChannelId, Messenger.Core.Models.Channel.ChannelName, and Messenger.Core.Models.Channel.TeamId.
Map() [2/7]
static IEnumerable<ChannelViewModel> Messenger.Helpers.TeamHelpers.TeamBuilder.Map (IEnumerable< Channel > channels) inline static
Definition at line 258 of file TeamBuilder.cs.
References Messenger.Helpers.TeamHelpers.TeamBuilder.Map().
Map() [3/7]
static IEnumerable<TeamRoleViewModel> Messenger.Helpers.TeamHelpers.TeamBuilder.Map (IEnumerable< TeamRole > teamRoles) inline static
Definition at line 243 of file TeamBuilder.cs.
References Messenger.Helpers.TeamHelpers.TeamBuilder.Map().
Map() [4/7]
static IEnumerable<MemberViewModel> Messenger.Helpers.TeamHelpers.TeamBuilder.Map (IEnumerable< User > users) inline static
Definition at line 289 of file TeamBuilder.cs.
References Messenger.Helpers.TeamHelpers.TeamBuilder.Map().
Map() [5/7]
static TeamViewModel Messenger.Helpers.TeamHelpers.TeamBuilder.Map (Team team) inline static
Definition at line 217 of file TeamBuilder.cs.
References Messenger.Core.Models.Team.CreationDate, Messenger.Core.Models.Team.Description, Messenger.Core.Models.Team.Id, and Messenger.Core.Models.Team.Name.
Referenced by Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateChannel(), Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateMember(), Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeamRole(), Messenger.Helpers.TeamHelpers.TeamBuilder.Build(), Messenger.Helpers.TeamHelpers.TeamBuilder.Map(), Messenger.Helpers.TeamHelpers.TeamBuilder.WithChannels(), Messenger.Helpers.TeamHelpers.TeamBuilder.WithMemberRoles(), Messenger.Helpers.TeamHelpers.TeamBuilder.WithMembers(), Messenger.Helpers.MessageHelpers.MessageBuilder.WithSender(), and Messenger.Helpers.TeamHelpers.TeamBuilder.WithTeamRoles().
Map() [6/7]
static TeamRoleViewModel Messenger.Helpers.TeamHelpers.TeamBuilder.Map (TeamRole teamRole) inline static
Definition at line 231 of file TeamBuilder.cs.
References Messenger.Core.Models.TeamRole.Color, Messenger.Core.Models.TeamRole.Id, Messenger.Core.Models.TeamRole.Role, and Messenger.Core.Models.TeamRole.TeamId.
Map() [7/7]
static MemberViewModel Messenger.Helpers.TeamHelpers.TeamBuilder.Map (User user) inline static
Definition at line 270 of file TeamBuilder.cs.
References Messenger.Core.Models.User.Bio, Messenger.Core.Models.User.DisplayName, Messenger.Core.Models.User.Id, Messenger.Core.Models.User.Mail, and Messenger.Core.Models.User.NameId.
WithChannels()
static async Task<TeamViewModel> Messenger.Helpers.TeamHelpers.TeamBuilder.WithChannels (this TeamViewModel viewModel) inline static
Loads the children channels of the team
Parameters
viewModel ViewModel of the team
Returns
TeamViewModel with updated channels
Definition at line 93 of file TeamBuilder.cs.
References Messenger.ViewModels.DataViewModels.TeamViewModel.Channels, Messenger.Core.Services.MessengerService.GetChannelsForTeam(), Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.ViewModels.DataViewModels.PrivateChatViewModel.MainChannel, and Messenger.Helpers.TeamHelpers.TeamBuilder.Map().
WithMemberRoles()
static async Task<MemberViewModel> Messenger.Helpers.TeamHelpers.TeamBuilder.WithMemberRoles (this MemberViewModel viewModel) inline static
LOAD CUSTOM ROLES FOR THE TEAM
LOAD PERMISSIONS FOR EACH ROLE
Definition at line 146 of file TeamBuilder.cs.
References Messenger.ViewModels.DataViewModels.MemberViewModel.AssignableMemberRoles, Messenger.Core.Services.TeamService.GetUsersRoles(), Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Id, Messenger.ViewModels.DataViewModels.UserViewModel.Id, Messenger.Core.Services.TeamService.ListRoles(), Messenger.Helpers.TeamHelpers.TeamBuilder.Map(), Messenger.ViewModels.DataViewModels.MemberViewModel.MemberRoles, and Messenger.ViewModels.DataViewModels.MemberViewModel.TeamId.
WithMembers()
static async Task<TeamViewModel> Messenger.Helpers.TeamHelpers.TeamBuilder.WithMembers (this TeamViewModel viewModel, string currentUserId) inline static
Determines the type of team and sets the corresponding member models
Parameters
team Team object to reference to
members List of members to set
Definition at line 54 of file TeamBuilder.cs.
References Messenger.Helpers.TeamHelpers.TeamBuilder.DetermineTeamType(), Messenger.Core.Services.MessengerService.GetTeamMembers(), Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Helpers.TeamHelpers.TeamBuilder.Map(), Messenger.ViewModels.DataViewModels.TeamViewModel.Members, Messenger.ViewModels.DataViewModels.UserViewModel.Name, Messenger.ViewModels.DataViewModels.PrivateChatViewModel.Partner, Messenger.ViewModels.DataViewModels.MemberViewModel.TeamId, and Messenger.ViewModels.DataViewModels.TeamViewModel.TeamName.
WithPermissions() [1/2]
static async Task<IEnumerable<TeamRoleViewModel> > Messenger.Helpers.TeamHelpers.TeamBuilder.WithPermissions (this IEnumerable< TeamRoleViewModel > viewModels) inline static
Definition at line 203 of file TeamBuilder.cs.
WithPermissions() [2/2]
static async Task<TeamRoleViewModel> Messenger.Helpers.TeamHelpers.TeamBuilder.WithPermissions (this TeamRoleViewModel viewModel) inline static
Definition at line 184 of file TeamBuilder.cs.
References Messenger.Core.Services.TeamService.GetPermissionsOfRole(), Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Permissions, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.TeamId, and Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Title.
WithTeamRoles()
static async Task<TeamViewModel> Messenger.Helpers.TeamHelpers.TeamBuilder.WithTeamRoles (this TeamViewModel viewModel) inline static
Definition at line 118 of file TeamBuilder.cs.
References Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Core.Services.TeamService.ListRoles(), Messenger.Helpers.TeamHelpers.TeamBuilder.Map(), and Messenger.ViewModels.DataViewModels.TeamViewModel.TeamRoles.
The documentation for this class was generated from the following file:
Messenger/Messenger/Helpers/TeamHelpers/TeamBuilder.cs