VPR_Messenger: Messenger.ViewModels.Pages.SettingsViewModel Class Reference
Messenger.ViewModels.Pages.SettingsViewModel Class Reference
Public Member Functions
SettingsViewModel ()
async void InitializeAsync ()
void UnregisterEvents ()
Properties
ElementTheme ElementTheme [get, set]
string VersionDescription [get, set]
ICommand SwitchThemeCommand [get]
ICommand LogoutCommand [get]
ICommand UpdateUserBioCommand [get]
ICommand UpdateUsernameCommand [get]
ICommand NavigateBackCommand [get]
UserViewModel User [get, set]
string CurrentBio [get, set]
Additional Inherited Members
Protected Member Functions inherited from Messenger.Helpers.Observable
void Set< T > (ref T storage, T value, [CallerMemberName]string propertyName=null)
void OnPropertyChanged (string propertyName)
Events inherited from Messenger.Helpers.Observable
PropertyChangedEventHandler PropertyChanged
Detailed Description
Definition at line 18 of file SettingsViewModel.cs.
Constructor & Destructor Documentation
SettingsViewModel()
Messenger.ViewModels.Pages.SettingsViewModel.SettingsViewModel () inline
Definition at line 92 of file SettingsViewModel.cs.
References Messenger.ViewModels.Pages.SettingsViewModel.InitializeAsync().
Member Function Documentation
InitializeAsync()
async void Messenger.ViewModels.Pages.SettingsViewModel.InitializeAsync () inline
Definition at line 97 of file SettingsViewModel.cs.
References Messenger.Services.UserDataService.GetUserAsync(), Messenger.Core.Services.IdentityService.LoggedOut, Messenger.ViewModels.Pages.SettingsViewModel.User, Messenger.Services.UserDataService.UserDataUpdated, and Messenger.ViewModels.Pages.SettingsViewModel.VersionDescription.
Referenced by Messenger.ViewModels.Pages.SettingsViewModel.SettingsViewModel().
UnregisterEvents()
void Messenger.ViewModels.Pages.SettingsViewModel.UnregisterEvents () inline
Definition at line 115 of file SettingsViewModel.cs.
References Messenger.Core.Services.IdentityService.LoggedOut, and Messenger.Services.UserDataService.UserDataUpdated.
Referenced by Messenger.Views.Pages.SettingsPage.OnNavigatingFrom().
Property Documentation
CurrentBio
string Messenger.ViewModels.Pages.SettingsViewModel.CurrentBio get set
Definition at line 86 of file SettingsViewModel.cs.
ElementTheme
ElementTheme Messenger.ViewModels.Pages.SettingsViewModel.ElementTheme get set
Definition at line 26 of file SettingsViewModel.cs.
Referenced by Messenger.Views.Pages.SettingsPage.OnNavigatedTo().
LogoutCommand
ICommand Messenger.ViewModels.Pages.SettingsViewModel.LogoutCommand get
Definition at line 66 of file SettingsViewModel.cs.
NavigateBackCommand
ICommand Messenger.ViewModels.Pages.SettingsViewModel.NavigateBackCommand get
Definition at line 72 of file SettingsViewModel.cs.
SwitchThemeCommand
ICommand Messenger.ViewModels.Pages.SettingsViewModel.SwitchThemeCommand get
Definition at line 44 of file SettingsViewModel.cs.
UpdateUserBioCommand
ICommand Messenger.ViewModels.Pages.SettingsViewModel.UpdateUserBioCommand get
Definition at line 68 of file SettingsViewModel.cs.
UpdateUsernameCommand
ICommand Messenger.ViewModels.Pages.SettingsViewModel.UpdateUsernameCommand get
Definition at line 70 of file SettingsViewModel.cs.
User
UserViewModel Messenger.ViewModels.Pages.SettingsViewModel.User get set
Definition at line 74 of file SettingsViewModel.cs.
Referenced by Messenger.ViewModels.Pages.SettingsViewModel.InitializeAsync().
VersionDescription
string Messenger.ViewModels.Pages.SettingsViewModel.VersionDescription get set
Definition at line 35 of file SettingsViewModel.cs.
Referenced by Messenger.ViewModels.Pages.SettingsViewModel.InitializeAsync().
The documentation for this class was generated from the following file:
Messenger/Messenger/ViewModels/Pages/SettingsViewModel.cs