VPR_Messenger: Messenger.Commands.Messenger.ToggleReactionCommand Class Reference
Messenger.Commands.Messenger.ToggleReactionCommand Class Reference
Public Member Functions
ToggleReactionCommand ()
bool CanExecute (object parameter)
async void Execute (object parameter)
Events
EventHandler CanExecuteChanged
Detailed Description
Definition at line 13 of file ToggleReactionCommand.cs.
Constructor & Destructor Documentation
ToggleReactionCommand()
Messenger.Commands.Messenger.ToggleReactionCommand.ToggleReactionCommand () inline
Definition at line 17 of file ToggleReactionCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.Messenger.ToggleReactionCommand.CanExecute (object parameter) inline
Definition at line 23 of file ToggleReactionCommand.cs.
Execute()
async void Messenger.Commands.Messenger.ToggleReactionCommand.Execute (object parameter) inline
IF USER HAS ALREADY MADE A REACTION
ELSE MAKE ONLY
Definition at line 28 of file ToggleReactionCommand.cs.
References Messenger.Core.Services.MessengerService.CreateMessageReaction(), Messenger.Core.Services.MessengerService.DeleteMessageReaction(), Messenger.ViewModels.DataViewModels.MessageViewModel.HasReacted, Messenger.ViewModels.DataViewModels.MessageViewModel.Id, Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.ViewModels.DataViewModels.UserViewModel.Id, Messenger.Models.ToggleReactionArg.Message, Messenger.ViewModels.DataViewModels.MessageViewModel.MyReaction, Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set(), and Messenger.Models.ToggleReactionArg.Type.
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.Messenger.ToggleReactionCommand.CanExecuteChanged
Definition at line 21 of file ToggleReactionCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/Messenger/ToggleReactionCommand.cs