VPR_Messenger: Messenger.Commands.Messenger.DeleteMessageCommand Class Reference
Messenger.Commands.Messenger.DeleteMessageCommand Class Reference
Public Member Functions
DeleteMessageCommand ()
bool CanExecute (object parameter)
async void Execute (object parameter)
Properties
ILogger _logger [get]
Events
EventHandler CanExecuteChanged
Detailed Description
Definition at line 11 of file DeleteMessageCommand.cs.
Constructor & Destructor Documentation
DeleteMessageCommand()
Messenger.Commands.Messenger.DeleteMessageCommand.DeleteMessageCommand () inline
Definition at line 15 of file DeleteMessageCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.Messenger.DeleteMessageCommand.CanExecute (object parameter) inline
Definition at line 21 of file DeleteMessageCommand.cs.
Execute()
async void Messenger.Commands.Messenger.DeleteMessageCommand.Execute (object parameter) inline
Definition at line 26 of file DeleteMessageCommand.cs.
References Messenger.Commands.Messenger.DeleteMessageCommand._logger, Messenger.Core.Services.MessengerService.DeleteMessage(), Messenger.ViewModels.DataViewModels.MessageViewModel.Id, Messenger.ViewModels.DataViewModels.TeamViewModel.Id, and Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set().
Referenced by Messenger.Views.Subcontrols.MessageView.DeleteButton_Tapped().
Property Documentation
_logger
ILogger Messenger.Commands.Messenger.DeleteMessageCommand._logger get private
Definition at line 13 of file DeleteMessageCommand.cs.
Referenced by Messenger.Commands.Messenger.DeleteMessageCommand.Execute().
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.Messenger.DeleteMessageCommand.CanExecuteChanged
Definition at line 19 of file DeleteMessageCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/Messenger/DeleteMessageCommand.cs