VPR_Messenger: Messenger.App Class Reference
Messenger.App Class Reference
Public Member Functions
App ()
Protected Member Functions
override async void OnLaunched (LaunchActivatedEventArgs args)
override async void OnActivated (IActivatedEventArgs args)
Properties
IdentityService IdentityService [get]
ActivationService ActivationService [get]
Private Member Functions
void OnAppUnhandledException (object sender, Windows.UI.Xaml.UnhandledExceptionEventArgs e)
ActivationService CreateActivationService ()
UIElement CreateShell ()
async void OnLoggedOut (object sender, EventArgs e)
Private Attributes
Lazy< ActivationService > _activationService
Detailed Description
Definition at line 19 of file App.xaml.cs.
Constructor & Destructor Documentation
App()
Messenger.App.App () inline
Definition at line 34 of file App.xaml.cs.
References Messenger.App._activationService, Messenger.App.CreateActivationService(), Messenger.Core.Services.IdentityService.LoggedOut, Messenger.App.OnAppUnhandledException(), and Messenger.App.OnLoggedOut().
Member Function Documentation
CreateActivationService()
ActivationService Messenger.App.CreateActivationService () inline private
Definition at line 98 of file App.xaml.cs.
References Messenger.App.ActivationService, and Messenger.App.CreateShell().
Referenced by Messenger.App.App().
CreateShell()
UIElement Messenger.App.CreateShell () inline private
Definition at line 103 of file App.xaml.cs.
Referenced by Messenger.App.CreateActivationService(), and Messenger.App.OnLoggedOut().
OnActivated()
override async void Messenger.App.OnActivated (IActivatedEventArgs args) inline protected
Definition at line 61 of file App.xaml.cs.
References Messenger.App.ActivationService, and Messenger.Services.NavigationService.Navigate().
OnAppUnhandledException()
void Messenger.App.OnAppUnhandledException (object sender, Windows.UI.Xaml.UnhandledExceptionEventArgs e) inline private
Definition at line 92 of file App.xaml.cs.
Referenced by Messenger.App.App().
OnLaunched()
override async void Messenger.App.OnLaunched (LaunchActivatedEventArgs args) inline protected
Definition at line 50 of file App.xaml.cs.
References Messenger.App.ActivationService.
OnLoggedOut()
async void Messenger.App.OnLoggedOut (object sender, EventArgs e) inline private
Definition at line 108 of file App.xaml.cs.
References Messenger.App.ActivationService, and Messenger.App.CreateShell().
Referenced by Messenger.App.App().
Member Data Documentation
_activationService
Lazy<ActivationService> Messenger.App._activationService private
Definition at line 23 of file App.xaml.cs.
Referenced by Messenger.App.App().
Property Documentation
ActivationService
ActivationService Messenger.App.ActivationService get private
Definition at line 25 of file App.xaml.cs.
Referenced by Messenger.App.CreateActivationService(), Messenger.App.OnActivated(), Messenger.App.OnLaunched(), and Messenger.App.OnLoggedOut().
IdentityService
IdentityService Messenger.App.IdentityService get private
Definition at line 21 of file App.xaml.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/App.xaml.cs