VPR_Messenger: Messenger.Services.UserDataService Class Reference
Messenger.Services.UserDataService Class Reference
Public Member Functions
UserDataService ()
void Initialize ()
async Task< UserViewModel > GetUserAsync ()
Properties
IdentityService IdentityService [get]
bool IsOnline [get]
Events
EventHandler< UserViewModel > UserDataUpdated
Private Member Functions
async void OnLoggedIn (object sender, EventArgs e)
async void OnLoggedOut (object sender, EventArgs e)
async Task< UserViewModel > GetUserFromCacheAsync ()
async Task< UserViewModel > GetUserFromGraphApiAsync ()
async Task< UserViewModel > GetUserViewModelFromData (User userData)
UserViewModel GetDefaultUserData ()
async Task< IList< Team > > InitializeSignalR (string userId)
Private Attributes
UserViewModel _user
Static Private Attributes
const string _userSettingsKey = "IdentityUser"
Detailed Description
Definition at line 16 of file UserDataService.cs.
Constructor & Destructor Documentation
UserDataService()
Messenger.Services.UserDataService.UserDataService () inline
Definition at line 28 of file UserDataService.cs.
Member Function Documentation
GetDefaultUserData()
UserViewModel Messenger.Services.UserDataService.GetDefaultUserData () inline private
Definition at line 123 of file UserDataService.cs.
References Messenger.Core.Services.IdentityService.GetAccountUserName(), and Messenger.Helpers.ImageHelper.ImageFromAssetsFile().
Referenced by Messenger.Services.UserDataService.GetUserAsync().
GetUserAsync()
async Task<UserViewModel> Messenger.Services.UserDataService.GetUserAsync () inline
Definition at line 38 of file UserDataService.cs.
References Messenger.Services.UserDataService._user, Messenger.Services.UserDataService.GetDefaultUserData(), and Messenger.Services.UserDataService.GetUserFromCacheAsync().
Referenced by Messenger.ViewModels.Pages.ChatNavViewModel.Initialize(), Messenger.ViewModels.Pages.TeamNavViewModel.Initialize(), and Messenger.ViewModels.Pages.SettingsViewModel.InitializeAsync().
GetUserFromCacheAsync()
async Task<UserViewModel> Messenger.Services.UserDataService.GetUserFromCacheAsync () inline private
Definition at line 65 of file UserDataService.cs.
References Messenger.Services.UserDataService._userSettingsKey, and Messenger.Services.UserDataService.GetUserViewModelFromData().
Referenced by Messenger.Services.UserDataService.GetUserAsync().
GetUserFromGraphApiAsync()
async Task<UserViewModel> Messenger.Services.UserDataService.GetUserFromGraphApiAsync () inline private
Definition at line 72 of file UserDataService.cs.
References Messenger.Services.UserDataService._userSettingsKey, Messenger.Core.Services.IdentityService.GetAccessTokenForGraphAsync(), Messenger.Core.Services.MicrosoftGraphService.GetUserInfoAsync(), Messenger.Core.Services.MicrosoftGraphService.GetUserPhoto(), and Messenger.Services.UserDataService.GetUserViewModelFromData().
Referenced by Messenger.Services.UserDataService.OnLoggedIn().
GetUserViewModelFromData()
async Task<UserViewModel> Messenger.Services.UserDataService.GetUserViewModelFromData (User userData) inline private
Definition at line 90 of file UserDataService.cs.
References Messenger.Core.Models.User.Bio, Messenger.Core.Models.User.DisplayName, Messenger.Core.Services.UserService.GetOrCreateApplicationUser(), Messenger.Core.Models.User.Id, Messenger.ViewModels.DataViewModels.UserViewModel.Id, Messenger.Helpers.ImageHelper.ImageFromAssetsFile(), Messenger.Helpers.ImageHelper.ImageFromStringAsync(), Messenger.Services.UserDataService.InitializeSignalR(), Messenger.Core.Helpers.Singleton< T >.Instance, Messenger.Core.Models.User.Mail, Messenger.Core.Models.User.NameId, and Messenger.Core.Models.User.Photo.
Referenced by Messenger.Services.UserDataService.GetUserFromCacheAsync(), and Messenger.Services.UserDataService.GetUserFromGraphApiAsync().
Initialize()
void Messenger.Services.UserDataService.Initialize () inline
Definition at line 32 of file UserDataService.cs.
References Messenger.Core.Services.IdentityService.LoggedIn, Messenger.Core.Services.IdentityService.LoggedOut, Messenger.Services.UserDataService.OnLoggedIn(), and Messenger.Services.UserDataService.OnLoggedOut().
InitializeSignalR()
async Task<IList<Team> > Messenger.Services.UserDataService.InitializeSignalR (string userId) inline private
Definition at line 132 of file UserDataService.cs.
References Messenger.Core.Services.MessengerService.Initialize().
Referenced by Messenger.Services.UserDataService.GetUserViewModelFromData().
OnLoggedIn()
async void Messenger.Services.UserDataService.OnLoggedIn (object sender, EventArgs e) inline private
Definition at line 52 of file UserDataService.cs.
References Messenger.Services.UserDataService._user, Messenger.Services.UserDataService.GetUserFromGraphApiAsync(), and Messenger.Services.UserDataService.UserDataUpdated.
Referenced by Messenger.Services.UserDataService.Initialize().
OnLoggedOut()
async void Messenger.Services.UserDataService.OnLoggedOut (object sender, EventArgs e) inline private
Definition at line 59 of file UserDataService.cs.
References Messenger.Services.UserDataService._user, and Messenger.Services.UserDataService._userSettingsKey.
Referenced by Messenger.Services.UserDataService.Initialize().
Member Data Documentation
_user
UserViewModel Messenger.Services.UserDataService._user private
Definition at line 20 of file UserDataService.cs.
Referenced by Messenger.Services.UserDataService.GetUserAsync(), Messenger.Services.UserDataService.OnLoggedIn(), and Messenger.Services.UserDataService.OnLoggedOut().
_userSettingsKey
const string Messenger.Services.UserDataService._userSettingsKey = "IdentityUser" static private
Definition at line 18 of file UserDataService.cs.
Referenced by Messenger.Services.UserDataService.GetUserFromCacheAsync(), Messenger.Services.UserDataService.GetUserFromGraphApiAsync(), and Messenger.Services.UserDataService.OnLoggedOut().
Property Documentation
IdentityService
IdentityService Messenger.Services.UserDataService.IdentityService get private
Definition at line 22 of file UserDataService.cs.
IsOnline
bool Messenger.Services.UserDataService.IsOnline get
Definition at line 24 of file UserDataService.cs.
Event Documentation
UserDataUpdated
EventHandler<UserViewModel> Messenger.Services.UserDataService.UserDataUpdated
Definition at line 26 of file UserDataService.cs.
Referenced by Messenger.ViewModels.Pages.SettingsViewModel.InitializeAsync(), Messenger.Services.UserDataService.OnLoggedIn(), and Messenger.ViewModels.Pages.SettingsViewModel.UnregisterEvents().
The documentation for this class was generated from the following file:
Messenger/Messenger/Services/UserDataService.cs