VPR_Messenger: Messenger.Helpers.MessageHelpers.MessageManager Class Reference
Messenger.Helpers.MessageHelpers.MessageManager Class Reference
Handles the dictionary for storing messages with the key of channel ids.
Public Member Functions
MessageManager ()
bool TryGetMessages (uint channelId, out ObservableCollection< MessageViewModel > messages)
Gets the list of messages with the key of the given channel id
async Task CreateEntry (TeamViewModel viewModel)
async Task CreateEntry (IEnumerable< TeamViewModel > viewModels)
async Task< MessageViewModel > AddOrUpdateMessage (Message messageData)
async Task< IList< MessageViewModel > > AddOrUpdateMessage (IEnumerable< Message > messageData)
MessageViewModel RemoveMessage (Message data)
Finds and removes the MessageViewModel with the given Message data model
ChannelViewModel RemoveEntry (uint channelId)
Removes entry with the given key
Events
EventHandler< ManagerEventArgs > MessagesLoadedForChannel
Events inherited from Messenger.Helpers.Observable
PropertyChangedEventHandler PropertyChanged
Additional Inherited Members
Protected Member Functions inherited from Messenger.Helpers.Observable
void Set< T > (ref T storage, T value, [CallerMemberName]string propertyName=null)
void OnPropertyChanged (string propertyName)
Detailed Description
Handles the dictionary for storing messages with the key of channel ids.
Definition at line 16 of file MessageManager.cs.
Constructor & Destructor Documentation
MessageManager()
Messenger.Helpers.MessageHelpers.MessageManager.MessageManager () inline
Definition at line 22 of file MessageManager.cs.
Member Function Documentation
AddOrUpdateMessage() [1/2]
async Task<IList<MessageViewModel> > Messenger.Helpers.MessageHelpers.MessageManager.AddOrUpdateMessage (IEnumerable< Message > messageData) inline
Definition at line 109 of file MessageManager.cs.
References Messenger.Helpers.MessageHelpers.MessageManager.AddOrUpdateMessage().
AddOrUpdateMessage() [2/2]
async Task<MessageViewModel> Messenger.Helpers.MessageHelpers.MessageManager.AddOrUpdateMessage (Message messageData) inline
Definition at line 100 of file MessageManager.cs.
References Messenger.Helpers.MessageHelpers.MessageBuilder.Build().
Referenced by Messenger.Helpers.CacheQuery.AddOrUpdate< T >(), Messenger.Helpers.MessageHelpers.MessageManager.AddOrUpdateMessage(), and Messenger.Helpers.MessageHelpers.MessageManager.CreateEntry().
CreateEntry() [1/2]
async Task Messenger.Helpers.MessageHelpers.MessageManager.CreateEntry (IEnumerable< TeamViewModel > viewModels) inline
Definition at line 92 of file MessageManager.cs.
References Messenger.Helpers.MessageHelpers.MessageManager.CreateEntry().
CreateEntry() [2/2]
async Task Messenger.Helpers.MessageHelpers.MessageManager.CreateEntry (TeamViewModel viewModel) inline
Definition at line 40 of file MessageManager.cs.
References Messenger.Helpers.MessageHelpers.MessageManager.AddOrUpdateMessage(), Messenger.ViewModels.DataViewModels.TeamViewModel.Channels, Messenger.Helpers.MessageHelpers.MessageBuilder.GetMessagesFromDatabase(), Messenger.ViewModels.DataViewModels.PrivateChatViewModel.MainChannel, and Messenger.Helpers.MessageHelpers.MessageManager.MessagesLoadedForChannel.
Referenced by Messenger.Helpers.MessageHelpers.MessageManager.CreateEntry(), and Messenger.Services.Providers.StateProviderExtension.LoadAllMessages().
RemoveEntry()
ChannelViewModel Messenger.Helpers.MessageHelpers.MessageManager.RemoveEntry (uint channelId) inline
Removes entry with the given key
Parameters
channelId Id of the channel
Returns
Removed channel object
Definition at line 168 of file MessageManager.cs.
RemoveMessage()
MessageViewModel Messenger.Helpers.MessageHelpers.MessageManager.RemoveMessage (Message data) inline
Finds and removes the MessageViewModel with the given Message data model
Parameters
data Message data model to be searched with
Definition at line 130 of file MessageManager.cs.
References Messenger.Core.Models.Message.Id, Messenger.Core.Models.Message.ParentMessageId, Messenger.Core.Models.Message.RecipientId, and Messenger.ViewModels.DataViewModels.MessageViewModel.Replies.
Referenced by Messenger.Helpers.CacheQuery.Remove< T >().
TryGetMessages()
bool Messenger.Helpers.MessageHelpers.MessageManager.TryGetMessages (uint channelId, out ObservableCollection< MessageViewModel > messages) inline
Gets the list of messages with the key of the given channel id
Parameters
channelId Id of the team (Key)
messages List of messages (Value)
Returns
True if the team exists, else false
Definition at line 33 of file MessageManager.cs.
Event Documentation
MessagesLoadedForChannel
EventHandler<ManagerEventArgs> Messenger.Helpers.MessageHelpers.MessageManager.MessagesLoadedForChannel
Definition at line 20 of file MessageManager.cs.
Referenced by Messenger.Helpers.MessageHelpers.MessageManager.CreateEntry().
The documentation for this class was generated from the following file:
Messenger/Messenger/Helpers/MessageHelpers/MessageManager.cs