VPR_Messenger: Messenger.Services.UserActivityService Class Reference
Messenger.Services.UserActivityService Class Reference
Static Public Member Functions
static async Task CreateUserActivityAsync (UserActivityData activityData)
static async Task CreateUserActivityAsync (UserActivityData activityData, IAdaptiveCard adaptiveCard)
static async Task AddSampleUserActivity ()
Static Private Member Functions
static async Task SaveAsync (UserActivity activity)
static SchemeActivationData CreateActivationDataSample ()
static IAdaptiveCard CreateAdaptiveCardSample (string displayText, string description, string imageUrl)
Static Private Attributes
static UserActivitySession _currentUserActivitySession
Detailed Description
Definition at line 15 of file UserActivityService.cs.
Member Function Documentation
AddSampleUserActivity()
static async Task Messenger.Services.UserActivityService.AddSampleUserActivity () inline static
Definition at line 17 of file UserActivityService.Sample.cs.
References Messenger.Services.UserActivityService.CreateActivationDataSample(), Messenger.Services.UserActivityService.CreateAdaptiveCardSample(), and Messenger.Services.UserActivityService.CreateUserActivityAsync().
CreateActivationDataSample()
static SchemeActivationData Messenger.Services.UserActivityService.CreateActivationDataSample () inline static private
Definition at line 30 of file UserActivityService.Sample.cs.
Referenced by Messenger.Services.UserActivityService.AddSampleUserActivity().
CreateAdaptiveCardSample()
static IAdaptiveCard Messenger.Services.UserActivityService.CreateAdaptiveCardSample (string displayText, string description, string imageUrl) inline static private
Definition at line 42 of file UserActivityService.Sample.cs.
Referenced by Messenger.Services.UserActivityService.AddSampleUserActivity().
CreateUserActivityAsync() [1/2]
static async Task Messenger.Services.UserActivityService.CreateUserActivityAsync (UserActivityData activityData) inline static
Definition at line 19 of file UserActivityService.cs.
References Messenger.Services.UserActivityService.SaveAsync(), and Messenger.Services.UserActivityData.ToUserActivity().
Referenced by Messenger.Services.UserActivityService.AddSampleUserActivity().
CreateUserActivityAsync() [2/2]
static async Task Messenger.Services.UserActivityService.CreateUserActivityAsync (UserActivityData activityData, IAdaptiveCard adaptiveCard) inline static
Definition at line 28 of file UserActivityService.cs.
References Messenger.Services.UserActivityService.SaveAsync(), and Messenger.Services.UserActivityData.ToUserActivity().
SaveAsync()
static async Task Messenger.Services.UserActivityService.SaveAsync (UserActivity activity) inline static private
Definition at line 36 of file UserActivityService.cs.
References Messenger.Services.UserActivityService._currentUserActivitySession.
Referenced by Messenger.Services.UserActivityService.CreateUserActivityAsync().
Member Data Documentation
_currentUserActivitySession
UserActivitySession Messenger.Services.UserActivityService._currentUserActivitySession static private
Definition at line 17 of file UserActivityService.cs.
Referenced by Messenger.Services.UserActivityService.SaveAsync().
The documentation for this class was generated from the following files:
Messenger/Messenger/Services/UserActivityService.cs
Messenger/Messenger/Services/UserActivityService.Sample.cs