VPR_Messenger: Messenger.Core.Services.MentionService Class Reference
Messenger.Core.Services.MentionService Class Reference
Holds helpers and static methods to interact with mentions on the DB
Static Public Member Functions
static async Task< uint?> CreateMention< T > (MentionTarget target, T id, string mentionerId)
Create a mention to the entity of type target identified by id
static async Task< bool > RemoveMention (uint mentionId)
Remove a mention entry with the specified id
static async Task< Mention > RetrieveMention (uint mentionId)
Retrieve a mention object
static async Task< string > ResolveMentions (string message)
Resolve message's a mentionId's referenced entity name
static async Task< IList< Mentionable > > SearchMentionable (string searchString, uint teamId)
Return the top 10 mentionables matching the searchString
Static Private Member Functions
static async Task< IList< Mentionable > > SearchUsers (string userName, uint teamId)
Retrieve Mentionable objects of the top 10 user matches for the userName
static async Task< IList< Mentionable > > SearchRoles (string roleName, uint teamId)
Retrieve Mentionable objects of the top 10 role matches for the roleName
static async Task< IList< Mentionable > > SearchChannels (string channelName, uint teamId)
Retrieve Mentionable objects of the top 10 channel matches for the channelName
static async Task< IList< Mentionable > > SearchMessages (string messageId, uint teamId)
Retrieve Mentionable objects of the top 10 channel matches for the messageId
Detailed Description
Holds helpers and static methods to interact with mentions on the DB
Definition at line 15 of file MentionService.cs.
Member Function Documentation
CreateMention< T >()
static async Task<uint?> Messenger.Core.Services.MentionService.CreateMention< T > (MentionTarget target, T id, string mentionerId) inline static
Create a mention to the entity of type target identified by id
Parameters
target The type of the entity to mention
id The id of the entity to mention
mentionerId The id of the user who mentions an entity
Returns
The created mention id on success, null on failure
Definition at line 24 of file MentionService.cs.
RemoveMention()
static async Task<bool> Messenger.Core.Services.MentionService.RemoveMention (uint mentionId) inline static
Remove a mention entry with the specified id
Parameters
mentionId The id of the mention entry to remove
Returns
true on successfully, false otherwise
Definition at line 57 of file MentionService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
ResolveMentions()
static async Task<string> Messenger.Core.Services.MentionService.ResolveMentions (string message) inline static
Resolve message's a mentionId's referenced entity name
Parameters
message The message containing the mentions to resolve
Returns
The message with all mentions resolved
Definition at line 101 of file MentionService.cs.
References Messenger.Core.Services.ChannelService.GetChannel(), Messenger.Core.Services.TeamService.GetRole(), Messenger.Core.Services.UserService.GetUser(), and Messenger.Core.Services.MentionService.RetrieveMention().
Referenced by Messenger.Core.Helpers.NotificationMessageBuilder.MakeUserMentionedNotificationMessage().
RetrieveMention()
static async Task<Mention> Messenger.Core.Services.MentionService.RetrieveMention (uint mentionId) inline static
Retrieve a mention object
Parameters
mentionId The id of the mention to retrieve
Returns
The mention object
Definition at line 78 of file MentionService.cs.
References Messenger.Core.Helpers.SqlHelpers.GetRows(), and Messenger.Core.Helpers.Mapper.MentionFromDataRow().
Referenced by Messenger.Core.Services.NotificationService.CanSendNotification(), and Messenger.Core.Services.MentionService.ResolveMentions().
SearchChannels()
static async Task<IList<Mentionable> > Messenger.Core.Services.MentionService.SearchChannels (string channelName, uint teamId) inline static private
Retrieve Mentionable objects of the top 10 channel matches for the channelName
Parameters
channelName Channel name to retrieve matches for
teamId The id of the team to search in
Returns
List of top 10 matched mentionables
Definition at line 240 of file MentionService.cs.
References Messenger.Core.Helpers.Mapper.MentionableFromDataRow().
Referenced by Messenger.Core.Services.MentionService.SearchMentionable().
SearchMentionable()
static async Task<IList<Mentionable> > Messenger.Core.Services.MentionService.SearchMentionable (string searchString, uint teamId) inline static
Return the top 10 mentionables matching the searchString
Parameters
searchString The string used to rank matched entities
teamId The id of the team to search in
Returns
A list of Mentionables
Definition at line 302 of file MentionService.cs.
References Messenger.Core.Services.MentionService.SearchChannels(), Messenger.Core.Services.MentionService.SearchMessages(), Messenger.Core.Services.MentionService.SearchRoles(), and Messenger.Core.Services.MentionService.SearchUsers().
SearchMessages()
static async Task<IList<Mentionable> > Messenger.Core.Services.MentionService.SearchMessages (string messageId, uint teamId) inline static private
Retrieve Mentionable objects of the top 10 channel matches for the messageId
Parameters
messageId Id of the message to search for
teamId The id of the team to search in
Returns
List of top 10 matched mentionables
Definition at line 271 of file MentionService.cs.
References Messenger.Core.Helpers.Mapper.MentionableFromDataRow().
Referenced by Messenger.Core.Services.MentionService.SearchMentionable().
SearchRoles()
static async Task<IList<Mentionable> > Messenger.Core.Services.MentionService.SearchRoles (string roleName, uint teamId) inline static private
Retrieve Mentionable objects of the top 10 role matches for the roleName
Parameters
roleName Role name to retrieve matches for
teamId The id of the team to search in
Returns
List of top 10 matched mentionables
Definition at line 209 of file MentionService.cs.
References Messenger.Core.Helpers.Mapper.MentionableFromDataRow().
Referenced by Messenger.Core.Services.MentionService.SearchMentionable().
SearchUsers()
static async Task<IList<Mentionable> > Messenger.Core.Services.MentionService.SearchUsers (string userName, uint teamId) inline static private
Retrieve Mentionable objects of the top 10 user matches for the userName
Parameters
userName User name to retrieve matches for
teamId The id of the team to search in
Returns
List of top 10 matched mentionables
Definition at line 177 of file MentionService.cs.
References Messenger.Core.Helpers.Mapper.MentionableFromDataRow().
Referenced by Messenger.Core.Services.MentionService.SearchMentionable().
The documentation for this class was generated from the following file:
Messenger/Messenger.Core/Services/MentionService.cs