VPR_Messenger: Messenger.Commands.Messenger.UpdateMessageCommand Class Reference
Messenger.Commands.Messenger.UpdateMessageCommand Class Reference
Public Member Functions
UpdateMessageCommand ()
bool CanExecute (object parameter)
async void Execute (object parameter)
Properties
ILogger _logger [get]
Events
EventHandler CanExecuteChanged
Detailed Description
Definition at line 11 of file UpdateMessageCommand.cs.
Constructor & Destructor Documentation
UpdateMessageCommand()
Messenger.Commands.Messenger.UpdateMessageCommand.UpdateMessageCommand () inline
Definition at line 15 of file UpdateMessageCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.Messenger.UpdateMessageCommand.CanExecute (object parameter) inline
Definition at line 21 of file UpdateMessageCommand.cs.
Execute()
async void Messenger.Commands.Messenger.UpdateMessageCommand.Execute (object parameter) inline
Definition at line 26 of file UpdateMessageCommand.cs.
References Messenger.Commands.Messenger.UpdateMessageCommand._logger, Messenger.ViewModels.DataViewModels.MessageViewModel.Content, Messenger.ViewModels.DataViewModels.MessageViewModel.Id, Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set(), and Messenger.Core.Services.MessengerService.UpdateMessage().
Referenced by Messenger.Views.Subcontrols.MessageView.EditAcceptButton_Tapped().
Property Documentation
_logger
ILogger Messenger.Commands.Messenger.UpdateMessageCommand._logger get private
Definition at line 13 of file UpdateMessageCommand.cs.
Referenced by Messenger.Commands.Messenger.UpdateMessageCommand.Execute().
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.Messenger.UpdateMessageCommand.CanExecuteChanged
Definition at line 19 of file UpdateMessageCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/Messenger/UpdateMessageCommand.cs