VPR_Messenger: Messenger.Commands.PrivateChat.RemoveChatCommand Class Reference
Messenger.Commands.PrivateChat.RemoveChatCommand Class Reference
Public Member Functions
bool CanExecute (object parameter)
async void Execute (object parameter)
Events
EventHandler CanExecuteChanged
Detailed Description
Definition at line 11 of file RemoveChatCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.PrivateChat.RemoveChatCommand.CanExecute (object parameter) inline
Definition at line 15 of file RemoveChatCommand.cs.
Execute()
async void Messenger.Commands.PrivateChat.RemoveChatCommand.Execute (object parameter) inline
Definition at line 20 of file RemoveChatCommand.cs.
References Messenger.Core.Services.MessengerService.DeleteTeam(), Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Views.DialogBoxes.OperationConfirmationDialog.Response, Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set(), and Messenger.Views.DialogBoxes.OperationConfirmationDialog.Set().
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.PrivateChat.RemoveChatCommand.CanExecuteChanged
Definition at line 13 of file RemoveChatCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/PrivateChat/RemoveChatCommand.cs