VPR_Messenger: Messenger.Commands.TeamManage.RemoveUserCommand Class Reference
Messenger.Commands.TeamManage.RemoveUserCommand Class Reference
Public Member Functions
RemoveUserCommand ()
bool CanExecute (object parameter)
async void Execute (object parameter)
Events
EventHandler CanExecuteChanged
Detailed Description
Definition at line 10 of file RemoveUserCommand.cs.
Constructor & Destructor Documentation
RemoveUserCommand()
Messenger.Commands.TeamManage.RemoveUserCommand.RemoveUserCommand () inline
Definition at line 12 of file RemoveUserCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.TeamManage.RemoveUserCommand.CanExecute (object parameter) inline
Definition at line 18 of file RemoveUserCommand.cs.
Execute()
async void Messenger.Commands.TeamManage.RemoveUserCommand.Execute (object parameter) inline
Definition at line 23 of file RemoveUserCommand.cs.
References Messenger.Core.Services.UserService.GetUser(), Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Core.Services.MessengerService.RemoveMember(), Messenger.Views.DialogBoxes.OperationConfirmationDialog.Response, Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set(), and Messenger.Views.DialogBoxes.OperationConfirmationDialog.Set().
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.TeamManage.RemoveUserCommand.CanExecuteChanged
Definition at line 16 of file RemoveUserCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/TeamManage/RemoveUserCommand.cs