VPR_Messenger: Messenger.Views.Subcontrols.MessageView Class Reference
Messenger.Views.Subcontrols.MessageView Class Reference
Public Member Functions
MessageView ()
Static Public Attributes
static readonly DependencyProperty MessageProperty
static readonly DependencyProperty ReplyToCommandProperty
static readonly DependencyProperty UpdateMessageCommandProperty
static readonly DependencyProperty DeleteMessageCommandProperty
static readonly DependencyProperty ToggleReactionCommandProperty
Properties
MessageViewModel Message [get, set]
CommandBarOverflowButtonVisibility MyMessageActionsVisibility [get]
ICommand ReplyToCommand [get, set]
ICommand UpdateMessageCommand [get, set]
ICommand DeleteMessageCommand [get, set]
ICommand ToggleReactionCommand [get, set]
Private Member Functions
void ReplyButton_Tapped (object sender, TappedRoutedEventArgs e)
void AppBarButton_Tapped (object sender, TappedRoutedEventArgs e)
void LikeButton_Tapped (object sender, TappedRoutedEventArgs e)
void DislikeButton_Tapped (object sender, TappedRoutedEventArgs e)
void SurprisedButton_Tapped (object sender, TappedRoutedEventArgs e)
void AngryButton_Tapped (object sender, TappedRoutedEventArgs e)
void EditButton_Tapped (object sender, TappedRoutedEventArgs e)
void EditAcceptButton_Tapped (object sender, TappedRoutedEventArgs e)
void EditCancelButton_Tapped (object sender, TappedRoutedEventArgs e)
void EnterEditMode ()
void ExitEditMode ()
void DeleteButton_Tapped (object sender, TappedRoutedEventArgs e)
Detailed Description
Definition at line 19 of file MessageView.xaml.cs.
Constructor & Destructor Documentation
MessageView()
Messenger.Views.Subcontrols.MessageView.MessageView () inline
Definition at line 69 of file MessageView.xaml.cs.
Member Function Documentation
AngryButton_Tapped()
void Messenger.Views.Subcontrols.MessageView.AngryButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 118 of file MessageView.xaml.cs.
References Messenger.Commands.Messenger.ToggleReactionCommand.Execute(), and Messenger.Views.Subcontrols.MessageView.Message.
AppBarButton_Tapped()
void Messenger.Views.Subcontrols.MessageView.AppBarButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 86 of file MessageView.xaml.cs.
DeleteButton_Tapped()
void Messenger.Views.Subcontrols.MessageView.DeleteButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 171 of file MessageView.xaml.cs.
References Messenger.Commands.Messenger.DeleteMessageCommand.Execute(), and Messenger.Views.Subcontrols.MessageView.Message.
DislikeButton_Tapped()
void Messenger.Views.Subcontrols.MessageView.DislikeButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 100 of file MessageView.xaml.cs.
References Messenger.Commands.Messenger.ToggleReactionCommand.Execute(), and Messenger.Views.Subcontrols.MessageView.Message.
EditAcceptButton_Tapped()
void Messenger.Views.Subcontrols.MessageView.EditAcceptButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 136 of file MessageView.xaml.cs.
References Messenger.Commands.Messenger.UpdateMessageCommand.Execute(), Messenger.Views.Subcontrols.MessageView.ExitEditMode(), Messenger.ViewModels.DataViewModels.MessageViewModel.Id, and Messenger.Views.Subcontrols.MessageView.Message.
EditButton_Tapped()
void Messenger.Views.Subcontrols.MessageView.EditButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 131 of file MessageView.xaml.cs.
References Messenger.Views.Subcontrols.MessageView.EnterEditMode().
EditCancelButton_Tapped()
void Messenger.Views.Subcontrols.MessageView.EditCancelButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 152 of file MessageView.xaml.cs.
References Messenger.Views.Subcontrols.MessageView.ExitEditMode().
EnterEditMode()
void Messenger.Views.Subcontrols.MessageView.EnterEditMode () inline private
Definition at line 157 of file MessageView.xaml.cs.
Referenced by Messenger.Views.Subcontrols.MessageView.EditButton_Tapped().
ExitEditMode()
void Messenger.Views.Subcontrols.MessageView.ExitEditMode () inline private
Definition at line 163 of file MessageView.xaml.cs.
Referenced by Messenger.Views.Subcontrols.MessageView.EditAcceptButton_Tapped(), and Messenger.Views.Subcontrols.MessageView.EditCancelButton_Tapped().
LikeButton_Tapped()
void Messenger.Views.Subcontrols.MessageView.LikeButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 91 of file MessageView.xaml.cs.
References Messenger.Commands.Messenger.ToggleReactionCommand.Execute(), and Messenger.Views.Subcontrols.MessageView.Message.
ReplyButton_Tapped()
void Messenger.Views.Subcontrols.MessageView.ReplyButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 78 of file MessageView.xaml.cs.
References Messenger.Views.Subcontrols.MessageView.Message, and Messenger.Views.Subcontrols.MessageView.ReplyToCommand.
SurprisedButton_Tapped()
void Messenger.Views.Subcontrols.MessageView.SurprisedButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 109 of file MessageView.xaml.cs.
References Messenger.Commands.Messenger.ToggleReactionCommand.Execute(), and Messenger.Views.Subcontrols.MessageView.Message.
Member Data Documentation
DeleteMessageCommandProperty
readonly DependencyProperty Messenger.Views.Subcontrols.MessageView.DeleteMessageCommandProperty static
Initial value:
=
            DependencyProperty.Register("DeleteMessageCommand", typeof(ICommand), typeof(MessageView), new PropertyMetadata(null))
Definition at line 56 of file MessageView.xaml.cs.
MessageProperty
readonly DependencyProperty Messenger.Views.Subcontrols.MessageView.MessageProperty static
Initial value:
=
            DependencyProperty.Register("Message", typeof(MessageViewModel), typeof(MessageView), new PropertyMetadata(null))
Definition at line 27 of file MessageView.xaml.cs.
ReplyToCommandProperty
readonly DependencyProperty Messenger.Views.Subcontrols.MessageView.ReplyToCommandProperty static
Initial value:
=
            DependencyProperty.Register("ReplyToCommand", typeof(ICommand), typeof(MessageView), new PropertyMetadata(null))
Definition at line 38 of file MessageView.xaml.cs.
ToggleReactionCommandProperty
readonly DependencyProperty Messenger.Views.Subcontrols.MessageView.ToggleReactionCommandProperty static
Initial value:
=
            DependencyProperty.Register("ToggleReactionCommand", typeof(ICommand), typeof(MessageView), new PropertyMetadata(null))
Definition at line 65 of file MessageView.xaml.cs.
UpdateMessageCommandProperty
readonly DependencyProperty Messenger.Views.Subcontrols.MessageView.UpdateMessageCommandProperty static
Initial value:
=
            DependencyProperty.Register("UpdateMessageCommand", typeof(ICommand), typeof(MessageView), new PropertyMetadata(null))
Definition at line 47 of file MessageView.xaml.cs.
Property Documentation
DeleteMessageCommand
ICommand Messenger.Views.Subcontrols.MessageView.DeleteMessageCommand get set
Definition at line 50 of file MessageView.xaml.cs.
Message
MessageViewModel Messenger.Views.Subcontrols.MessageView.Message get set
Definition at line 21 of file MessageView.xaml.cs.
Referenced by Messenger.Views.Subcontrols.MessageView.AngryButton_Tapped(), Messenger.Views.Subcontrols.MessageView.DeleteButton_Tapped(), Messenger.Views.Subcontrols.MessageView.DislikeButton_Tapped(), Messenger.Views.Subcontrols.MessageView.EditAcceptButton_Tapped(), Messenger.Views.Subcontrols.MessageView.LikeButton_Tapped(), Messenger.Views.Subcontrols.MessageView.ReplyButton_Tapped(), and Messenger.Views.Subcontrols.MessageView.SurprisedButton_Tapped().
MyMessageActionsVisibility
CommandBarOverflowButtonVisibility Messenger.Views.Subcontrols.MessageView.MyMessageActionsVisibility get
Definition at line 30 of file MessageView.xaml.cs.
ReplyToCommand
ICommand Messenger.Views.Subcontrols.MessageView.ReplyToCommand get set
Definition at line 32 of file MessageView.xaml.cs.
Referenced by Messenger.Views.Subcontrols.MessageView.ReplyButton_Tapped().
ToggleReactionCommand
ICommand Messenger.Views.Subcontrols.MessageView.ToggleReactionCommand get set
Definition at line 59 of file MessageView.xaml.cs.
UpdateMessageCommand
ICommand Messenger.Views.Subcontrols.MessageView.UpdateMessageCommand get set
Definition at line 41 of file MessageView.xaml.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Views/Subcontrols/MessageView.xaml.cs