VPR_Messenger: Messenger.Views.DialogBoxes.ManageRolesDialog Class Reference
Messenger.Views.DialogBoxes.ManageRolesDialog Class Reference
Public Member Functions
ManageRolesDialog ()
Independent content dialog with own view model to add, remove and update team roles
Protected Member Functions
override void OnApplyTemplate ()
Properties
ManageRolesDialogViewModel ViewModel = new ManageRolesDialogViewModel() [get]
List< ToolTip > OpenTooltips [get, set]
List< Button > ActivatedButtons [get, set]
Color OriginalColor [get, set]
string OriginalTitle [get, set]
Private Member Functions
void TeamRolesListBox_SelectionChanged (object sender, SelectionChangedEventArgs e)
void RemoveTeamRoleButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
void ColorPickerOkButton_Click (object sender, RoutedEventArgs e)
void ColorPickerCancelButton_Click (object sender, RoutedEventArgs e)
void ColorPicker_ColorChanged (ColorPicker sender, ColorChangedEventArgs args)
void ColorPicker_Loaded (object sender, RoutedEventArgs e)
void EditTitleButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
void EditTitleAcceptButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
void EditTitleCancelButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
void RevokePermissionButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
void GrantablePermission_Checked (object sender, RoutedEventArgs e)
void UpdateTeamRoleButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
void CloseButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
void ClearAll ()
Detailed Description
Definition at line 14 of file ManageRolesDialog.xaml.cs.
Constructor & Destructor Documentation
ManageRolesDialog()
Messenger.Views.DialogBoxes.ManageRolesDialog.ManageRolesDialog () inline
Independent content dialog with own view model to add, remove and update team roles
Definition at line 33 of file ManageRolesDialog.xaml.cs.
References Messenger.Views.DialogBoxes.ManageRolesDialog.ActivatedButtons, and Messenger.Views.DialogBoxes.ManageRolesDialog.OpenTooltips.
Member Function Documentation
ClearAll()
void Messenger.Views.DialogBoxes.ManageRolesDialog.ClearAll () inline private
Definition at line 234 of file ManageRolesDialog.xaml.cs.
References Messenger.Views.DialogBoxes.ManageRolesDialog.ActivatedButtons, and Messenger.Views.DialogBoxes.ManageRolesDialog.OpenTooltips.
Referenced by Messenger.Views.DialogBoxes.ManageRolesDialog.CloseButton_Tapped(), and Messenger.Views.DialogBoxes.ManageRolesDialog.TeamRolesListBox_SelectionChanged().
CloseButton_Tapped()
void Messenger.Views.DialogBoxes.ManageRolesDialog.CloseButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e) inline private
Definition at line 222 of file ManageRolesDialog.xaml.cs.
References Messenger.Views.DialogBoxes.ManageRolesDialog.ClearAll(), Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.OnTeamUpdated(), and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
ColorPicker_ColorChanged()
void Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPicker_ColorChanged (ColorPicker sender, ColorChangedEventArgs args) inline private
Definition at line 124 of file ManageRolesDialog.xaml.cs.
References Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Color, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.PendingChange, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
ColorPicker_Loaded()
void Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPicker_Loaded (object sender, RoutedEventArgs e) inline private
Definition at line 129 of file ManageRolesDialog.xaml.cs.
References Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Color, Messenger.Views.DialogBoxes.ManageRolesDialog.OriginalColor, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.SelectedTeamRole, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
ColorPickerCancelButton_Click()
void Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPickerCancelButton_Click (object sender, RoutedEventArgs e) inline private
Definition at line 118 of file ManageRolesDialog.xaml.cs.
References Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Color, Messenger.Views.DialogBoxes.ManageRolesDialog.OriginalColor, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.PendingChange, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
ColorPickerOkButton_Click()
void Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPickerOkButton_Click (object sender, RoutedEventArgs e) inline private
Definition at line 107 of file ManageRolesDialog.xaml.cs.
References Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Color, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.HasChanged, Messenger.Views.DialogBoxes.ManageRolesDialog.OriginalColor, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.PendingChange, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
EditTitleAcceptButton_Tapped()
void Messenger.Views.DialogBoxes.ManageRolesDialog.EditTitleAcceptButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e) inline private
Definition at line 144 of file ManageRolesDialog.xaml.cs.
References Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.HasChanged, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.IsInEditMode, Messenger.Views.DialogBoxes.ManageRolesDialog.OriginalTitle, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.PendingChange, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Title, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
EditTitleButton_Tapped()
void Messenger.Views.DialogBoxes.ManageRolesDialog.EditTitleButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e) inline private
Definition at line 138 of file ManageRolesDialog.xaml.cs.
References Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.IsInEditMode, Messenger.Views.DialogBoxes.ManageRolesDialog.OriginalTitle, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.SelectedTeamRole, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Title, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
EditTitleCancelButton_Tapped()
void Messenger.Views.DialogBoxes.ManageRolesDialog.EditTitleCancelButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e) inline private
Definition at line 154 of file ManageRolesDialog.xaml.cs.
References Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.IsInEditMode, Messenger.Views.DialogBoxes.ManageRolesDialog.OriginalTitle, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.PendingChange, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Title, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
GrantablePermission_Checked()
void Messenger.Views.DialogBoxes.ManageRolesDialog.GrantablePermission_Checked (object sender, RoutedEventArgs e) inline private
Definition at line 196 of file ManageRolesDialog.xaml.cs.
References Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.GrantablePermissions, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.HasChanged, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.PendingChange, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.PendingPermissions, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Permissions, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
OnApplyTemplate()
override void Messenger.Views.DialogBoxes.ManageRolesDialog.OnApplyTemplate () inline protected
Definition at line 41 of file ManageRolesDialog.xaml.cs.
References Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.OnTeamUpdated(), and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
RemoveTeamRoleButton_Tapped()
void Messenger.Views.DialogBoxes.ManageRolesDialog.RemoveTeamRoleButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e) inline private
Definition at line 71 of file ManageRolesDialog.xaml.cs.
References Messenger.Views.DialogBoxes.ManageRolesDialog.OpenTooltips, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.RemoveTeamRoleCommand, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
RevokePermissionButton_Tapped()
void Messenger.Views.DialogBoxes.ManageRolesDialog.RevokePermissionButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e) inline private
Definition at line 164 of file ManageRolesDialog.xaml.cs.
References Messenger.Views.DialogBoxes.ManageRolesDialog.OpenTooltips, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.RevokePermissionCommand, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
TeamRolesListBox_SelectionChanged()
void Messenger.Views.DialogBoxes.ManageRolesDialog.TeamRolesListBox_SelectionChanged (object sender, SelectionChangedEventArgs e) inline private
Definition at line 50 of file ManageRolesDialog.xaml.cs.
References Messenger.Views.DialogBoxes.ManageRolesDialog.ClearAll(), Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Color, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.FilterGrantablePermissions(), Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.HasChanged, Messenger.Views.DialogBoxes.ManageRolesDialog.OriginalColor, Messenger.Views.DialogBoxes.ManageRolesDialog.OriginalTitle, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.PendingChange, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Title, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
UpdateTeamRoleButton_Tapped()
void Messenger.Views.DialogBoxes.ManageRolesDialog.UpdateTeamRoleButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e) inline private
Definition at line 217 of file ManageRolesDialog.xaml.cs.
References Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.PendingChange, Messenger.ViewModels.DialogBoxes.ManageRolesDialogViewModel.UpdateTeamRoleCommand, and Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel.
Property Documentation
ActivatedButtons
List<Button> Messenger.Views.DialogBoxes.ManageRolesDialog.ActivatedButtons get set
Definition at line 22 of file ManageRolesDialog.xaml.cs.
Referenced by Messenger.Views.DialogBoxes.ManageRolesDialog.ClearAll(), and Messenger.Views.DialogBoxes.ManageRolesDialog.ManageRolesDialog().
OpenTooltips
List<ToolTip> Messenger.Views.DialogBoxes.ManageRolesDialog.OpenTooltips get set
Definition at line 20 of file ManageRolesDialog.xaml.cs.
Referenced by Messenger.Views.DialogBoxes.ManageRolesDialog.ClearAll(), Messenger.Views.DialogBoxes.ManageRolesDialog.ManageRolesDialog(), Messenger.Views.DialogBoxes.ManageRolesDialog.RemoveTeamRoleButton_Tapped(), and Messenger.Views.DialogBoxes.ManageRolesDialog.RevokePermissionButton_Tapped().
OriginalColor
Color Messenger.Views.DialogBoxes.ManageRolesDialog.OriginalColor get set
Definition at line 26 of file ManageRolesDialog.xaml.cs.
Referenced by Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPicker_Loaded(), Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPickerCancelButton_Click(), Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPickerOkButton_Click(), and Messenger.Views.DialogBoxes.ManageRolesDialog.TeamRolesListBox_SelectionChanged().
OriginalTitle
string Messenger.Views.DialogBoxes.ManageRolesDialog.OriginalTitle get set
Definition at line 28 of file ManageRolesDialog.xaml.cs.
Referenced by Messenger.Views.DialogBoxes.ManageRolesDialog.EditTitleAcceptButton_Tapped(), Messenger.Views.DialogBoxes.ManageRolesDialog.EditTitleButton_Tapped(), Messenger.Views.DialogBoxes.ManageRolesDialog.EditTitleCancelButton_Tapped(), and Messenger.Views.DialogBoxes.ManageRolesDialog.TeamRolesListBox_SelectionChanged().
ViewModel
ManageRolesDialogViewModel Messenger.Views.DialogBoxes.ManageRolesDialog.ViewModel = new ManageRolesDialogViewModel() get
Definition at line 16 of file ManageRolesDialog.xaml.cs.
Referenced by Messenger.Views.DialogBoxes.ManageRolesDialog.CloseButton_Tapped(), Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPicker_ColorChanged(), Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPicker_Loaded(), Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPickerCancelButton_Click(), Messenger.Views.DialogBoxes.ManageRolesDialog.ColorPickerOkButton_Click(), Messenger.Views.DialogBoxes.ManageRolesDialog.EditTitleAcceptButton_Tapped(), Messenger.Views.DialogBoxes.ManageRolesDialog.EditTitleButton_Tapped(), Messenger.Views.DialogBoxes.ManageRolesDialog.EditTitleCancelButton_Tapped(), Messenger.Views.DialogBoxes.ManageRolesDialog.GrantablePermission_Checked(), Messenger.Views.DialogBoxes.ManageRolesDialog.OnApplyTemplate(), Messenger.Views.DialogBoxes.ManageRolesDialog.RemoveTeamRoleButton_Tapped(), Messenger.Views.DialogBoxes.ManageRolesDialog.RevokePermissionButton_Tapped(), Messenger.Views.DialogBoxes.ManageRolesDialog.TeamRolesListBox_SelectionChanged(), and Messenger.Views.DialogBoxes.ManageRolesDialog.UpdateTeamRoleButton_Tapped().
The documentation for this class was generated from the following file:
Messenger/Messenger/Views/DialogBoxes/ManageRolesDialog.xaml.cs