VPR_Messenger: Messenger.Commands.PrivateChat.StartChatWithUserCommand Class Reference
Messenger.Commands.PrivateChat.StartChatWithUserCommand Class Reference
Public Member Functions
StartChatWithUserCommand ()
bool CanExecute (object parameter)
async void Execute (object parameter)
Opens the dialog to start a new private chat
Events
EventHandler CanExecuteChanged
Detailed Description
Definition at line 14 of file StartChatWithUserCommand.cs.
Constructor & Destructor Documentation
StartChatWithUserCommand()
Messenger.Commands.PrivateChat.StartChatWithUserCommand.StartChatWithUserCommand () inline
Definition at line 20 of file StartChatWithUserCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.PrivateChat.StartChatWithUserCommand.CanExecute (object parameter) inline
Definition at line 24 of file StartChatWithUserCommand.cs.
Execute()
async void Messenger.Commands.PrivateChat.StartChatWithUserCommand.Execute (object parameter) inline
Opens the dialog to start a new private chat
Definition at line 32 of file StartChatWithUserCommand.cs.
References Messenger.Helpers.CacheQuery.GetMyChats(), Messenger.ViewModels.DataViewModels.UserViewModel.Id, Messenger.ViewModels.DataViewModels.PrivateChatViewModel.Partner, Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set(), and Messenger.Core.Services.MessengerService.StartChat().
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.PrivateChat.StartChatWithUserCommand.CanExecuteChanged
Definition at line 18 of file StartChatWithUserCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/PrivateChat/StartChatWithUserCommand.cs