VPR_Messenger: Messenger.Core.Services.UserService Class Reference
Messenger.Core.Services.UserService Class Reference
Holds helpers and static methods to interact with users on the DB
Static Public Member Functions
static async Task< bool > Update (string userId, string columnToChange, string newVal)
Update a specified column for a specified user. /summary>
Parameters
userId The id of the user, whose data will be updated
columnToChange The column to update for the user
newVal The new value for the specifed column for the specified user
Returns
True if no exceptions occured while executing the query and it affected at least one entry, false otherwise
static async Task< bool > UpdateUsername (string userId, string newUsername)
Update a specified users name /summary>
Parameters
userId The id of the user, whose name will be updated
newUsername The new username to set
Returns
True if no exceptions occured while executing the query, false otherwise
static async Task< bool > UpdateUserMail (string userId, string newMail)
Update a specified users email /summary>
Parameters
userId The id of the user, whose email will be updated
newMail The new email to set
Returns
True if no exceptions occured while executing the query, false otherwise
static async Task< bool > UpdateUserPhoto (string userId, string newPhoto)
Update a specified users photo /summary>
Parameters
userId The id of the user, whose photo will be updated
newPhoto The new photo to set
Returns
True if no exceptions occured while executing the query, false otherwise
static async Task< bool > UpdateUserBio (string userId, string newBio)
Update a specified users bio /summary>
Parameters
userId The id of the user, whose bio will be updated
newBio The new bio to set
Returns
True if no exceptions occured while executing the query, false otherwise
static async Task< User > GetOrCreateApplicationUser (User userdata)
Create or retrieve an application user from a specified user object holding a GraphService Id.
static async Task< bool > DeleteUser (string userId)
Delete the user with the specified userId.
static async Task< User > GetUser (string userId)
Construct a User object from data that belongs to the user identified by userId.
static async Task< User > GetUser (string userName, uint nameId)
Construct a User object from a given UserName and NameId
static async Task< IList< string > > SearchUser (string userName)
Retrieve the UserNames and NameIds of the top 10 matches for the given userName
Static Private Member Functions
static async Task< uint?> DetermineNewNameId (string username, SqlConnection connection)
Determine a usernames new NameId.
Detailed Description
Holds helpers and static methods to interact with users on the DB
Definition at line 16 of file UserService.cs.
Member Function Documentation
DeleteUser()
static async Task<bool> Messenger.Core.Services.UserService.DeleteUser (string userId) inline static
Delete the user with the specified userId.
Parameters
userId The id of the user, whose data will be updated
Returns
True if no exceptions occured while executing the query, false otherwise
Definition at line 278 of file UserService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
DetermineNewNameId()
static async Task<uint?> Messenger.Core.Services.UserService.DetermineNewNameId (string username, SqlConnection connection) inline static private
Determine a usernames new NameId.
Parameters
username A username whose nameid is the be determined
connection A connection to the sql database
returns>Null on database errors, the appropriate NameId otherwise
Definition at line 396 of file UserService.cs.
Referenced by Messenger.Core.Services.UserService.GetOrCreateApplicationUser(), and Messenger.Core.Services.UserService.UpdateUsername().
GetOrCreateApplicationUser()
static async Task<User> Messenger.Core.Services.UserService.GetOrCreateApplicationUser (User userdata) inline static
Create or retrieve an application user from a specified user object holding a GraphService Id.
Parameters
userdata A user object holding a GraphService id which will be used to retrieve or create a user
Returns
The existing or newly created User object
Definition at line 180 of file UserService.cs.
References Messenger.Core.Services.UserService.DetermineNewNameId(), Messenger.Core.Models.User.DisplayName, Messenger.Core.Helpers.SqlHelpers.GetRows(), Messenger.Core.Models.User.NameId, Messenger.Core.Helpers.SqlHelpers.NonQueryAsync(), Messenger.Core.Models.User.Photo, Messenger.Core.Services.FileSharingService.UploadFromBase64(), Messenger.Core.Helpers.Mapper.UserFromDataRow(), and Messenger.Core.Helpers.Mapper.UserFromMSGraph().
Referenced by Messenger.Services.UserDataService.GetUserViewModelFromData().
GetUser() [1/2]
static async Task<User> Messenger.Core.Services.UserService.GetUser (string userId) inline static
Construct a User object from data that belongs to the user identified by userId.
Parameters
userId The id of the user to retrieve
Returns
A full User object
Definition at line 301 of file UserService.cs.
References Messenger.Core.Helpers.SqlHelpers.GetRows(), and Messenger.Core.Helpers.Mapper.UserFromDataRow().
Referenced by Messenger.Core.Services.MessengerService.AssignUserRole(), Messenger.Commands.TeamManage.RemoveUserCommand.Execute(), Messenger.ViewModels.Controls.UserSearchPanelViewModel.GetSelectedUser(), Messenger.Core.Services.MessengerService.GetUserWithNameId(), Messenger.Core.Services.MessengerService.RemoveMember(), Messenger.Core.Services.MentionService.ResolveMentions(), Messenger.Core.Services.MessengerService.SendInvitation(), Messenger.Core.Services.MessengerService.UnassignUserRole(), Messenger.Core.Services.MessengerService.UpdateUserBio(), Messenger.Core.Services.MessengerService.UpdateUserEmail(), Messenger.Core.Services.MessengerService.UpdateUserPhoto(), Messenger.Core.Services.MessengerService.UpdateUserUsername(), and Messenger.Helpers.MessageHelpers.MessageBuilder.WithSender().
GetUser() [2/2]
static async Task<User> Messenger.Core.Services.UserService.GetUser (string userName, uint nameId) inline static
Construct a User object from a given UserName and NameId
Parameters
userName The Name of the user to retrieve
nameId The NameId of the user to retrieve
Returns
A full User object
Definition at line 333 of file UserService.cs.
References Messenger.Core.Helpers.Mapper.UserFromDataRow().
SearchUser()
static async Task<IList<string> > Messenger.Core.Services.UserService.SearchUser (string userName) inline static
Retrieve the UserNames and NameIds of the top 10 matches for the given userName
Parameters
userName User name to retrieve matches for
Returns
List of top 10 matched User names
Definition at line 362 of file UserService.cs.
References Messenger.Core.Helpers.SqlHelpers.GetRows().
Referenced by Messenger.ViewModels.Controls.UserSearchPanelViewModel.Search().
Update()
static async Task<bool> Messenger.Core.Services.UserService.Update (string userId, string columnToChange, string newVal) inline static
Update a specified column for a specified user. /summary>
Parameters
userId The id of the user, whose data will be updated
columnToChange The column to update for the user
newVal The new value for the specifed column for the specified user
Returns
True if no exceptions occured while executing the query and it affected at least one entry, false otherwise
Definition at line 27 of file UserService.cs.
References Messenger.Core.Helpers.SqlHelpers.GetColumnType(), Messenger.Core.Helpers.SqlHelpers.NonQueryAsync(), and Messenger.Core.Services.UserService.UpdateUsername().
UpdateUserBio()
static async Task<bool> Messenger.Core.Services.UserService.UpdateUserBio (string userId, string newBio) inline static
Update a specified users bio /summary>
Parameters
userId The id of the user, whose bio will be updated
newBio The new bio to set
Returns
True if no exceptions occured while executing the query, false otherwise
Definition at line 156 of file UserService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.UpdateUserBio().
UpdateUserMail()
static async Task<bool> Messenger.Core.Services.UserService.UpdateUserMail (string userId, string newMail) inline static
Update a specified users email /summary>
Parameters
userId The id of the user, whose email will be updated
newMail The new email to set
Returns
True if no exceptions occured while executing the query, false otherwise
Definition at line 105 of file UserService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.UpdateUserEmail().
UpdateUsername()
static async Task<bool> Messenger.Core.Services.UserService.UpdateUsername (string userId, string newUsername) inline static
Update a specified users name /summary>
Parameters
userId The id of the user, whose name will be updated
newUsername The new username to set
Returns
True if no exceptions occured while executing the query, false otherwise
Definition at line 63 of file UserService.cs.
References Messenger.Core.Services.UserService.DetermineNewNameId(), and Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.UserService.Update(), and Messenger.Core.Services.MessengerService.UpdateUserUsername().
UpdateUserPhoto()
static async Task<bool> Messenger.Core.Services.UserService.UpdateUserPhoto (string userId, string newPhoto) inline static
Update a specified users photo /summary>
Parameters
userId The id of the user, whose photo will be updated
newPhoto The new photo to set
Returns
True if no exceptions occured while executing the query, false otherwise
Definition at line 130 of file UserService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.UpdateUserPhoto().
The documentation for this class was generated from the following file:
Messenger/Messenger.Core/Services/UserService.cs