VPR_Messenger: Messenger.Core.Services.ChannelService Class Reference
Messenger.Core.Services.ChannelService Class Reference
A class holding static methods to interact with channels on the DB
Static Public Member Functions
static async Task< uint?> CreateChannel (string channelName, uint teamId)
Creates a Channel with the given name inside the specified team
static async Task< bool > RemoveChannel (uint channelId)
Deletes a channel with a given channelId
static async Task< bool > RemoveAllChannels (uint teamId)
Deletes all channel from a specified team
static async Task< bool > RenameChannel (string channelName, uint channelId)
Rename a specified channel
static async Task< Channel > GetChannel (uint channelId)
Construct a Channel object from data that belongs to the channel identified by channelId.
static async Task< bool > PinMessage (uint messageId, uint channelId)
Pin a specified message in the specified channel
static async Task< bool > UnPinMessage (uint messageId, uint channelId)
Unpin a specified message in the specified channel
static async Task< IEnumerable< Message > > RetrievePinnedMessages (uint channelId)
Retrieve the pinned messages of a channel
Detailed Description
A class holding static methods to interact with channels on the DB
Definition at line 16 of file ChannelService.cs.
Member Function Documentation
CreateChannel()
static async Task<uint?> Messenger.Core.Services.ChannelService.CreateChannel (string channelName, uint teamId) inline static
Creates a Channel with the given name inside the specified team
Parameters
channelName Name of the channel
teamId Id of the team to create the channel in
Returns
The id of the created channel if it was created successfully, null otherwise
Definition at line 24 of file ChannelService.cs.
Referenced by Messenger.Core.Services.MessengerService.CreateChannel(), Messenger.Core.Services.MessengerService.CreateTeam(), and Messenger.Core.Services.MessengerService.StartChat().
GetChannel()
static async Task<Channel> Messenger.Core.Services.ChannelService.GetChannel (uint channelId) inline static
Construct a Channel object from data that belongs to the channel identified by channelId.
Parameters
channelId The id of the channel to retrieve
Returns
Definition at line 108 of file ChannelService.cs.
References Messenger.Core.Helpers.Mapper.ChannelFromDataRow(), and Messenger.Core.Helpers.SqlHelpers.GetRows().
Referenced by Messenger.Core.Services.MessengerService.CreateChannel(), Messenger.Core.Services.MessengerService.DeleteChannel(), Messenger.Core.Services.MessengerService.RenameChannel(), Messenger.Core.Services.MentionService.ResolveMentions(), and Messenger.Helpers.MessageHelpers.MessageBuilder.WithSender().
PinMessage()
static async Task<bool> Messenger.Core.Services.ChannelService.PinMessage (uint messageId, uint channelId) inline static
Pin a specified message in the specified channel
Parameters
messageId The id of the message to pin
channelId The id of the channel to pin the message in
Returns
True on success, false on failure
Definition at line 143 of file ChannelService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
RemoveAllChannels()
static async Task<bool> Messenger.Core.Services.ChannelService.RemoveAllChannels (uint teamId) inline static
Deletes all channel from a specified team
Parameters
teamId The id of the team to clear the channels from
Returns
True if no exceptions occured while executing the query and it affected at least one query, false otherwise
Definition at line 69 of file ChannelService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.DeleteTeam().
RemoveChannel()
static async Task<bool> Messenger.Core.Services.ChannelService.RemoveChannel (uint channelId) inline static
Deletes a channel with a given channelId
Parameters
channelId The id of the channel to delete
Returns
True if no exceptions occured while executing the query and it affected at least one query, false otherwise
Definition at line 49 of file ChannelService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.DeleteChannel().
RenameChannel()
static async Task<bool> Messenger.Core.Services.ChannelService.RenameChannel (string channelName, uint channelId) inline static
Rename a specified channel
Parameters
channelName the new name of the channel>
channelId the id of the channel to rename
Returns
True, if the channel got renamed successfully, false otherwise
Definition at line 91 of file ChannelService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.RenameChannel().
RetrievePinnedMessages()
static async Task<IEnumerable<Message> > Messenger.Core.Services.ChannelService.RetrievePinnedMessages (uint channelId) inline static
Retrieve the pinned messages of a channel
Parameters
channelId The channel to retrieve pinned messages from
Returns
An enumerable of message objects representing the pinned messages
Definition at line 192 of file ChannelService.cs.
References Messenger.Core.Helpers.Mapper.MessageFromDataRow().
UnPinMessage()
static async Task<bool> Messenger.Core.Services.ChannelService.UnPinMessage (uint messageId, uint channelId) inline static
Unpin a specified message in the specified channel
Parameters
messageId The id of the message to Unpin
channelId The id of the channel to Unpin the message in
Returns
True on success, false on failure
Definition at line 168 of file ChannelService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
The documentation for this class was generated from the following file:
Messenger/Messenger.Core/Services/ChannelService.cs