VPR_Messenger: Messenger.ViewModels.Pages.TeamManageViewModel Class Reference
Messenger.ViewModels.Pages.TeamManageViewModel Class Reference
Public Member Functions
TeamManageViewModel ()
Protected Member Functions
void Set< T > (ref T storage, T value, [CallerMemberName]string propertyName=null)
void OnPropertyChanged (string propertyName)
Properties
ICommand CreateChannelCommand [get]
ICommand InviteUserCommand [get]
ICommand RemoveChannelClick [get]
ICommand NavigateBackCommand [get]
UserViewModel CurrentUser [get]
TeamViewModel SelectedTeam [get]
MembersListControlViewModel MembersListControlViewModel [get, set]
UserSearchPanelViewModel UserSearchPanelViewModel [get, set]
Events
PropertyChangedEventHandler PropertyChanged
Private Member Functions
bool UserSearchFilter (string resultString)
Detailed Description
Definition at line 21 of file TeamManageViewModel.cs.
Constructor & Destructor Documentation
TeamManageViewModel()
Messenger.ViewModels.Pages.TeamManageViewModel.TeamManageViewModel () inline
Definition at line 39 of file TeamManageViewModel.cs.
References Messenger.ViewModels.Pages.TeamManageViewModel.MembersListControlViewModel, Messenger.ViewModels.Pages.TeamManageViewModel.UserSearchFilter(), and Messenger.ViewModels.Pages.TeamManageViewModel.UserSearchPanelViewModel.
Member Function Documentation
OnPropertyChanged()
void Messenger.Helpers.Observable.OnPropertyChanged (string propertyName) protected inherited
Referenced by Messenger.Helpers.Observable.Set< T >().
Set< T >()
void Messenger.Helpers.Observable.Set< T > (ref T storage, T value, [CallerMemberName] string propertyName = null) inline protected inherited
Definition at line 11 of file Observable.cs.
References Messenger.Helpers.Observable.OnPropertyChanged().
UserSearchFilter()
bool Messenger.ViewModels.Pages.TeamManageViewModel.UserSearchFilter (string resultString) inline private
Definition at line 45 of file TeamManageViewModel.cs.
References Messenger.ViewModels.DataViewModels.TeamViewModel.Members, and Messenger.ViewModels.Pages.TeamManageViewModel.SelectedTeam.
Referenced by Messenger.ViewModels.Pages.TeamManageViewModel.TeamManageViewModel().
Property Documentation
CreateChannelCommand
ICommand Messenger.ViewModels.Pages.TeamManageViewModel.CreateChannelCommand get
Definition at line 23 of file TeamManageViewModel.cs.
CurrentUser
UserViewModel Messenger.ViewModels.Pages.TeamManageViewModel.CurrentUser get
Definition at line 31 of file TeamManageViewModel.cs.
InviteUserCommand
ICommand Messenger.ViewModels.Pages.TeamManageViewModel.InviteUserCommand get
Definition at line 25 of file TeamManageViewModel.cs.
MembersListControlViewModel
MembersListControlViewModel Messenger.ViewModels.Pages.TeamManageViewModel.MembersListControlViewModel get set
Definition at line 35 of file TeamManageViewModel.cs.
Referenced by Messenger.ViewModels.Pages.TeamManageViewModel.TeamManageViewModel().
NavigateBackCommand
ICommand Messenger.ViewModels.Pages.TeamManageViewModel.NavigateBackCommand get
Definition at line 29 of file TeamManageViewModel.cs.
RemoveChannelClick
ICommand Messenger.ViewModels.Pages.TeamManageViewModel.RemoveChannelClick get
Definition at line 27 of file TeamManageViewModel.cs.
SelectedTeam
TeamViewModel Messenger.ViewModels.Pages.TeamManageViewModel.SelectedTeam get
Definition at line 33 of file TeamManageViewModel.cs.
Referenced by Messenger.ViewModels.Pages.TeamManageViewModel.UserSearchFilter().
UserSearchPanelViewModel
UserSearchPanelViewModel Messenger.ViewModels.Pages.TeamManageViewModel.UserSearchPanelViewModel get set
Definition at line 37 of file TeamManageViewModel.cs.
Referenced by Messenger.ViewModels.Pages.TeamManageViewModel.TeamManageViewModel().
Event Documentation
PropertyChanged
PropertyChangedEventHandler Messenger.Helpers.Observable.PropertyChanged inherited
Definition at line 9 of file Observable.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/ViewModels/Pages/TeamManageViewModel.cs