VPR_Messenger: Messenger.Commands.TeamManage.RemoveChannelCommand Class Reference
Messenger.Commands.TeamManage.RemoveChannelCommand Class Reference
Public Member Functions
bool CanExecute (object parameter)
async void Execute (object parameter)
Events
EventHandler CanExecuteChanged
Detailed Description
Definition at line 11 of file RemoveChannelCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.TeamManage.RemoveChannelCommand.CanExecute (object parameter) inline
Definition at line 15 of file RemoveChannelCommand.cs.
Execute()
async void Messenger.Commands.TeamManage.RemoveChannelCommand.Execute (object parameter) inline
Definition at line 20 of file RemoveChannelCommand.cs.
References Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, Messenger.Core.Services.MessengerService.DeleteChannel(), Messenger.Views.DialogBoxes.OperationConfirmationDialog.Response, Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set(), and Messenger.Views.DialogBoxes.OperationConfirmationDialog.Set().
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.TeamManage.RemoveChannelCommand.CanExecuteChanged
Definition at line 13 of file RemoveChannelCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/TeamManage/RemoveChannelCommand.cs