VPR_Messenger: Messenger.Views.Subcontrols.ReplyView Class Reference
Messenger.Views.Subcontrols.ReplyView Class Reference
Public Member Functions
ReplyView ()
Static Public Attributes
static readonly DependencyProperty ReplyProperty
Properties
MessageViewModel Reply [get, set]
ICommand ToggleReactionCommand [get]
ICommand DeleteReplyCommand [get]
Private Member Functions
void AppBarButton_Tapped (object sender, TappedRoutedEventArgs e)
void LikeButton_Tapped (object sender, TappedRoutedEventArgs e)
void DislikeButton_Tapped (object sender, TappedRoutedEventArgs e)
void SurprisedButton_Tapped (object sender, TappedRoutedEventArgs e)
void AngryButton_Tapped (object sender, TappedRoutedEventArgs e)
Detailed Description
Definition at line 12 of file ReplyView.xaml.cs.
Constructor & Destructor Documentation
ReplyView()
Messenger.Views.Subcontrols.ReplyView.ReplyView () inline
Definition at line 28 of file ReplyView.xaml.cs.
Member Function Documentation
AngryButton_Tapped()
void Messenger.Views.Subcontrols.ReplyView.AngryButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 64 of file ReplyView.xaml.cs.
References Messenger.Commands.Messenger.ToggleReactionCommand.Execute(), and Messenger.Views.Subcontrols.ReplyView.Reply.
AppBarButton_Tapped()
void Messenger.Views.Subcontrols.ReplyView.AppBarButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 33 of file ReplyView.xaml.cs.
DislikeButton_Tapped()
void Messenger.Views.Subcontrols.ReplyView.DislikeButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 46 of file ReplyView.xaml.cs.
References Messenger.Commands.Messenger.ToggleReactionCommand.Execute(), and Messenger.Views.Subcontrols.ReplyView.Reply.
LikeButton_Tapped()
void Messenger.Views.Subcontrols.ReplyView.LikeButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 38 of file ReplyView.xaml.cs.
References Messenger.Commands.Messenger.ToggleReactionCommand.Execute(), and Messenger.Views.Subcontrols.ReplyView.Reply.
SurprisedButton_Tapped()
void Messenger.Views.Subcontrols.ReplyView.SurprisedButton_Tapped (object sender, TappedRoutedEventArgs e) inline private
Definition at line 55 of file ReplyView.xaml.cs.
References Messenger.Commands.Messenger.ToggleReactionCommand.Execute(), and Messenger.Views.Subcontrols.ReplyView.Reply.
Member Data Documentation
ReplyProperty
readonly DependencyProperty Messenger.Views.Subcontrols.ReplyView.ReplyProperty static
Initial value:
=
            DependencyProperty.Register("Reply", typeof(MessageViewModel), typeof(ReplyView), new PropertyMetadata(new MessageViewModel()))
Definition at line 20 of file ReplyView.xaml.cs.
Property Documentation
DeleteReplyCommand
ICommand Messenger.Views.Subcontrols.ReplyView.DeleteReplyCommand get
Definition at line 25 of file ReplyView.xaml.cs.
Reply
MessageViewModel Messenger.Views.Subcontrols.ReplyView.Reply get set
Definition at line 14 of file ReplyView.xaml.cs.
Referenced by Messenger.Views.Subcontrols.ReplyView.AngryButton_Tapped(), Messenger.Views.Subcontrols.ReplyView.DislikeButton_Tapped(), Messenger.Views.Subcontrols.ReplyView.LikeButton_Tapped(), and Messenger.Views.Subcontrols.ReplyView.SurprisedButton_Tapped().
ToggleReactionCommand
ICommand Messenger.Views.Subcontrols.ReplyView.ToggleReactionCommand get
Definition at line 23 of file ReplyView.xaml.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Views/Subcontrols/ReplyView.xaml.cs