VPR_Messenger: Messenger.ViewModels.Pages.TeamNavViewModel Class Reference
Messenger.ViewModels.Pages.TeamNavViewModel Class Reference
Public Member Functions
TeamNavViewModel ()
void OnTeamsLoaded (object sender, BroadcastArgs e)
Fired by EventProvider on TeamsLoaded
void OnTeamUpdated (object sender, BroadcastArgs e)
Fired by EventProvider on TeamUpdated
void OnChannelUpdated (object sender, BroadcastArgs e)
Fired by EventProvider on ChannelUpdated
void OnMessageUpdated (object sender, BroadcastArgs e)
Fired by EventProvider on MessageUpdated(for LastMessage of Channel)
Protected Member Functions
void Set< T > (ref T storage, T value, [CallerMemberName]string propertyName=null)
void OnPropertyChanged (string propertyName)
Properties
UserDataService UserDataService [get]
ObservableCollection< TeamViewModel > Teams [get, set]
bool IsBusy [get, set]
UserViewModel CurrentUser [get, set]
ICommand TeamChannelSwitchCommand [get]
Switches channel within a team
ICommand CreateTeamCommand [get]
Opens CreateTeamDialog to start a new team
ICommand RemoveChannelCommand [get]
ICommand RemoveTeamCommand [get]
ICommand ReloadCommand [get]
Manually reloads all teams and messages
Events
PropertyChangedEventHandler PropertyChanged
Private Member Functions
async void Initialize ()
void LoadFromCache ()
async void Reload ()
Private Attributes
ObservableCollection< TeamViewModel > _teams
bool _isBusy
Detailed Description
Definition at line 18 of file TeamNavViewModel.cs.
Constructor & Destructor Documentation
TeamNavViewModel()
Messenger.ViewModels.Pages.TeamNavViewModel.TeamNavViewModel () inline
Definition at line 83 of file TeamNavViewModel.cs.
References Messenger.ViewModels.Pages.TeamNavViewModel.Initialize(), Messenger.ViewModels.Pages.TeamNavViewModel.OnChannelUpdated(), Messenger.ViewModels.Pages.TeamNavViewModel.OnMessageUpdated(), Messenger.ViewModels.Pages.TeamNavViewModel.OnTeamsLoaded(), and Messenger.ViewModels.Pages.TeamNavViewModel.OnTeamUpdated().
Member Function Documentation
Initialize()
async void Messenger.ViewModels.Pages.TeamNavViewModel.Initialize () inline private
GET DATA FROM CACHE IF ALREADY INITIALIZED
Definition at line 93 of file TeamNavViewModel.cs.
References Messenger.ViewModels.Pages.TeamNavViewModel.CurrentUser, Messenger.Services.UserDataService.GetUserAsync(), Messenger.ViewModels.Pages.TeamNavViewModel.IsBusy, Messenger.ViewModels.Pages.TeamNavViewModel.LoadFromCache(), and Messenger.ViewModels.Pages.TeamNavViewModel.Teams.
Referenced by Messenger.ViewModels.Pages.TeamNavViewModel.TeamNavViewModel().
LoadFromCache()
void Messenger.ViewModels.Pages.TeamNavViewModel.LoadFromCache () inline private
Definition at line 109 of file TeamNavViewModel.cs.
References Messenger.Helpers.CacheQuery.GetMyTeams(), and Messenger.ViewModels.Pages.TeamNavViewModel.Teams.
Referenced by Messenger.ViewModels.Pages.TeamNavViewModel.Initialize().
OnChannelUpdated()
void Messenger.ViewModels.Pages.TeamNavViewModel.OnChannelUpdated (object sender, BroadcastArgs e) inline
Fired by EventProvider on ChannelUpdated
Definition at line 188 of file TeamNavViewModel.cs.
References Messenger.ViewModels.Pages.TeamNavViewModel._teams, Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, Messenger.ViewModels.DataViewModels.TeamViewModel.Channels, Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Models.BroadcastArgs.Payload, Messenger.Models.BroadcastArgs.Reason, and Messenger.ViewModels.DataViewModels.ChannelViewModel.TeamId.
Referenced by Messenger.ViewModels.Pages.TeamNavViewModel.TeamNavViewModel().
OnMessageUpdated()
void Messenger.ViewModels.Pages.TeamNavViewModel.OnMessageUpdated (object sender, BroadcastArgs e) inline
Fired by EventProvider on MessageUpdated(for LastMessage of Channel)
Definition at line 238 of file TeamNavViewModel.cs.
References Messenger.ViewModels.DataViewModels.TeamViewModel.Channels, Messenger.ViewModels.DataViewModels.ChannelViewModel.LastMessage, Messenger.Models.BroadcastArgs.Payload, Messenger.Models.BroadcastArgs.Reason, and Messenger.ViewModels.Pages.TeamNavViewModel.Teams.
Referenced by Messenger.ViewModels.Pages.TeamNavViewModel.TeamNavViewModel().
OnPropertyChanged()
void Messenger.Helpers.Observable.OnPropertyChanged (string propertyName) protected inherited
Referenced by Messenger.Helpers.Observable.Set< T >().
OnTeamsLoaded()
void Messenger.ViewModels.Pages.TeamNavViewModel.OnTeamsLoaded (object sender, BroadcastArgs e) inline
Fired by EventProvider on TeamsLoaded
Definition at line 134 of file TeamNavViewModel.cs.
References Messenger.ViewModels.Pages.TeamNavViewModel.IsBusy, Messenger.Models.BroadcastArgs.Payload, and Messenger.ViewModels.Pages.TeamNavViewModel.Teams.
Referenced by Messenger.ViewModels.Pages.TeamNavViewModel.TeamNavViewModel().
OnTeamUpdated()
void Messenger.ViewModels.Pages.TeamNavViewModel.OnTeamUpdated (object sender, BroadcastArgs e) inline
Fired by EventProvider on TeamUpdated
Definition at line 154 of file TeamNavViewModel.cs.
References Messenger.ViewModels.Pages.TeamNavViewModel._teams, Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Models.BroadcastArgs.Payload, and Messenger.Models.BroadcastArgs.Reason.
Referenced by Messenger.ViewModels.Pages.TeamNavViewModel.TeamNavViewModel().
Reload()
async void Messenger.ViewModels.Pages.TeamNavViewModel.Reload () inline private
Definition at line 119 of file TeamNavViewModel.cs.
References Messenger.ViewModels.Pages.TeamNavViewModel.IsBusy, Messenger.Helpers.CacheQuery.Reload(), and Messenger.ViewModels.Pages.TeamNavViewModel.Teams.
Set< T >()
void Messenger.Helpers.Observable.Set< T > (ref T storage, T value, [CallerMemberName] string propertyName = null) inline protected inherited
Definition at line 11 of file Observable.cs.
References Messenger.Helpers.Observable.OnPropertyChanged().
Member Data Documentation
_isBusy
bool Messenger.ViewModels.Pages.TeamNavViewModel._isBusy private
Definition at line 26 of file TeamNavViewModel.cs.
_teams
ObservableCollection<TeamViewModel> Messenger.ViewModels.Pages.TeamNavViewModel._teams private
Definition at line 24 of file TeamNavViewModel.cs.
Referenced by Messenger.ViewModels.Pages.TeamNavViewModel.OnChannelUpdated(), and Messenger.ViewModels.Pages.TeamNavViewModel.OnTeamUpdated().
Property Documentation
CreateTeamCommand
ICommand Messenger.ViewModels.Pages.TeamNavViewModel.CreateTeamCommand get
Opens CreateTeamDialog to start a new team
Definition at line 70 of file TeamNavViewModel.cs.
CurrentUser
UserViewModel Messenger.ViewModels.Pages.TeamNavViewModel.CurrentUser get set
Definition at line 56 of file TeamNavViewModel.cs.
Referenced by Messenger.ViewModels.Pages.TeamNavViewModel.Initialize().
IsBusy
bool Messenger.ViewModels.Pages.TeamNavViewModel.IsBusy get set
Definition at line 44 of file TeamNavViewModel.cs.
Referenced by Messenger.ViewModels.Pages.TeamNavViewModel.Initialize(), Messenger.ViewModels.Pages.TeamNavViewModel.OnTeamsLoaded(), and Messenger.ViewModels.Pages.TeamNavViewModel.Reload().
ReloadCommand
ICommand Messenger.ViewModels.Pages.TeamNavViewModel.ReloadCommand get
Manually reloads all teams and messages
Definition at line 79 of file TeamNavViewModel.cs.
RemoveChannelCommand
ICommand Messenger.ViewModels.Pages.TeamNavViewModel.RemoveChannelCommand get
Definition at line 72 of file TeamNavViewModel.cs.
RemoveTeamCommand
ICommand Messenger.ViewModels.Pages.TeamNavViewModel.RemoveTeamCommand get
Definition at line 74 of file TeamNavViewModel.cs.
TeamChannelSwitchCommand
ICommand Messenger.ViewModels.Pages.TeamNavViewModel.TeamChannelSwitchCommand get
Switches channel within a team
Definition at line 65 of file TeamNavViewModel.cs.
Referenced by Messenger.Views.Pages.TeamNavPage.treeView_ItemInvoked().
Teams
ObservableCollection<TeamViewModel> Messenger.ViewModels.Pages.TeamNavViewModel.Teams get set
Definition at line 32 of file TeamNavViewModel.cs.
Referenced by Messenger.ViewModels.Pages.TeamNavViewModel.Initialize(), Messenger.ViewModels.Pages.TeamNavViewModel.LoadFromCache(), Messenger.ViewModels.Pages.TeamNavViewModel.OnMessageUpdated(), Messenger.ViewModels.Pages.TeamNavViewModel.OnTeamsLoaded(), and Messenger.ViewModels.Pages.TeamNavViewModel.Reload().
UserDataService
UserDataService Messenger.ViewModels.Pages.TeamNavViewModel.UserDataService get private
Definition at line 22 of file TeamNavViewModel.cs.
Event Documentation
PropertyChanged
PropertyChangedEventHandler Messenger.Helpers.Observable.PropertyChanged inherited
Definition at line 9 of file Observable.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/ViewModels/Pages/TeamNavViewModel.cs