VPR_Messenger: Messenger.Helpers.MessageHelpers.MessageBuilder Class Reference
Messenger.Helpers.MessageHelpers.MessageBuilder Class Reference
Converts and completes MessageViewModels to be shown on UI
Static Public Member Functions
static async Task< IEnumerable< Message > > GetMessagesFromDatabase (ChannelViewModel channel)
loads all messages in channel from the db
static async Task< MessageViewModel > Build (this Message message)
Converts the given Message data model to MessageViewModel
static async Task< IEnumerable< MessageViewModel > > Build (this IEnumerable< Message > messages)
Converts the given Message data models to MessageViewModels
static async Task< MessageViewModel > WithReactions (this MessageViewModel viewModel)
Loads reactions for the given view model
static async Task< MessageViewModel > WithReplies (this MessageViewModel viewModel)
Loads replies for the given view model
static async Task< MessageViewModel > WithSender (this MessageViewModel viewModel)
loads the sender to the ViewModel
static async Task< MessageViewModel > WithAttachments (this MessageViewModel viewModel)
loads the attachments to the viewmodel
static IList< MessageViewModel > SortReplies (this IEnumerable< MessageViewModel > viewModels)
Sorts parent-messages/replies and assigns replies to matching parents this should be called only after converting all loaded messages to view models
static MessageViewModel Map (Message message)
Maps the properties from the data model
static UserViewModel Map (User user)
converts the user to an UserViewModel
static List< Attachment > Parse (this IEnumerable< string > blobName)
Parses the attachments blob name of a message and maps to Attachment models
static string ToBlobName (this Attachment attachment)
converts the attachment to the download name
static IEnumerable< string > ToBlobNames (this List< Attachment > attachments)
converts a list of attachments to donwloadnames
Detailed Description
Converts and completes MessageViewModels to be shown on UI
Definition at line 18 of file MessageBuilder.cs.
Member Function Documentation
Build() [1/2]
static async Task<IEnumerable<MessageViewModel> > Messenger.Helpers.MessageHelpers.MessageBuilder.Build (this IEnumerable< Message > messages) inline static
Converts the given Message data models to MessageViewModels
Parameters
messages Message data models to be converted
Returns
List of complete MessageViewModel objects
Definition at line 50 of file MessageBuilder.cs.
References Messenger.Helpers.MessageHelpers.MessageBuilder.Build().
Build() [2/2]
static async Task<MessageViewModel> Messenger.Helpers.MessageHelpers.MessageBuilder.Build (this Message message) inline static
Converts the given Message data model to MessageViewModel
Parameters
message Message data model to be converted
Returns
A complete MessageViewModel object
Definition at line 36 of file MessageBuilder.cs.
References Messenger.Helpers.MessageHelpers.MessageBuilder.Map(), and Messenger.ViewModels.DataViewModels.MessageViewModel.Sender.
Referenced by Messenger.Helpers.MessageHelpers.MessageManager.AddOrUpdateMessage(), and Messenger.Helpers.MessageHelpers.MessageBuilder.Build().
GetMessagesFromDatabase()
static async Task<IEnumerable<Message> > Messenger.Helpers.MessageHelpers.MessageBuilder.GetMessagesFromDatabase (ChannelViewModel channel) inline static
loads all messages in channel from the db
Parameters
channel
Returns
Task<IEnumerable<Message>> all messages from channel
Definition at line 26 of file MessageBuilder.cs.
References Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, and Messenger.Core.Services.MessengerService.GetMessages().
Referenced by Messenger.Helpers.MessageHelpers.MessageManager.CreateEntry().
Map() [1/2]
static MessageViewModel Messenger.Helpers.MessageHelpers.MessageBuilder.Map (Message message) inline static
Maps the properties from the data model
Parameters
message Message data model to map from
Returns
Mapped MessageViewModel object
Definition at line 223 of file MessageBuilder.cs.
References Messenger.Core.Models.Message.AttachmentsBlobName, Messenger.Core.Models.Message.Content, Messenger.Core.Models.Message.CreationTime, Messenger.Core.Models.Message.Id, Messenger.Core.Models.Message.ParentMessageId, Messenger.Core.Models.Message.RecipientId, and Messenger.Core.Models.Message.SenderId.
Referenced by Messenger.Helpers.MessageHelpers.MessageBuilder.Build(), Messenger.Helpers.MessageHelpers.MessageBuilder.WithReplies(), and Messenger.Helpers.MessageHelpers.MessageBuilder.WithSender().
Map() [2/2]
static UserViewModel Messenger.Helpers.MessageHelpers.MessageBuilder.Map (User user) inline static
converts the user to an UserViewModel
Parameters
user
Returns
Definition at line 248 of file MessageBuilder.cs.
References Messenger.Core.Models.User.Bio, Messenger.Core.Models.User.DisplayName, Messenger.Core.Models.User.Id, Messenger.Core.Models.User.Mail, and Messenger.Core.Models.User.NameId.
Parse()
static List<Attachment> Messenger.Helpers.MessageHelpers.MessageBuilder.Parse (this IEnumerable< string > blobName) inline static
Parses the attachments blob name of a message and maps to Attachment models
Parameters
blobName Blob name to parse
Returns
List of Attachment objects
Definition at line 272 of file MessageBuilder.cs.
SortReplies()
static IList<MessageViewModel> Messenger.Helpers.MessageHelpers.MessageBuilder.SortReplies (this IEnumerable< MessageViewModel > viewModels) inline static
Sorts parent-messages/replies and assigns replies to matching parents this should be called only after converting all loaded messages to view models
Parameters
viewModels List of MessageViewModel to sort
Returns
List of parent messages with assigned replies
Definition at line 186 of file MessageBuilder.cs.
References Messenger.ViewModels.DataViewModels.MessageViewModel.IsReply, Messenger.ViewModels.DataViewModels.MessageViewModel.ParentMessageId, and Messenger.ViewModels.DataViewModels.MessageViewModel.Replies.
ToBlobName()
static string Messenger.Helpers.MessageHelpers.MessageBuilder.ToBlobName (this Attachment attachment) inline static
converts the attachment to the download name
Parameters
attachment
Returns
Definition at line 307 of file MessageBuilder.cs.
References Messenger.Models.Attachment.FileName, Messenger.Models.Attachment.FileType, and Messenger.Models.Attachment.UploaderId.
ToBlobNames()
static IEnumerable<string> Messenger.Helpers.MessageHelpers.MessageBuilder.ToBlobNames (this List< Attachment > attachments) inline static
converts a list of attachments to donwloadnames
Parameters
attachments
Returns
Definition at line 324 of file MessageBuilder.cs.
References Messenger.Models.Attachment.FileName, Messenger.Models.Attachment.FileType, and Messenger.Models.Attachment.UploaderId.
WithAttachments()
static async Task<MessageViewModel> Messenger.Helpers.MessageHelpers.MessageBuilder.WithAttachments (this MessageViewModel viewModel) inline static
loads the attachments to the viewmodel
Parameters
viewModel
Returns
Task<MessageViewModel> with attachments
Definition at line 153 of file MessageBuilder.cs.
References Messenger.ViewModels.DataViewModels.MessageViewModel.AddImages(), Messenger.ViewModels.DataViewModels.MessageViewModel.Attachments, Messenger.Core.Services.FileSharingService.Download(), Messenger.Core.Services.MessageService.GetBlobFileNamesOfAttachments(), and Messenger.ViewModels.DataViewModels.MessageViewModel.Id.
WithReactions()
static async Task<MessageViewModel> Messenger.Helpers.MessageHelpers.MessageBuilder.WithReactions (this MessageViewModel viewModel) inline static
Loads reactions for the given view model
Parameters
viewModel MessageViewModel to load reactions for
Returns
MessageViewModel with the list of reactions
Definition at line 67 of file MessageBuilder.cs.
References Messenger.Core.Services.MessengerService.GetReactions(), Messenger.ViewModels.DataViewModels.MessageViewModel.HasReacted, Messenger.ViewModels.DataViewModels.MessageViewModel.Id, Messenger.ViewModels.DataViewModels.MessageViewModel.MyReaction, Messenger.ViewModels.DataViewModels.MessageViewModel.Reactions, and Messenger.Core.Models.Reaction.Symbol.
WithReplies()
static async Task<MessageViewModel> Messenger.Helpers.MessageHelpers.MessageBuilder.WithReplies (this MessageViewModel viewModel) inline static
Loads replies for the given view model
Parameters
viewModel MessageViewModel to load replies for
Returns
MessageViewModel with the list of replies
Definition at line 102 of file MessageBuilder.cs.
References Messenger.ViewModels.DataViewModels.MessageViewModel.Id, Messenger.Helpers.MessageHelpers.MessageBuilder.Map(), Messenger.ViewModels.DataViewModels.MessageViewModel.Replies, Messenger.Core.Services.MessageService.RetrieveReplies(), and Messenger.Helpers.MessageHelpers.MessageBuilder.WithSender().
WithSender()
static async Task<MessageViewModel> Messenger.Helpers.MessageHelpers.MessageBuilder.WithSender (this MessageViewModel viewModel) inline static
loads the sender to the ViewModel
Parameters
viewModel
Returns
Task<MessageViewModel> with senders
Definition at line 133 of file MessageBuilder.cs.
References Messenger.ViewModels.DataViewModels.MessageViewModel.ChannelId, Messenger.Core.Services.ChannelService.GetChannel(), Messenger.Core.Services.UserService.GetUser(), Messenger.Helpers.MessageHelpers.MessageBuilder.Map(), Messenger.Helpers.TeamHelpers.TeamBuilder.Map(), Messenger.ViewModels.DataViewModels.MessageViewModel.Sender, Messenger.ViewModels.DataViewModels.MessageViewModel.SenderId, and Messenger.ViewModels.DataViewModels.ChannelViewModel.TeamId.
Referenced by Messenger.Helpers.MessageHelpers.MessageBuilder.WithReplies().
The documentation for this class was generated from the following file:
Messenger/Messenger/Helpers/MessageHelpers/MessageBuilder.cs