VPR_Messenger: Messenger.SignalR.Models.ConnectionMapping Class Reference
Messenger.SignalR.Models.ConnectionMapping Class Reference
Thread-safe dictionary mapping class for connection ids
Public Member Functions
void Add (string userId, string connectionId)
Adds a new connection id under the user id
IEnumerable< string > GetConnections (string userId)
Gets all connection ids registered under the user id
void Remove (string userId, string connectionId)
Safely removes the connection id from the registered list under the user id
Public Attributes
ILogger logger = GlobalLogger.Instance
Properties
int Count [get]
Private Attributes
readonly Dictionary< string, HashSet< string > > _connections = new Dictionary<string, HashSet<string>>()
Detailed Description
Thread-safe dictionary mapping class for connection ids
Definition at line 12 of file ConnectionMapping.cs.
Member Function Documentation
Add()
void Messenger.SignalR.Models.ConnectionMapping.Add (string userId, string connectionId) inline
Adds a new connection id under the user id
Parameters
userId Id of the user logged in
connectionId Current connection id of the application
Definition at line 31 of file ConnectionMapping.cs.
References Messenger.SignalR.Models.ConnectionMapping._connections, and Messenger.SignalR.Models.ConnectionMapping.logger.
Referenced by Messenger.SignalR.ChatHub.Register().
GetConnections()
IEnumerable<string> Messenger.SignalR.Models.ConnectionMapping.GetConnections (string userId) inline
Gets all connection ids registered under the user id
Parameters
userId Id of the user logged in
Returns
List of connection ids, empty enumerable if none exists
Definition at line 63 of file ConnectionMapping.cs.
References Messenger.SignalR.Models.ConnectionMapping._connections, and Messenger.SignalR.Models.ConnectionMapping.logger.
Referenced by Messenger.SignalR.ChatHub.JoinTeam(), Messenger.SignalR.ChatHub.LeaveTeam(), Messenger.SignalR.ChatHub.RemoveMember(), Messenger.SignalR.ChatHub.SendInvitation(), Messenger.SignalR.ChatHub.SendNotificationToUser(), and Messenger.SignalR.ChatHub.UpdateUser().
Remove()
void Messenger.SignalR.Models.ConnectionMapping.Remove (string userId, string connectionId) inline
Safely removes the connection id from the registered list under the user id
Parameters
userId Id of the user logged in
connectionId Connection id to remove from the list
Definition at line 86 of file ConnectionMapping.cs.
References Messenger.SignalR.Models.ConnectionMapping._connections, and Messenger.SignalR.Models.ConnectionMapping.logger.
Member Data Documentation
_connections
readonly Dictionary<string, HashSet<string> > Messenger.SignalR.Models.ConnectionMapping._connections = new Dictionary<string, HashSet<string>>() private
Definition at line 14 of file ConnectionMapping.cs.
Referenced by Messenger.SignalR.Models.ConnectionMapping.Add(), Messenger.SignalR.Models.ConnectionMapping.GetConnections(), and Messenger.SignalR.Models.ConnectionMapping.Remove().
logger
ILogger Messenger.SignalR.Models.ConnectionMapping.logger = GlobalLogger.Instance
Definition at line 24 of file ConnectionMapping.cs.
Referenced by Messenger.SignalR.Models.ConnectionMapping.Add(), Messenger.SignalR.Models.ConnectionMapping.GetConnections(), and Messenger.SignalR.Models.ConnectionMapping.Remove().
Property Documentation
Count
int Messenger.SignalR.Models.ConnectionMapping.Count get
Definition at line 16 of file ConnectionMapping.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger.SignalR/Models/ConnectionMapping.cs