VPR_Messenger: Messenger.Commands.PrivateChat.StartChatCommand Class Reference
Messenger.Commands.PrivateChat.StartChatCommand Class Reference
Public Member Functions
StartChatCommand ()
bool CanExecute (object parameter)
async void Execute (object parameter)
Opens the dialog to start a new private chat
Properties
ILogger _logger [get]
Events
EventHandler CanExecuteChanged
Private Member Functions
void SwitchToChatPage (PrivateChatViewModel chat)
Detailed Description
Definition at line 15 of file StartChatCommand.cs.
Constructor & Destructor Documentation
StartChatCommand()
Messenger.Commands.PrivateChat.StartChatCommand.StartChatCommand () inline
Definition at line 21 of file StartChatCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.PrivateChat.StartChatCommand.CanExecute (object parameter) inline
Definition at line 25 of file StartChatCommand.cs.
Execute()
async void Messenger.Commands.PrivateChat.StartChatCommand.Execute (object parameter) inline
Opens the dialog to start a new private chat
Definition at line 33 of file StartChatCommand.cs.
References Messenger.Commands.PrivateChat.StartChatCommand._logger, Messenger.Helpers.CacheQuery.GetMyChats(), Messenger.ViewModels.DataViewModels.UserViewModel.Id, Messenger.ViewModels.DataViewModels.PrivateChatViewModel.Partner, Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set(), Messenger.Core.Services.MessengerService.StartChat(), Messenger.Commands.PrivateChat.StartChatCommand.SwitchToChatPage(), and Messenger.Views.DialogBoxes.CreateChatDialog.ViewModel.
SwitchToChatPage()
void Messenger.Commands.PrivateChat.StartChatCommand.SwitchToChatPage (PrivateChatViewModel chat) inline private
Definition at line 79 of file StartChatCommand.cs.
References Messenger.ViewModels.DataViewModels.PrivateChatViewModel.MainChannel, and Messenger.Services.NavigationService.Navigate().
Referenced by Messenger.Commands.PrivateChat.StartChatCommand.Execute().
Property Documentation
_logger
ILogger Messenger.Commands.PrivateChat.StartChatCommand._logger get private
Definition at line 17 of file StartChatCommand.cs.
Referenced by Messenger.Commands.PrivateChat.StartChatCommand.Execute().
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.PrivateChat.StartChatCommand.CanExecuteChanged
Definition at line 19 of file StartChatCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/PrivateChat/StartChatCommand.cs