VPR_Messenger: Messenger.TemplateSelectors.TeamDataTemplateSelector Class Reference
Messenger.TemplateSelectors.TeamDataTemplateSelector Class Reference
Protected Member Functions
override DataTemplate SelectTemplateCore (object item)
override DataTemplate SelectTemplateCore (object item, DependencyObject container)
Properties
DataTemplate TeamTemplate [get, set]
DataTemplate TeamChannelTemplate [get, set]
Private Member Functions
DataTemplate GetTemplate (object item)
Detailed Description
Definition at line 8 of file TeamDataTemplateSelector.cs.
Member Function Documentation
GetTemplate()
DataTemplate Messenger.TemplateSelectors.TeamDataTemplateSelector.GetTemplate (object item) inline private
Definition at line 24 of file TeamDataTemplateSelector.cs.
References Messenger.TemplateSelectors.TeamDataTemplateSelector.TeamChannelTemplate, and Messenger.TemplateSelectors.TeamDataTemplateSelector.TeamTemplate.
Referenced by Messenger.TemplateSelectors.TeamDataTemplateSelector.SelectTemplateCore().
SelectTemplateCore() [1/2]
override DataTemplate Messenger.TemplateSelectors.TeamDataTemplateSelector.SelectTemplateCore (object item) inline protected
Definition at line 14 of file TeamDataTemplateSelector.cs.
References Messenger.TemplateSelectors.TeamDataTemplateSelector.GetTemplate().
SelectTemplateCore() [2/2]
override DataTemplate Messenger.TemplateSelectors.TeamDataTemplateSelector.SelectTemplateCore (object item, DependencyObject container) inline protected
Definition at line 19 of file TeamDataTemplateSelector.cs.
References Messenger.TemplateSelectors.TeamDataTemplateSelector.GetTemplate().
Property Documentation
TeamChannelTemplate
DataTemplate Messenger.TemplateSelectors.TeamDataTemplateSelector.TeamChannelTemplate get set
Definition at line 12 of file TeamDataTemplateSelector.cs.
Referenced by Messenger.TemplateSelectors.TeamDataTemplateSelector.GetTemplate().
TeamTemplate
DataTemplate Messenger.TemplateSelectors.TeamDataTemplateSelector.TeamTemplate get set
Definition at line 10 of file TeamDataTemplateSelector.cs.
Referenced by Messenger.TemplateSelectors.TeamDataTemplateSelector.GetTemplate().
The documentation for this class was generated from the following file:
Messenger/Messenger/TemplateSelectors/TeamDataTemplateSelector.cs