VPR_Messenger: Messenger.Services.Providers.StateProviderExtension Class Reference
Messenger.Services.Providers.StateProviderExtension Class Reference
Extension methods for StateProvider
Static Public Member Functions
static async Task< StateProvider > Initialize (this StateProvider provider, UserViewModel user)
Initializes the provider with teams/chats and messages, loaded from database
static async Task LoadAllMessages (this StateProvider provider)
Loads all messages from the database
static async Task LoadAllNotifications (this StateProvider provider)
Detailed Description
Extension methods for StateProvider
Definition at line 88 of file StateProvider.cs.
Member Function Documentation
Initialize()
static async Task<StateProvider> Messenger.Services.Providers.StateProviderExtension.Initialize (this StateProvider provider, UserViewModel user) inline static
Initializes the provider with teams/chats and messages, loaded from database
Parameters
provider Provider instance(Extension)
user Currently logged-in user
Returns
Initialized provider instance
LOAD TEAMS/PRIVATE CHATS FROM DATABASE
Definition at line 96 of file StateProvider.cs.
References Messenger.Services.Providers.StateProvider.CurrentUser, Messenger.Helpers.TeamHelpers.TeamManager.Initialize(), Messenger.Core.Helpers.Singleton< T >.Instance, and Messenger.Services.Providers.StateProvider.TeamManager.
LoadAllMessages()
static async Task Messenger.Services.Providers.StateProviderExtension.LoadAllMessages (this StateProvider provider) inline static
Loads all messages from the database
Parameters
provider Provider instance(Extension)
Returns
Task to be awaited
LOAD MESSAGES FOR TEAMS
LOAD MESSAGES FOR PRIVATE CHATS
Definition at line 131 of file StateProvider.cs.
References Messenger.Helpers.MessageHelpers.MessageManager.CreateEntry(), Messenger.Services.Providers.StateProvider.MessageManager, Messenger.Helpers.TeamHelpers.TeamManager.MyChats, Messenger.Helpers.TeamHelpers.TeamManager.MyTeams, and Messenger.Services.Providers.StateProvider.TeamManager.
LoadAllNotifications()
static async Task Messenger.Services.Providers.StateProviderExtension.LoadAllNotifications (this StateProvider provider) inline static
Definition at line 146 of file StateProvider.cs.
References Messenger.Services.Providers.StateProvider.CurrentUser, Messenger.ViewModels.DataViewModels.UserViewModel.Id, Messenger.Services.Providers.StateProvider.Notifications, and Messenger.Core.Services.NotificationService.RetrieveNotifications().
The documentation for this class was generated from the following file:
Messenger/Messenger/Services/Providers/StateProvider.cs