VPR_Messenger: Messenger.Behaviors.NavigationViewHeaderBehavior Class Reference
Messenger.Behaviors.NavigationViewHeaderBehavior Class Reference
Static Public Member Functions
static NavigationViewHeaderMode GetHeaderMode (Page item)
static void SetHeaderMode (Page item, NavigationViewHeaderMode value)
static object GetHeaderContext (Page item)
static void SetHeaderContext (Page item, object value)
static DataTemplate GetHeaderTemplate (Page item)
static void SetHeaderTemplate (Page item, DataTemplate value)
Static Public Attributes
static readonly DependencyProperty DefaultHeaderProperty = DependencyProperty.Register("DefaultHeader", typeof(object), typeof(NavigationViewHeaderBehavior), new PropertyMetadata(null, (d, e) => _current.UpdateHeader()))
static readonly DependencyProperty HeaderModeProperty
static readonly DependencyProperty HeaderContextProperty
static readonly DependencyProperty HeaderTemplateProperty
Protected Member Functions
override void OnAttached ()
override void OnDetaching ()
Properties
DataTemplate DefaultHeaderTemplate [get, set]
object DefaultHeader [get, set]
Private Member Functions
void OnNavigated (object sender, NavigationEventArgs e)
void UpdateHeader ()
void UpdateHeaderTemplate ()
Private Attributes
Page _currentPage
Static Private Attributes
static NavigationViewHeaderBehavior _current
Detailed Description
Definition at line 13 of file NavigationViewHeaderBehavior.cs.
Member Function Documentation
GetHeaderContext()
static object Messenger.Behaviors.NavigationViewHeaderBehavior.GetHeaderContext (Page item) inline static
Definition at line 41 of file NavigationViewHeaderBehavior.cs.
References Messenger.Behaviors.NavigationViewHeaderBehavior.HeaderContextProperty.
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeader().
GetHeaderMode()
static NavigationViewHeaderMode Messenger.Behaviors.NavigationViewHeaderBehavior.GetHeaderMode (Page item) inline static
Definition at line 28 of file NavigationViewHeaderBehavior.cs.
References Messenger.Behaviors.NavigationViewHeaderBehavior.HeaderModeProperty.
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeader().
GetHeaderTemplate()
static DataTemplate Messenger.Behaviors.NavigationViewHeaderBehavior.GetHeaderTemplate (Page item) inline static
Definition at line 54 of file NavigationViewHeaderBehavior.cs.
References Messenger.Behaviors.NavigationViewHeaderBehavior.HeaderTemplateProperty.
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeaderTemplate().
OnAttached()
override void Messenger.Behaviors.NavigationViewHeaderBehavior.OnAttached () inline protected
Definition at line 67 of file NavigationViewHeaderBehavior.cs.
References Messenger.Behaviors.NavigationViewHeaderBehavior._current, Messenger.Services.NavigationService.Navigated, and Messenger.Behaviors.NavigationViewHeaderBehavior.OnNavigated().
OnDetaching()
override void Messenger.Behaviors.NavigationViewHeaderBehavior.OnDetaching () inline protected
Definition at line 74 of file NavigationViewHeaderBehavior.cs.
References Messenger.Services.NavigationService.Navigated, and Messenger.Behaviors.NavigationViewHeaderBehavior.OnNavigated().
OnNavigated()
void Messenger.Behaviors.NavigationViewHeaderBehavior.OnNavigated (object sender, NavigationEventArgs e) inline private
Definition at line 80 of file NavigationViewHeaderBehavior.cs.
References Messenger.Behaviors.NavigationViewHeaderBehavior._currentPage, Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeader(), and Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeaderTemplate().
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.OnAttached(), and Messenger.Behaviors.NavigationViewHeaderBehavior.OnDetaching().
SetHeaderContext()
static void Messenger.Behaviors.NavigationViewHeaderBehavior.SetHeaderContext (Page item, object value) inline static
Definition at line 46 of file NavigationViewHeaderBehavior.cs.
References Messenger.Behaviors.NavigationViewHeaderBehavior.HeaderContextProperty.
SetHeaderMode()
static void Messenger.Behaviors.NavigationViewHeaderBehavior.SetHeaderMode (Page item, NavigationViewHeaderMode value) inline static
Definition at line 33 of file NavigationViewHeaderBehavior.cs.
References Messenger.Behaviors.NavigationViewHeaderBehavior.HeaderModeProperty.
SetHeaderTemplate()
static void Messenger.Behaviors.NavigationViewHeaderBehavior.SetHeaderTemplate (Page item, DataTemplate value) inline static
Definition at line 59 of file NavigationViewHeaderBehavior.cs.
References Messenger.Behaviors.NavigationViewHeaderBehavior.HeaderTemplateProperty.
UpdateHeader()
void Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeader () inline private
Definition at line 92 of file NavigationViewHeaderBehavior.cs.
References Messenger.Behaviors.NavigationViewHeaderBehavior._currentPage, Messenger.Behaviors.NavigationViewHeaderBehavior.DefaultHeader, Messenger.Behaviors.NavigationViewHeaderBehavior.GetHeaderContext(), and Messenger.Behaviors.NavigationViewHeaderBehavior.GetHeaderMode().
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.OnNavigated().
UpdateHeaderTemplate()
void Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeaderTemplate () inline private
Definition at line 126 of file NavigationViewHeaderBehavior.cs.
References Messenger.Behaviors.NavigationViewHeaderBehavior._currentPage, Messenger.Behaviors.NavigationViewHeaderBehavior.DefaultHeaderTemplate, and Messenger.Behaviors.NavigationViewHeaderBehavior.GetHeaderTemplate().
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.OnNavigated().
Member Data Documentation
_current
NavigationViewHeaderBehavior Messenger.Behaviors.NavigationViewHeaderBehavior._current static private
Definition at line 15 of file NavigationViewHeaderBehavior.cs.
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.OnAttached().
_currentPage
Page Messenger.Behaviors.NavigationViewHeaderBehavior._currentPage private
Definition at line 16 of file NavigationViewHeaderBehavior.cs.
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.OnNavigated(), Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeader(), and Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeaderTemplate().
DefaultHeaderProperty
readonly DependencyProperty Messenger.Behaviors.NavigationViewHeaderBehavior.DefaultHeaderProperty = DependencyProperty.Register("DefaultHeader", typeof(object), typeof(NavigationViewHeaderBehavior), new PropertyMetadata(null, (d, e) => _current.UpdateHeader())) static
Definition at line 26 of file NavigationViewHeaderBehavior.cs.
HeaderContextProperty
readonly DependencyProperty Messenger.Behaviors.NavigationViewHeaderBehavior.HeaderContextProperty static
Initial value:
=
            DependencyProperty.RegisterAttached("HeaderContext", typeof(object), typeof(NavigationViewHeaderBehavior), new PropertyMetadata(null, (d, e) => _current.UpdateHeader()))
Definition at line 51 of file NavigationViewHeaderBehavior.cs.
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.GetHeaderContext(), and Messenger.Behaviors.NavigationViewHeaderBehavior.SetHeaderContext().
HeaderModeProperty
readonly DependencyProperty Messenger.Behaviors.NavigationViewHeaderBehavior.HeaderModeProperty static
Initial value:
=
            DependencyProperty.RegisterAttached("HeaderMode", typeof(bool), typeof(NavigationViewHeaderBehavior), new PropertyMetadata(NavigationViewHeaderMode.Always, (d, e) => _current.UpdateHeader()))
Definition at line 38 of file NavigationViewHeaderBehavior.cs.
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.GetHeaderMode(), and Messenger.Behaviors.NavigationViewHeaderBehavior.SetHeaderMode().
HeaderTemplateProperty
readonly DependencyProperty Messenger.Behaviors.NavigationViewHeaderBehavior.HeaderTemplateProperty static
Initial value:
=
            DependencyProperty.RegisterAttached("HeaderTemplate", typeof(DataTemplate), typeof(NavigationViewHeaderBehavior), new PropertyMetadata(null, (d, e) => _current.UpdateHeaderTemplate()))
Definition at line 64 of file NavigationViewHeaderBehavior.cs.
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.GetHeaderTemplate(), and Messenger.Behaviors.NavigationViewHeaderBehavior.SetHeaderTemplate().
Property Documentation
DefaultHeader
object Messenger.Behaviors.NavigationViewHeaderBehavior.DefaultHeader get set
Definition at line 20 of file NavigationViewHeaderBehavior.cs.
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeader().
DefaultHeaderTemplate
DataTemplate Messenger.Behaviors.NavigationViewHeaderBehavior.DefaultHeaderTemplate get set
Definition at line 18 of file NavigationViewHeaderBehavior.cs.
Referenced by Messenger.Behaviors.NavigationViewHeaderBehavior.UpdateHeaderTemplate().
The documentation for this class was generated from the following file:
Messenger/Messenger/Behaviors/NavigationViewHeaderBehavior.cs