VPR_Messenger: Messenger.Commands.Messenger.DownloadAttachmentCommand Class Reference
Messenger.Commands.Messenger.DownloadAttachmentCommand Class Reference
Public Member Functions
DownloadAttachmentCommand (MessageViewModel viewModel)
bool CanExecute (object parameter)
async void Execute (object parameter)
Opens the file open picker and sets the model for AttachmentsBlobName, if any selected
async void SaveToStorage (MemoryStream stream, string filename, StorageFolder folder)
Safes an attachment to the local storage
Events
EventHandler CanExecuteChanged
Detailed Description
Definition at line 16 of file DownloadAttachmentCommand.cs.
Constructor & Destructor Documentation
DownloadAttachmentCommand()
Messenger.Commands.Messenger.DownloadAttachmentCommand.DownloadAttachmentCommand (MessageViewModel viewModel) inline
Definition at line 23 of file DownloadAttachmentCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.Messenger.DownloadAttachmentCommand.CanExecute (object parameter) inline
Definition at line 28 of file DownloadAttachmentCommand.cs.
Execute()
async void Messenger.Commands.Messenger.DownloadAttachmentCommand.Execute (object parameter) inline
Opens the file open picker and sets the model for AttachmentsBlobName, if any selected
Definition at line 36 of file DownloadAttachmentCommand.cs.
References Messenger.Core.Services.FileSharingService.Download(), Messenger.Models.Attachment.FileName, Messenger.Models.Attachment.FileType, Messenger.Commands.Messenger.DownloadAttachmentCommand.SaveToStorage(), Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set(), and Messenger.Models.Attachment.ToBlobName().
SaveToStorage()
async void Messenger.Commands.Messenger.DownloadAttachmentCommand.SaveToStorage (MemoryStream stream, string filename, StorageFolder folder) inline
Safes an attachment to the local storage
Parameters
stream
filename
folder
<return></return>
Definition at line 86 of file DownloadAttachmentCommand.cs.
Referenced by Messenger.Commands.Messenger.DownloadAttachmentCommand.Execute().
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.Messenger.DownloadAttachmentCommand.CanExecuteChanged
Definition at line 21 of file DownloadAttachmentCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/Messenger/DownloadAttachmentCommand.cs