VPR_Messenger: Messenger.ViewModels.MainViewModel Class Reference
Messenger.ViewModels.MainViewModel Class Reference
Public Member Functions
MainViewModel ()
Protected Member Functions
void Set< T > (ref T storage, T value, [CallerMemberName]string propertyName=null)
void OnPropertyChanged (string propertyName)
Properties
ChatHubViewModel Hub [get, set]
SignalR hub with an established connection, preconfigured with the current user data
Events
PropertyChangedEventHandler PropertyChanged
Private Member Functions
void InitializeHub ()
Private Attributes
ChatHubViewModel _hub
Detailed Description
Definition at line 13 of file MainViewModel.cs.
Constructor & Destructor Documentation
MainViewModel()
Messenger.ViewModels.MainViewModel.MainViewModel () inline
Definition at line 34 of file MainViewModel.cs.
References Messenger.ViewModels.MainViewModel.InitializeHub().
Member Function Documentation
InitializeHub()
void Messenger.ViewModels.MainViewModel.InitializeHub () inline private
Definition at line 39 of file MainViewModel.cs.
References Messenger.ViewModels.MainViewModel.Hub.
Referenced by Messenger.ViewModels.MainViewModel.MainViewModel().
OnPropertyChanged()
void Messenger.Helpers.Observable.OnPropertyChanged (string propertyName) protected inherited
Referenced by Messenger.Helpers.Observable.Set< T >().
Set< T >()
void Messenger.Helpers.Observable.Set< T > (ref T storage, T value, [CallerMemberName] string propertyName = null) inline protected inherited
Definition at line 11 of file Observable.cs.
References Messenger.Helpers.Observable.OnPropertyChanged().
Member Data Documentation
_hub
ChatHubViewModel Messenger.ViewModels.MainViewModel._hub private
Definition at line 17 of file MainViewModel.cs.
Property Documentation
Hub
ChatHubViewModel Messenger.ViewModels.MainViewModel.Hub get set
SignalR hub with an established connection, preconfigured with the current user data
Definition at line 24 of file MainViewModel.cs.
Referenced by Messenger.ViewModels.MainViewModel.InitializeHub().
Event Documentation
PropertyChanged
PropertyChangedEventHandler Messenger.Helpers.Observable.PropertyChanged inherited
Definition at line 9 of file Observable.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/ViewModels/MainViewModel.cs