VPR_Messenger: Messenger.Services.ThemeSelectorService Class Reference
Messenger.Services.ThemeSelectorService Class Reference
Static Public Member Functions
static async Task InitializeAsync ()
static async Task SetThemeAsync (ElementTheme theme)
static async Task SetRequestedThemeAsync ()
Properties
static ElementTheme Theme = ElementTheme.Default [get, set]
Static Private Member Functions
static async Task< ElementTheme > LoadThemeFromSettingsAsync ()
static async Task SaveThemeInSettingsAsync (ElementTheme theme)
Static Private Attributes
const string SettingsKey = "AppBackgroundRequestedTheme"
Detailed Description
Definition at line 13 of file ThemeSelectorService.cs.
Member Function Documentation
InitializeAsync()
static async Task Messenger.Services.ThemeSelectorService.InitializeAsync () inline static
Definition at line 19 of file ThemeSelectorService.cs.
References Messenger.Services.ThemeSelectorService.LoadThemeFromSettingsAsync(), and Messenger.Services.ThemeSelectorService.Theme.
LoadThemeFromSettingsAsync()
static async Task<ElementTheme> Messenger.Services.ThemeSelectorService.LoadThemeFromSettingsAsync () inline static private
Definition at line 46 of file ThemeSelectorService.cs.
Referenced by Messenger.Services.ThemeSelectorService.InitializeAsync().
SaveThemeInSettingsAsync()
static async Task Messenger.Services.ThemeSelectorService.SaveThemeInSettingsAsync (ElementTheme theme) inline static private
Definition at line 59 of file ThemeSelectorService.cs.
Referenced by Messenger.Services.ThemeSelectorService.SetThemeAsync().
SetRequestedThemeAsync()
static async Task Messenger.Services.ThemeSelectorService.SetRequestedThemeAsync () inline static
Definition at line 32 of file ThemeSelectorService.cs.
Referenced by Messenger.Services.ThemeSelectorService.SetThemeAsync().
SetThemeAsync()
static async Task Messenger.Services.ThemeSelectorService.SetThemeAsync (ElementTheme theme) inline static
Definition at line 24 of file ThemeSelectorService.cs.
References Messenger.Services.ThemeSelectorService.SaveThemeInSettingsAsync(), Messenger.Services.ThemeSelectorService.SetRequestedThemeAsync(), and Messenger.Services.ThemeSelectorService.Theme.
Member Data Documentation
SettingsKey
const string Messenger.Services.ThemeSelectorService.SettingsKey = "AppBackgroundRequestedTheme" static private
Definition at line 15 of file ThemeSelectorService.cs.
Property Documentation
Theme
ElementTheme Messenger.Services.ThemeSelectorService.Theme = ElementTheme.Default static get set
Definition at line 17 of file ThemeSelectorService.cs.
Referenced by Messenger.Services.ThemeSelectorService.InitializeAsync(), and Messenger.Services.ThemeSelectorService.SetThemeAsync().
The documentation for this class was generated from the following file:
Messenger/Messenger/Services/ThemeSelectorService.cs