VPR_Messenger: Messenger.Views.DialogBoxes.OperationConfirmationDialog Class Reference
Messenger.Views.DialogBoxes.OperationConfirmationDialog Class Reference
Static Public Member Functions
static OperationConfirmationDialog Set (string content)
Static Public Attributes
static readonly DependencyProperty ResponseProperty
static readonly DependencyProperty ContentTextProperty
Properties
bool Response [get, set]
string ContentText [get, set]
Detailed Description
Definition at line 7 of file OperationConfirmationDialog.xaml.cs.
Member Function Documentation
Set()
static OperationConfirmationDialog Messenger.Views.DialogBoxes.OperationConfirmationDialog.Set (string content) inline static
Definition at line 32 of file OperationConfirmationDialog.xaml.cs.
References Messenger.Views.DialogBoxes.OperationConfirmationDialog.ContentText.
Referenced by Messenger.Commands.PrivateChat.RemoveChatCommand.Execute(), Messenger.Commands.TeamManage.RemoveChannelCommand.Execute(), Messenger.Commands.TeamManage.RemoveTeamCommand.Execute(), and Messenger.Commands.TeamManage.RemoveUserCommand.Execute().
Member Data Documentation
ContentTextProperty
readonly DependencyProperty Messenger.Views.DialogBoxes.OperationConfirmationDialog.ContentTextProperty static
Initial value:
=
            DependencyProperty.Register("ContentText", typeof(string), typeof(OperationConfirmationDialog), new PropertyMetadata(string.Empty))
Definition at line 24 of file OperationConfirmationDialog.xaml.cs.
ResponseProperty
readonly DependencyProperty Messenger.Views.DialogBoxes.OperationConfirmationDialog.ResponseProperty static
Initial value:
=
            DependencyProperty.Register("Response", typeof(bool), typeof(OperationConfirmationDialog), new PropertyMetadata(false))
Definition at line 15 of file OperationConfirmationDialog.xaml.cs.
Property Documentation
ContentText
string Messenger.Views.DialogBoxes.OperationConfirmationDialog.ContentText get set
Definition at line 18 of file OperationConfirmationDialog.xaml.cs.
Referenced by Messenger.Views.DialogBoxes.OperationConfirmationDialog.Set().
Response
bool Messenger.Views.DialogBoxes.OperationConfirmationDialog.Response get set
Definition at line 9 of file OperationConfirmationDialog.xaml.cs.
Referenced by Messenger.Commands.PrivateChat.RemoveChatCommand.Execute(), Messenger.Commands.TeamManage.RemoveChannelCommand.Execute(), Messenger.Commands.TeamManage.RemoveTeamCommand.Execute(), and Messenger.Commands.TeamManage.RemoveUserCommand.Execute().
The documentation for this class was generated from the following file:
Messenger/Messenger/Views/DialogBoxes/OperationConfirmationDialog.xaml.cs