VPR_Messenger: Messenger.Views.Pages.SettingsPage Class Reference
Messenger.Views.Pages.SettingsPage Class Reference
Public Member Functions
SettingsPage ()
Public Attributes
bool editUserNameMode = false
Protected Member Functions
override void OnNavigatedTo (NavigationEventArgs e)
override void OnNavigatingFrom (NavigatingCancelEventArgs e)
Properties
SettingsViewModel ViewModel = new SettingsViewModel() [get]
Private Member Functions
void EditButton_Click (object sender, RoutedEventArgs e)
void UserNametbx_KeyDown (object sender, Windows.UI.Xaml.Input.KeyRoutedEventArgs e)
void GridView_SelectionChanged (object sender, SelectionChangedEventArgs e)
void EditCancelButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
void EditAcceptButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
void EditButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
Detailed Description
Definition at line 10 of file SettingsPage.xaml.cs.
Constructor & Destructor Documentation
SettingsPage()
Messenger.Views.Pages.SettingsPage.SettingsPage () inline
Definition at line 15 of file SettingsPage.xaml.cs.
Member Function Documentation
EditAcceptButton_Tapped()
void Messenger.Views.Pages.SettingsPage.EditAcceptButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e) inline private
Definition at line 103 of file SettingsPage.xaml.cs.
References Messenger.ViewModels.Pages.SettingsViewModel.CurrentBio, Messenger.ViewModels.Pages.SettingsViewModel.UpdateUserBioCommand, and Messenger.Views.Pages.SettingsPage.ViewModel.
EditButton_Click()
void Messenger.Views.Pages.SettingsPage.EditButton_Click (object sender, RoutedEventArgs e) inline private
Definition at line 41 of file SettingsPage.xaml.cs.
References Messenger.Views.Pages.SettingsPage.editUserNameMode, Messenger.ViewModels.Pages.SettingsViewModel.User, and Messenger.Views.Pages.SettingsPage.ViewModel.
EditButton_Tapped()
void Messenger.Views.Pages.SettingsPage.EditButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e) inline private
Definition at line 111 of file SettingsPage.xaml.cs.
EditCancelButton_Tapped()
void Messenger.Views.Pages.SettingsPage.EditCancelButton_Tapped (object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e) inline private
Definition at line 89 of file SettingsPage.xaml.cs.
References Messenger.ViewModels.Pages.SettingsViewModel.CurrentBio, and Messenger.Views.Pages.SettingsPage.ViewModel.
GridView_SelectionChanged()
void Messenger.Views.Pages.SettingsPage.GridView_SelectionChanged (object sender, SelectionChangedEventArgs e) inline private
Definition at line 81 of file SettingsPage.xaml.cs.
References Messenger.ViewModels.Pages.SettingsViewModel.SwitchThemeCommand, and Messenger.Views.Pages.SettingsPage.ViewModel.
OnNavigatedTo()
override void Messenger.Views.Pages.SettingsPage.OnNavigatedTo (NavigationEventArgs e) inline protected
Definition at line 20 of file SettingsPage.xaml.cs.
References Messenger.ViewModels.Pages.SettingsViewModel.ElementTheme, and Messenger.Views.Pages.SettingsPage.ViewModel.
OnNavigatingFrom()
override void Messenger.Views.Pages.SettingsPage.OnNavigatingFrom (NavigatingCancelEventArgs e) inline protected
Definition at line 35 of file SettingsPage.xaml.cs.
References Messenger.ViewModels.Pages.SettingsViewModel.UnregisterEvents(), and Messenger.Views.Pages.SettingsPage.ViewModel.
UserNametbx_KeyDown()
void Messenger.Views.Pages.SettingsPage.UserNametbx_KeyDown (object sender, Windows.UI.Xaml.Input.KeyRoutedEventArgs e) inline private
Definition at line 66 of file SettingsPage.xaml.cs.
References Messenger.ViewModels.Pages.SettingsViewModel.UpdateUsernameCommand, Messenger.ViewModels.Pages.SettingsViewModel.User, and Messenger.Views.Pages.SettingsPage.ViewModel.
Member Data Documentation
editUserNameMode
bool Messenger.Views.Pages.SettingsPage.editUserNameMode = false
Definition at line 12 of file SettingsPage.xaml.cs.
Referenced by Messenger.Views.Pages.SettingsPage.EditButton_Click().
Property Documentation
ViewModel
SettingsViewModel Messenger.Views.Pages.SettingsPage.ViewModel = new SettingsViewModel() get
Definition at line 13 of file SettingsPage.xaml.cs.
Referenced by Messenger.Views.Pages.SettingsPage.EditAcceptButton_Tapped(), Messenger.Views.Pages.SettingsPage.EditButton_Click(), Messenger.Views.Pages.SettingsPage.EditCancelButton_Tapped(), Messenger.Views.Pages.SettingsPage.GridView_SelectionChanged(), Messenger.Views.Pages.SettingsPage.OnNavigatedTo(), Messenger.Views.Pages.SettingsPage.OnNavigatingFrom(), and Messenger.Views.Pages.SettingsPage.UserNametbx_KeyDown().
The documentation for this class was generated from the following file:
Messenger/Messenger/Views/Pages/SettingsPage.xaml.cs