VPR_Messenger: Messenger.Commands.TeamManage.UpdateTeamRoleCommand Class Reference
Messenger.Commands.TeamManage.UpdateTeamRoleCommand Class Reference
Public Member Functions
bool CanExecute (object parameter)
async void Execute (object parameter)
Events
EventHandler CanExecuteChanged
Detailed Description
Definition at line 11 of file UpdateTeamRoleCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.TeamManage.UpdateTeamRoleCommand.CanExecute (object parameter) inline
Definition at line 15 of file UpdateTeamRoleCommand.cs.
Execute()
async void Messenger.Commands.TeamManage.UpdateTeamRoleCommand.Execute (object parameter) inline
Definition at line 20 of file UpdateTeamRoleCommand.cs.
References Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Color, Messenger.Core.Services.MessengerService.GrantPermission(), Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Id, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.PendingPermissions, Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set(), Messenger.ViewModels.DataViewModels.TeamRoleViewModel.TeamId, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Title, and Messenger.Core.Services.MessengerService.UpdateTeamRole().
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.TeamManage.UpdateTeamRoleCommand.CanExecuteChanged
Definition at line 13 of file UpdateTeamRoleCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/TeamManage/UpdateTeamRoleCommand.cs