VPR_Messenger: Messenger.Core.Services.FileSharingService Class Reference
Messenger.Core.Services.FileSharingService Class Reference
A class holding static methods to interact with blob storage for saving and retrieving message attachments
Static Public Member Functions
static async Task< MemoryStream > Download (string blobFileName)
Download a file into the local cache
static async Task< string > Upload (UploadData uploadFile)
Upload a file to the blob storage
static async Task< string > UploadFromBase64 (string data, string fileName)
Upload a base64 encoded file to the blob storage
static async Task< bool > Delete (string blobFileName)
Delete a blob file
Static Public Attributes
static readonly string localFileCachePath = Path.Combine(Path.GetTempPath(), "BIB_VPR" + Path.DirectorySeparatorChar)
The path at which to cache downloaded files
Properties
static ILogger logger [get]
Static Private Member Functions
static BlobContainerClient ConnectToContainer ()
Connect to our blob container
Static Private Attributes
const string blobServiceConnectionString = "DefaultEndpointsProtocol=https;AccountName=vpr;AccountKey=Y/A3PMNyH7ASxIB5KobgLqeJrBGW/vNKou0Ff8MWxs3B1PbNTZ0j+Ew9PAhiMkGObziTErqZ0j693pOc+hkVHQ==;EndpointSuffix=core.windows.net"
const string containerName = "attachments"
The name of the container all files are saved to
Detailed Description
A class holding static methods to interact with blob storage for saving and retrieving message attachments
Definition at line 16 of file FileSharingService.cs.
Member Function Documentation
ConnectToContainer()
static BlobContainerClient Messenger.Core.Services.FileSharingService.ConnectToContainer () inline static private
Connect to our blob container
Returns
BlobContainerClient object with established connection
Definition at line 38 of file FileSharingService.cs.
References Messenger.Core.Services.FileSharingService.blobServiceConnectionString, Messenger.Core.Services.FileSharingService.containerName, and Messenger.Core.Services.FileSharingService.logger.
Referenced by Messenger.Core.Services.FileSharingService.Delete(), Messenger.Core.Services.FileSharingService.Download(), Messenger.Core.Services.FileSharingService.Upload(), and Messenger.Core.Services.FileSharingService.UploadFromBase64().
Delete()
static async Task<bool> Messenger.Core.Services.FileSharingService.Delete (string blobFileName) inline static
Delete a blob file
Parameters
blobFileName A blob file name to delete
Returns
true if successfully deleted, false otherwise
Definition at line 170 of file FileSharingService.cs.
References Messenger.Core.Services.FileSharingService.ConnectToContainer(), and Messenger.Core.Services.FileSharingService.logger.
Referenced by Messenger.Core.Services.MessengerService.DeleteMessage().
Download()
static async Task<MemoryStream> Messenger.Core.Services.FileSharingService.Download (string blobFileName) inline static
Download a file into the local cache
Parameters
blobFileName A blob file to download
Returns
Stream on success, null otherwise
Definition at line 54 of file FileSharingService.cs.
References Messenger.Core.Services.FileSharingService.ConnectToContainer(), and Messenger.Core.Services.FileSharingService.logger.
Referenced by Messenger.Commands.Messenger.DownloadAttachmentCommand.Execute(), and Messenger.Helpers.MessageHelpers.MessageBuilder.WithAttachments().
Upload()
static async Task<string> Messenger.Core.Services.FileSharingService.Upload (UploadData uploadFile) inline static
Upload a file to the blob storage
Parameters
uploadFile An object with file data
Returns
The name of the blob file on success, null otherwise
Definition at line 89 of file FileSharingService.cs.
References Messenger.Core.Services.FileSharingService.ConnectToContainer(), Messenger.Core.Models.UploadData.FilePath, Messenger.Core.Services.FileSharingService.logger, and Messenger.Core.Models.UploadData.StreamFile.
Referenced by Messenger.Core.Services.MessengerService.SendMessage().
UploadFromBase64()
static async Task<string> Messenger.Core.Services.FileSharingService.UploadFromBase64 (string data, string fileName) inline static
Upload a base64 encoded file to the blob storage
Parameters
data The base64 encoded data to upload
fileName The name and extension to use for saving
Returns
The name of the blob file on success, null otherwise
Definition at line 127 of file FileSharingService.cs.
References Messenger.Core.Services.FileSharingService.ConnectToContainer(), and Messenger.Core.Services.FileSharingService.logger.
Referenced by Messenger.Core.Services.UserService.GetOrCreateApplicationUser().
Member Data Documentation
blobServiceConnectionString
const string Messenger.Core.Services.FileSharingService.blobServiceConnectionString = "DefaultEndpointsProtocol=https;AccountName=vpr;AccountKey=Y/A3PMNyH7ASxIB5KobgLqeJrBGW/vNKou0Ff8MWxs3B1PbNTZ0j+Ew9PAhiMkGObziTErqZ0j693pOc+hkVHQ==;EndpointSuffix=core.windows.net" static private
Definition at line 19 of file FileSharingService.cs.
Referenced by Messenger.Core.Services.FileSharingService.ConnectToContainer().
containerName
const string Messenger.Core.Services.FileSharingService.containerName = "attachments" static private
The name of the container all files are saved to
Definition at line 25 of file FileSharingService.cs.
Referenced by Messenger.Core.Services.FileSharingService.ConnectToContainer().
localFileCachePath
readonly string Messenger.Core.Services.FileSharingService.localFileCachePath = Path.Combine(Path.GetTempPath(), "BIB_VPR" + Path.DirectorySeparatorChar) static
The path at which to cache downloaded files
Definition at line 30 of file FileSharingService.cs.
Property Documentation
logger
ILogger Messenger.Core.Services.FileSharingService.logger static get
Definition at line 32 of file FileSharingService.cs.
Referenced by Messenger.Core.Services.FileSharingService.ConnectToContainer(), Messenger.Core.Services.FileSharingService.Delete(), Messenger.Core.Services.FileSharingService.Download(), Messenger.Core.Services.FileSharingService.Upload(), and Messenger.Core.Services.FileSharingService.UploadFromBase64().
The documentation for this class was generated from the following file:
Messenger/Messenger.Core/Services/FileSharingService.cs