VPR_Messenger: Messenger.Helpers.CacheQuery Class Reference
Messenger.Helpers.CacheQuery Class Reference
Static Public Member Functions
static async Task Reload ()
static bool IsChannelOf< T > (ChannelViewModel viewModel)
static IReadOnlyCollection< TeamViewModel > GetMyTeams ()
static IReadOnlyCollection< PrivateChatViewModel > GetMyChats ()
static IReadOnlyCollection< NotificationViewModel > GetNotifications ()
static bool TryGetMessages (uint channelId, out ObservableCollection< MessageViewModel > messages)
static T Get< T > (params object[] parameters)
Gets given model from the cache, following parameter(s) is/are required for each model: 'TeamViewModel' => 'uint teamId', 'PrivateChatViewModel' => 'uint chatId', 'ChannelViewModel' => 'uint channelId',
static async Task< T > AddOrUpdate< T > (params object[] parameters)
Adds or updates given model to the cache, following parameter(s) is/are required for each model: 'MessageViewModel' => 'Message message', 'TeamViewModel' => 'Team team', 'TeamRoleViewModel' => 'TeamRole teamRole', 'ChannelViewModel' => 'Channel channel', 'MemberViewModel' => 'uint teamId, User user'
static T Remove< T > (params object[] parameters)
Removes given model from the cache, following parameter(s) is/are required for each model: 'MessageViewModel' => 'Message message', 'TeamViewModel' => 'uint teamId', 'TeamRoleViewModel' => 'uint teamRoleId', 'ChannelViewModel' => 'uint channelId', 'MemberViewModel' => 'uint teamId, string userId'
static bool IsTypeOf< T > (Type type)
Detailed Description
Definition at line 17 of file CacheQuery.cs.
Member Function Documentation
AddOrUpdate< T >()
static async Task<T> Messenger.Helpers.CacheQuery.AddOrUpdate< T > (params object[] parameters) inline static
Adds or updates given model to the cache, following parameter(s) is/are required for each model: 'MessageViewModel' => 'Message message', 'TeamViewModel' => 'Team team', 'TeamRoleViewModel' => 'TeamRole teamRole', 'ChannelViewModel' => 'Channel channel', 'MemberViewModel' => 'uint teamId, User user'
Template Parameters
T Type of view model to be added/updated to the cache
Parameters
parameters Required parameter(s)
Returns
Added/Updated view model
Definition at line 138 of file CacheQuery.cs.
References Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateChannel(), Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateMember(), Messenger.Helpers.MessageHelpers.MessageManager.AddOrUpdateMessage(), Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeam(), Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeamRole(), Messenger.Services.Providers.StateProvider.MessageManager, and Messenger.Services.Providers.StateProvider.TeamManager.
Get< T >()
static T Messenger.Helpers.CacheQuery.Get< T > (params object[] parameters) inline static
Gets given model from the cache, following parameter(s) is/are required for each model: 'TeamViewModel' => 'uint teamId', 'PrivateChatViewModel' => 'uint chatId', 'ChannelViewModel' => 'uint channelId',
Template Parameters
T Type of view model to get from the cache
Parameters
parameters Required parameter(s)
Returns
Requested view model
Type Constraints
T : DataViewModel
Definition at line 79 of file CacheQuery.cs.
References Messenger.ViewModels.DataViewModels.TeamViewModel.Members, Messenger.Services.Providers.StateProvider.MessageManager, Messenger.Helpers.TeamHelpers.TeamManager.MyChats, Messenger.Helpers.TeamHelpers.TeamManager.MyTeams, and Messenger.Services.Providers.StateProvider.TeamManager.
GetMyChats()
static IReadOnlyCollection<PrivateChatViewModel> Messenger.Helpers.CacheQuery.GetMyChats () static
Referenced by Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Commands.PrivateChat.StartChatCommand.Execute(), Messenger.Commands.PrivateChat.StartChatWithUserCommand.Execute(), and Messenger.Helpers.CacheQuery.IsChannelOf< T >().
GetMyTeams()
static IReadOnlyCollection<TeamViewModel> Messenger.Helpers.CacheQuery.GetMyTeams () static
Referenced by Messenger.Services.Providers.EventProvider.Broadcast(), and Messenger.Helpers.CacheQuery.IsChannelOf< T >().
GetNotifications()
static IReadOnlyCollection<NotificationViewModel> Messenger.Helpers.CacheQuery.GetNotifications () static
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
IsChannelOf< T >()
static bool Messenger.Helpers.CacheQuery.IsChannelOf< T > (ChannelViewModel viewModel) inline static
Definition at line 41 of file CacheQuery.cs.
References Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, Messenger.Helpers.CacheQuery.GetMyChats(), and Messenger.Helpers.CacheQuery.GetMyTeams().
IsTypeOf< T >()
static bool Messenger.Helpers.CacheQuery.IsTypeOf< T > (Type type) inline static
Definition at line 238 of file CacheQuery.cs.
Reload()
static async Task Messenger.Helpers.CacheQuery.Reload () inline static
Definition at line 19 of file CacheQuery.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Services.Providers.StateProvider.CurrentUser, Messenger.Core.Helpers.Singleton< T >.Instance, Messenger.Helpers.TeamHelpers.TeamManager.LoadTeamsFromDatabase(), Messenger.Services.Providers.StateProvider.SelectedChannel, and Messenger.Services.Providers.StateProvider.TeamManager.
Remove< T >()
static T Messenger.Helpers.CacheQuery.Remove< T > (params object[] parameters) inline static
Removes given model from the cache, following parameter(s) is/are required for each model: 'MessageViewModel' => 'Message message', 'TeamViewModel' => 'uint teamId', 'TeamRoleViewModel' => 'uint teamRoleId', 'ChannelViewModel' => 'uint channelId', 'MemberViewModel' => 'uint teamId, string userId'
Template Parameters
T Type of view model to be removed from the cache
Parameters
parameters Required parameter(s)
Returns
Removed view model
Definition at line 202 of file CacheQuery.cs.
References Messenger.Services.Providers.StateProvider.MessageManager, Messenger.Helpers.TeamHelpers.TeamManager.RemoveChannel(), Messenger.Helpers.TeamHelpers.TeamManager.RemoveMember(), Messenger.Helpers.MessageHelpers.MessageManager.RemoveMessage(), Messenger.Helpers.TeamHelpers.TeamManager.RemoveTeam(), Messenger.Helpers.TeamHelpers.TeamManager.RemoveTeamRole(), and Messenger.Services.Providers.StateProvider.TeamManager.
TryGetMessages()
static bool Messenger.Helpers.CacheQuery.TryGetMessages (uint channelId, out ObservableCollection< MessageViewModel > messages) static
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
The documentation for this class was generated from the following file:
Messenger/Messenger/Helpers/CacheQuery.cs