VPR_Messenger: Messenger.ViewModels.Controls.UserSearchPanelViewModel Class Reference
Messenger.ViewModels.Controls.UserSearchPanelViewModel Class Reference
Public Member Functions
UserSearchPanelViewModel (Func< string, bool > searchFilter)
Protected Member Functions
void Set< T > (ref T storage, T value, [CallerMemberName]string propertyName=null)
void OnPropertyChanged (string propertyName)
Properties
Func< string, bool > SearchFilter [get, set]
User SelectedUser [get, set]
ObservableCollection< string > SearchResults [get, set]
ICommand SearchCommand [get]
ICommand GetSelectedUserCommand [get]
Events
PropertyChangedEventHandler PropertyChanged
Private Member Functions
async void Search (string keyword)
async void GetSelectedUser (string searchResult)
Private Attributes
Func< string, bool > _searchFilter
User _selectedUser
ObservableCollection< string > _searchResults
Detailed Description
Definition at line 13 of file UserSearchPanelViewModel.cs.
Constructor & Destructor Documentation
UserSearchPanelViewModel()
Messenger.ViewModels.Controls.UserSearchPanelViewModel.UserSearchPanelViewModel (Func< string, bool > searchFilter) inline
Definition at line 44 of file UserSearchPanelViewModel.cs.
References Messenger.ViewModels.Controls.UserSearchPanelViewModel.SearchFilter, and Messenger.ViewModels.Controls.UserSearchPanelViewModel.SearchResults.
Member Function Documentation
GetSelectedUser()
async void Messenger.ViewModels.Controls.UserSearchPanelViewModel.GetSelectedUser (string searchResult) inline private
Definition at line 78 of file UserSearchPanelViewModel.cs.
References Messenger.Core.Services.UserService.GetUser(), and Messenger.ViewModels.Controls.UserSearchPanelViewModel.SelectedUser.
OnPropertyChanged()
void Messenger.Helpers.Observable.OnPropertyChanged (string propertyName) protected inherited
Referenced by Messenger.Helpers.Observable.Set< T >().
Search()
async void Messenger.ViewModels.Controls.UserSearchPanelViewModel.Search (string keyword) inline private
FILTER OUT MEMBERS
Definition at line 51 of file UserSearchPanelViewModel.cs.
References Messenger.ViewModels.Controls.UserSearchPanelViewModel.SearchFilter, Messenger.ViewModels.Controls.UserSearchPanelViewModel.SearchResults, and Messenger.Core.Services.UserService.SearchUser().
Set< T >()
void Messenger.Helpers.Observable.Set< T > (ref T storage, T value, [CallerMemberName] string propertyName = null) inline protected inherited
Definition at line 11 of file Observable.cs.
References Messenger.Helpers.Observable.OnPropertyChanged().
Member Data Documentation
_searchFilter
Func<string, bool> Messenger.ViewModels.Controls.UserSearchPanelViewModel._searchFilter private
Definition at line 15 of file UserSearchPanelViewModel.cs.
_searchResults
ObservableCollection<string> Messenger.ViewModels.Controls.UserSearchPanelViewModel._searchResults private
Definition at line 31 of file UserSearchPanelViewModel.cs.
_selectedUser
User Messenger.ViewModels.Controls.UserSearchPanelViewModel._selectedUser private
Definition at line 23 of file UserSearchPanelViewModel.cs.
Property Documentation
GetSelectedUserCommand
ICommand Messenger.ViewModels.Controls.UserSearchPanelViewModel.GetSelectedUserCommand get
Definition at line 41 of file UserSearchPanelViewModel.cs.
Referenced by Messenger.Views.Controls.UserSearchPanel.SearchUserBox_SuggestionChosen().
SearchCommand
ICommand Messenger.ViewModels.Controls.UserSearchPanelViewModel.SearchCommand get
Definition at line 39 of file UserSearchPanelViewModel.cs.
Referenced by Messenger.Views.Controls.UserSearchPanel.SearchUserBox_TextChanged().
SearchFilter
Func<string, bool> Messenger.ViewModels.Controls.UserSearchPanelViewModel.SearchFilter get set
Definition at line 17 of file UserSearchPanelViewModel.cs.
Referenced by Messenger.ViewModels.Controls.UserSearchPanelViewModel.Search(), and Messenger.ViewModels.Controls.UserSearchPanelViewModel.UserSearchPanelViewModel().
SearchResults
ObservableCollection<string> Messenger.ViewModels.Controls.UserSearchPanelViewModel.SearchResults get set
Definition at line 33 of file UserSearchPanelViewModel.cs.
Referenced by Messenger.ViewModels.Controls.UserSearchPanelViewModel.Search(), and Messenger.ViewModels.Controls.UserSearchPanelViewModel.UserSearchPanelViewModel().
SelectedUser
User Messenger.ViewModels.Controls.UserSearchPanelViewModel.SelectedUser get set
Definition at line 25 of file UserSearchPanelViewModel.cs.
Referenced by Messenger.ViewModels.Controls.UserSearchPanelViewModel.GetSelectedUser().
Event Documentation
PropertyChanged
PropertyChangedEventHandler Messenger.Helpers.Observable.PropertyChanged inherited
Definition at line 9 of file Observable.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/ViewModels/Controls/UserSearchPanelViewModel.cs