VPR_Messenger: Messenger.Views.Subcontrols.SideNavigation Class Reference
Messenger.Views.Subcontrols.SideNavigation Class Reference
Public Member Functions
SideNavigation ()
Properties
ICommand NavigateToTeams [get]
ICommand NavigateToChats [get]
ICommand NavigateToNotifications [get]
Private Member Functions
void OnNavigated (object sender, NavigationEventArgs e)
void ToggleButtons (Type type)
Detailed Description
Definition at line 11 of file SideNavigation.xaml.cs.
Constructor & Destructor Documentation
SideNavigation()
Messenger.Views.Subcontrols.SideNavigation.SideNavigation () inline
Definition at line 19 of file SideNavigation.xaml.cs.
References Messenger.Services.NavigationService.Navigated, and Messenger.Views.Subcontrols.SideNavigation.OnNavigated().
Member Function Documentation
OnNavigated()
void Messenger.Views.Subcontrols.SideNavigation.OnNavigated (object sender, NavigationEventArgs e) inline private
Definition at line 26 of file SideNavigation.xaml.cs.
References Messenger.Views.Subcontrols.SideNavigation.ToggleButtons().
Referenced by Messenger.Views.Subcontrols.SideNavigation.SideNavigation().
ToggleButtons()
void Messenger.Views.Subcontrols.SideNavigation.ToggleButtons (Type type) inline private
Definition at line 33 of file SideNavigation.xaml.cs.
Referenced by Messenger.Views.Subcontrols.SideNavigation.OnNavigated().
Property Documentation
NavigateToChats
ICommand Messenger.Views.Subcontrols.SideNavigation.NavigateToChats get
Definition at line 15 of file SideNavigation.xaml.cs.
NavigateToNotifications
ICommand Messenger.Views.Subcontrols.SideNavigation.NavigateToNotifications get
Definition at line 17 of file SideNavigation.xaml.cs.
NavigateToTeams
ICommand Messenger.Views.Subcontrols.SideNavigation.NavigateToTeams get
Definition at line 13 of file SideNavigation.xaml.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Views/Subcontrols/SideNavigation.xaml.cs