VPR_Messenger: Messenger.Helpers.TeamHelpers.TeamManager Class Reference
Messenger.Helpers.TeamHelpers.TeamManager Class Reference
Public Member Functions
TeamManager (StateProvider provider)
async Task Initialize (UserViewModel user)
async Task< IEnumerable< TeamViewModel > > LoadTeamsFromDatabase (UserViewModel user)
async Task< TeamViewModel > AddOrUpdateTeam (Team teamData)
async Task< IList< TeamViewModel > > AddOrUpdateTeam (IEnumerable< Team > teamData)
ChannelViewModel AddOrUpdateChannel (Channel channelData)
IList< ChannelViewModel > AddOrUpdateChannel (IEnumerable< Channel > channelData)
async Task< MemberViewModel > AddOrUpdateMember (uint teamId, User userData)
async Task< IList< MemberViewModel > > AddOrUpdateMember (uint teamId, IEnumerable< User > userData)
async Task< TeamRoleViewModel > AddOrUpdateTeamRole (TeamRole teamRole)
TeamViewModel RemoveTeam (uint teamId)
TeamRoleViewModel RemoveTeamRole (uint roleId)
ChannelViewModel RemoveChannel (uint channelId)
MemberViewModel RemoveMember (uint teamId, string userId)
Protected Member Functions
void Set< T > (ref T storage, T value, [CallerMemberName]string propertyName=null)
void OnPropertyChanged (string propertyName)
Properties
ObservableCollection< TeamViewModel > MyTeams [get]
ObservableCollection< PrivateChatViewModel > MyChats [get]
Events
PropertyChangedEventHandler PropertyChanged
Private Member Functions
void OnMessagesLoadedForChannel (object sender, ManagerEventArgs args)
Fires only when initializing, to set the last message of the channel to be shown on the navigation panel
Private Attributes
readonly StateProvider _provider
ObservableCollection< TeamViewModel > _myTeams = new ObservableCollection<TeamViewModel>()
ObservableCollection< PrivateChatViewModel > _myChats = new ObservableCollection<PrivateChatViewModel>()
Detailed Description
Definition at line 12 of file TeamManager.cs.
Constructor & Destructor Documentation
TeamManager()
Messenger.Helpers.TeamHelpers.TeamManager.TeamManager (StateProvider provider) inline
Definition at line 40 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._provider.
Member Function Documentation
AddOrUpdateChannel() [1/2]
ChannelViewModel Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateChannel (Channel channelData) inline
Definition at line 164 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._myTeams, Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, Messenger.ViewModels.DataViewModels.TeamViewModel.Channels, Messenger.ViewModels.DataViewModels.TeamViewModel.Id, and Messenger.Helpers.TeamHelpers.TeamBuilder.Map().
Referenced by Messenger.Helpers.CacheQuery.AddOrUpdate< T >(), and Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateChannel().
AddOrUpdateChannel() [2/2]
IList<ChannelViewModel> Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateChannel (IEnumerable< Channel > channelData) inline
Definition at line 190 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateChannel().
AddOrUpdateMember() [1/2]
async Task<IList<MemberViewModel> > Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateMember (uint teamId, IEnumerable< User > userData) inline
Definition at line 233 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateMember().
AddOrUpdateMember() [2/2]
async Task<MemberViewModel> Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateMember (uint teamId, User userData) inline
Definition at line 202 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._myTeams, Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.ViewModels.DataViewModels.UserViewModel.Id, Messenger.Helpers.TeamHelpers.TeamBuilder.Map(), Messenger.ViewModels.DataViewModels.TeamViewModel.Members, and Messenger.ViewModels.DataViewModels.MemberViewModel.TeamId.
Referenced by Messenger.Helpers.CacheQuery.AddOrUpdate< T >(), and Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateMember().
AddOrUpdateTeam() [1/2]
async Task<IList<TeamViewModel> > Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeam (IEnumerable< Team > teamData) inline
Definition at line 151 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeam().
AddOrUpdateTeam() [2/2]
async Task<TeamViewModel> Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeam (Team teamData) inline
Definition at line 107 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._myChats, Messenger.Helpers.TeamHelpers.TeamManager._myTeams, Messenger.Helpers.TeamHelpers.TeamManager._provider, Messenger.Helpers.TeamHelpers.TeamBuilder.Build(), Messenger.Services.Providers.StateProvider.CurrentUser, Messenger.ViewModels.DataViewModels.TeamViewModel.Id, and Messenger.ViewModels.DataViewModels.UserViewModel.Id.
Referenced by Messenger.Helpers.CacheQuery.AddOrUpdate< T >(), Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeam(), and Messenger.Helpers.TeamHelpers.TeamManager.LoadTeamsFromDatabase().
AddOrUpdateTeamRole()
async Task<TeamRoleViewModel> Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeamRole (TeamRole teamRole) inline
Definition at line 247 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._myTeams, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.Id, Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Helpers.TeamHelpers.TeamBuilder.Map(), and Messenger.ViewModels.DataViewModels.TeamViewModel.TeamRoles.
Referenced by Messenger.Helpers.CacheQuery.AddOrUpdate< T >().
Initialize()
async Task Messenger.Helpers.TeamHelpers.TeamManager.Initialize (UserViewModel user) inline
Definition at line 45 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._provider, Messenger.Helpers.TeamHelpers.TeamManager.LoadTeamsFromDatabase(), Messenger.Services.Providers.StateProvider.MessageManager, and Messenger.Helpers.TeamHelpers.TeamManager.OnMessagesLoadedForChannel().
Referenced by Messenger.Services.Providers.StateProviderExtension.Initialize().
LoadTeamsFromDatabase()
async Task<IEnumerable<TeamViewModel> > Messenger.Helpers.TeamHelpers.TeamManager.LoadTeamsFromDatabase (UserViewModel user) inline
Definition at line 85 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._myChats, Messenger.Helpers.TeamHelpers.TeamManager._myTeams, Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeam(), and Messenger.Helpers.TeamHelpers.TeamBuilder.GetTeamsFromDatabase().
Referenced by Messenger.Helpers.TeamHelpers.TeamManager.Initialize(), and Messenger.Helpers.CacheQuery.Reload().
OnMessagesLoadedForChannel()
void Messenger.Helpers.TeamHelpers.TeamManager.OnMessagesLoadedForChannel (object sender, ManagerEventArgs args) inline private
Fires only when initializing, to set the last message of the channel to be shown on the navigation panel
Parameters
sender Message Manager
args Argument containing the messages, team and channel
Definition at line 57 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._myChats, Messenger.Helpers.TeamHelpers.TeamManager._myTeams, Messenger.Models.ManagerEventArgs.Channel, Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, Messenger.ViewModels.DataViewModels.TeamViewModel.Channels, Messenger.ViewModels.DataViewModels.ChannelViewModel.LastMessage, Messenger.ViewModels.DataViewModels.PrivateChatViewModel.LastMessage, Messenger.ViewModels.DataViewModels.PrivateChatViewModel.MainChannel, Messenger.Models.ManagerEventArgs.Messages, and Messenger.Models.ManagerEventArgs.Team.
Referenced by Messenger.Helpers.TeamHelpers.TeamManager.Initialize().
OnPropertyChanged()
void Messenger.Helpers.Observable.OnPropertyChanged (string propertyName) protected inherited
Referenced by Messenger.Helpers.Observable.Set< T >().
RemoveChannel()
ChannelViewModel Messenger.Helpers.TeamHelpers.TeamManager.RemoveChannel (uint channelId) inline
Definition at line 309 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._myTeams, Messenger.Core.Models.Channel.ChannelId, Messenger.ViewModels.DataViewModels.TeamViewModel.Channels, and Messenger.ViewModels.DataViewModels.ChannelViewModel.TeamId.
Referenced by Messenger.Helpers.CacheQuery.Remove< T >().
RemoveMember()
MemberViewModel Messenger.Helpers.TeamHelpers.TeamManager.RemoveMember (uint teamId, string userId) inline
Definition at line 325 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._myTeams, and Messenger.ViewModels.DataViewModels.TeamViewModel.Members.
Referenced by Messenger.Helpers.CacheQuery.Remove< T >().
RemoveTeam()
TeamViewModel Messenger.Helpers.TeamHelpers.TeamManager.RemoveTeam (uint teamId) inline
Definition at line 279 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._myTeams.
Referenced by Messenger.Helpers.CacheQuery.Remove< T >().
RemoveTeamRole()
TeamRoleViewModel Messenger.Helpers.TeamHelpers.TeamManager.RemoveTeamRole (uint roleId) inline
Definition at line 293 of file TeamManager.cs.
References Messenger.Helpers.TeamHelpers.TeamManager._myTeams, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.TeamId, and Messenger.ViewModels.DataViewModels.TeamViewModel.TeamRoles.
Referenced by Messenger.Helpers.CacheQuery.Remove< T >().
Set< T >()
void Messenger.Helpers.Observable.Set< T > (ref T storage, T value, [CallerMemberName] string propertyName = null) inline protected inherited
Definition at line 11 of file Observable.cs.
References Messenger.Helpers.Observable.OnPropertyChanged().
Member Data Documentation
_myChats
ObservableCollection<PrivateChatViewModel> Messenger.Helpers.TeamHelpers.TeamManager._myChats = new ObservableCollection<PrivateChatViewModel>() private
Definition at line 20 of file TeamManager.cs.
Referenced by Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeam(), Messenger.Helpers.TeamHelpers.TeamManager.LoadTeamsFromDatabase(), and Messenger.Helpers.TeamHelpers.TeamManager.OnMessagesLoadedForChannel().
_myTeams
ObservableCollection<TeamViewModel> Messenger.Helpers.TeamHelpers.TeamManager._myTeams = new ObservableCollection<TeamViewModel>() private
Definition at line 18 of file TeamManager.cs.
Referenced by Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateChannel(), Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateMember(), Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeam(), Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeamRole(), Messenger.Helpers.TeamHelpers.TeamManager.LoadTeamsFromDatabase(), Messenger.Helpers.TeamHelpers.TeamManager.OnMessagesLoadedForChannel(), Messenger.Helpers.TeamHelpers.TeamManager.RemoveChannel(), Messenger.Helpers.TeamHelpers.TeamManager.RemoveMember(), Messenger.Helpers.TeamHelpers.TeamManager.RemoveTeam(), and Messenger.Helpers.TeamHelpers.TeamManager.RemoveTeamRole().
_provider
readonly StateProvider Messenger.Helpers.TeamHelpers.TeamManager._provider private
Definition at line 16 of file TeamManager.cs.
Referenced by Messenger.Helpers.TeamHelpers.TeamManager.AddOrUpdateTeam(), Messenger.Helpers.TeamHelpers.TeamManager.Initialize(), and Messenger.Helpers.TeamHelpers.TeamManager.TeamManager().
Property Documentation
MyChats
ObservableCollection<PrivateChatViewModel> Messenger.Helpers.TeamHelpers.TeamManager.MyChats get
Definition at line 32 of file TeamManager.cs.
Referenced by Messenger.Helpers.CacheQuery.Get< T >(), and Messenger.Services.Providers.StateProviderExtension.LoadAllMessages().
MyTeams
ObservableCollection<TeamViewModel> Messenger.Helpers.TeamHelpers.TeamManager.MyTeams get
Definition at line 24 of file TeamManager.cs.
Referenced by Messenger.Helpers.CacheQuery.Get< T >(), and Messenger.Services.Providers.StateProviderExtension.LoadAllMessages().
Event Documentation
PropertyChanged
PropertyChangedEventHandler Messenger.Helpers.Observable.PropertyChanged inherited
Definition at line 9 of file Observable.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Helpers/TeamHelpers/TeamManager.cs