VPR_Messenger: Messenger.Commands.TeamManage.RemoveTeamCommand Class Reference
Messenger.Commands.TeamManage.RemoveTeamCommand Class Reference
Public Member Functions
bool CanExecute (object parameter)
async void Execute (object parameter)
Events
EventHandler CanExecuteChanged
Detailed Description
Definition at line 15 of file RemoveTeamCommand.cs.
Member Function Documentation
CanExecute()
bool Messenger.Commands.TeamManage.RemoveTeamCommand.CanExecute (object parameter) inline
Definition at line 19 of file RemoveTeamCommand.cs.
Execute()
async void Messenger.Commands.TeamManage.RemoveTeamCommand.Execute (object parameter) inline
Definition at line 24 of file RemoveTeamCommand.cs.
References Messenger.Core.Services.MessengerService.DeleteTeam(), Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Views.DialogBoxes.OperationConfirmationDialog.Response, Messenger.Views.DialogBoxes.ResultConfirmationDialog.Set(), and Messenger.Views.DialogBoxes.OperationConfirmationDialog.Set().
Event Documentation
CanExecuteChanged
EventHandler Messenger.Commands.TeamManage.RemoveTeamCommand.CanExecuteChanged
Definition at line 17 of file RemoveTeamCommand.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Commands/TeamManage/RemoveTeamCommand.cs