VPR_Messenger: Messenger.Services.DragAndDrop.DragDropService Class Reference
Messenger.Services.DragAndDrop.DragDropService Class Reference
Static Public Member Functions
static void SetConfiguration (DependencyObject dependencyObject, DropConfiguration value)
static DropConfiguration GetConfiguration (DependencyObject dependencyObject)
static void SetVisualConfiguration (DependencyObject dependencyObject, VisualDropConfiguration value)
static VisualDropConfiguration GetVisualConfiguration (DependencyObject dependencyObject)
Static Private Member Functions
static void OnConfigurationPropertyChanged (DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e)
static void ConfigureUIElement (UIElement element, DropConfiguration configuration)
static void ConfigureListView (ListViewBase listview, ListViewDropConfiguration configuration)
static void OnVisualConfigurationPropertyChanged (DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e)
Static Private Attributes
static DependencyProperty configurationProperty
static DependencyProperty visualConfigurationProperty
Detailed Description
Definition at line 11 of file DragDropService.cs.
Member Function Documentation
ConfigureListView()
static void Messenger.Services.DragAndDrop.DragDropService.ConfigureListView (ListViewBase listview, ListViewDropConfiguration configuration) inline static private
Definition at line 96 of file DragDropService.cs.
References Messenger.Models.DragDropStartingData.Data, Messenger.Services.DragAndDrop.ListViewDropConfiguration.DragItemsCompletedCommand, Messenger.Services.DragAndDrop.ListViewDropConfiguration.DragItemsStartingCommand, and Messenger.Models.DragDropCompletedData.DropResult.
Referenced by Messenger.Services.DragAndDrop.DragDropService.OnConfigurationPropertyChanged().
ConfigureUIElement()
static void Messenger.Services.DragAndDrop.DragDropService.ConfigureUIElement (UIElement element, DropConfiguration configuration) inline static private
Definition at line 65 of file DragDropService.cs.
References Messenger.Models.DragDropData.AcceptedOperation, Messenger.Services.DragAndDrop.DropConfiguration.DragEnterCommand, Messenger.Services.DragAndDrop.DropConfiguration.DragLeaveCommand, Messenger.Services.DragAndDrop.DropConfiguration.DragOverCommand, and Messenger.Services.DragAndDrop.DropConfiguration.ProcessComandsAsync().
Referenced by Messenger.Services.DragAndDrop.DragDropService.OnConfigurationPropertyChanged().
GetConfiguration()
static DropConfiguration Messenger.Services.DragAndDrop.DragDropService.GetConfiguration (DependencyObject dependencyObject) inline static
Definition at line 33 of file DragDropService.cs.
References Messenger.Services.DragAndDrop.DragDropService.configurationProperty.
Referenced by Messenger.Services.DragAndDrop.DragDropService.OnConfigurationPropertyChanged().
GetVisualConfiguration()
static VisualDropConfiguration Messenger.Services.DragAndDrop.DragDropService.GetVisualConfiguration (DependencyObject dependencyObject) inline static
Definition at line 46 of file DragDropService.cs.
References Messenger.Services.DragAndDrop.DragDropService.visualConfigurationProperty.
Referenced by Messenger.Services.DragAndDrop.DragDropService.OnVisualConfigurationPropertyChanged().
OnConfigurationPropertyChanged()
static void Messenger.Services.DragAndDrop.DragDropService.OnConfigurationPropertyChanged (DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e) inline static private
Definition at line 51 of file DragDropService.cs.
References Messenger.Services.DragAndDrop.DragDropService.ConfigureListView(), Messenger.Services.DragAndDrop.DragDropService.ConfigureUIElement(), and Messenger.Services.DragAndDrop.DragDropService.GetConfiguration().
OnVisualConfigurationPropertyChanged()
static void Messenger.Services.DragAndDrop.DragDropService.OnVisualConfigurationPropertyChanged (DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e) inline static private
Definition at line 111 of file DragDropService.cs.
References Messenger.Services.DragAndDrop.DragDropService.GetVisualConfiguration().
SetConfiguration()
static void Messenger.Services.DragAndDrop.DragDropService.SetConfiguration (DependencyObject dependencyObject, DropConfiguration value) inline static
Definition at line 25 of file DragDropService.cs.
References Messenger.Services.DragAndDrop.DragDropService.configurationProperty.
SetVisualConfiguration()
static void Messenger.Services.DragAndDrop.DragDropService.SetVisualConfiguration (DependencyObject dependencyObject, VisualDropConfiguration value) inline static
Definition at line 38 of file DragDropService.cs.
References Messenger.Services.DragAndDrop.DragDropService.visualConfigurationProperty.
Member Data Documentation
configurationProperty
DependencyProperty Messenger.Services.DragAndDrop.DragDropService.configurationProperty static private
Initial value:
= DependencyProperty.RegisterAttached(
        "Configuration",
        typeof(DropConfiguration),
        typeof(DragDropService),
        new PropertyMetadata(null, OnConfigurationPropertyChanged))
Definition at line 13 of file DragDropService.cs.
Referenced by Messenger.Services.DragAndDrop.DragDropService.GetConfiguration(), and Messenger.Services.DragAndDrop.DragDropService.SetConfiguration().
visualConfigurationProperty
DependencyProperty Messenger.Services.DragAndDrop.DragDropService.visualConfigurationProperty static private
Initial value:
= DependencyProperty.RegisterAttached(
        "VisualConfiguration",
        typeof(VisualDropConfiguration),
        typeof(DragDropService),
        new PropertyMetadata(null, OnVisualConfigurationPropertyChanged))
Definition at line 19 of file DragDropService.cs.
Referenced by Messenger.Services.DragAndDrop.DragDropService.GetVisualConfiguration(), and Messenger.Services.DragAndDrop.DragDropService.SetVisualConfiguration().
The documentation for this class was generated from the following file:
Messenger/Messenger/Services/DragAndDrop/DragDropService.cs