VPR_Messenger: Messenger.Core.Services.MessengerService Class Reference
Messenger.Core.Services.MessengerService Class Reference
Holds static wrappers around other Service's methods and adds Message passing to notify other clients of changes
Static Public Member Functions
static async Task< IList< Team > > Initialize (string userId, string connectionString=null)
Connects the given user to the teams he is a member of
static async Task< IEnumerable< Message > > GetMessages (uint channelId)
Gets all messages of the team
static async Task< Message > GetMessage (uint messageId)
static async Task< bool > SendMessage (Message message, uint teamId)
Saves the message to the database and simultaneously broadcasts to the connected Signal-R hub
static async Task< bool > DeleteMessage (uint messageId, uint teamId)
Delete a Message and notify other clients
static async Task< bool > UpdateMessage (uint messageId, string newContent, uint teamId)
Change a messages content and notify other clients
static async Task< IEnumerable< Reaction > > GetReactions (uint messageId)
static async Task< Reaction > CreateMessageReaction (uint messageId, string userId, uint teamId, string reaction)
Add a reaction to a message and notify other clients
static async Task< Reaction > DeleteMessageReaction (uint messageId, string userId, uint teamId, string reaction)
Remove a reaction from a message and notify other clients
static async Task< IEnumerable< Team > > GetTeams (string userId)
Gets all teams the current user has membership of
static async Task< Team > GetTeam (uint teamId)
Gets the team with the given team id
static async Task< uint?> CreateTeam (string creatorId, string teamName, string teamDescription="")
Saves new team to database, create a main channel and join the hub group of the team
static async Task< bool > UpdateTeamName (string teamName, uint teamId)
Rename A team and notify other clients
static async Task< Team > DeleteTeam (uint teamId)
Delete a team alongside it's channels and memberships
static async Task< bool > UpdateTeamDescription (string teamDescription, uint teamId)
Change a specified team's description and notify other clients
static async Task< uint?> CreateChannel (string channelName, uint teamId)
Add a channel to a specified team
static async Task< Channel > DeleteChannel (uint channelId)
Remove a specified channel from it's team
static async Task< bool > RenameChannel (string channelName, uint channelId)
Rename A channel and notify other clients
static async Task< IEnumerable< Channel > > GetChannelsForTeam (uint teamId)
Gets all channels from a team
static async Task< IEnumerable< User > > GetTeamMembers (uint teamId)
Gets all users in current Team
static async Task< User > GetUserWithNameId (string username, uint nameId)
Returns a user by username and nameId
static async Task< bool > SendInvitation (string userId, uint teamId)
Saves new membership to database and add the user to the hub group of the team
static async Task< bool > RemoveMember (string userId, uint teamId)
Removes a user from a specific team
static async Task< bool > UpdateUserEmail (string userId, string newEmail)
static async Task< bool > UpdateUserUsername (string userId, string newUsername)
static async Task< bool > UpdateUserBio (string userId, string newBio)
Update A user's bio
static async Task< bool > UpdateUserPhoto (string userId, string newPhotoURL)
static async Task< IEnumerable< TeamRole > > GetRolesList (uint teamId, string userId)
static async Task< bool > CreateTeamRole (string role, uint teamId, string colorCode)
Add a role to a team with the specified teamId and notify other clients
static async Task< bool > UpdateTeamRole (uint roleId, string role, string colorCode)
Update team's role with the specified teamId and notify other clients
static async Task< bool > DeleteTeamRole (string role, uint teamId)
Remove a role from a team's available roles and all members roles and notify other clients
static async Task< bool > AssignUserRole (string role, string userId, uint teamId)
Assign a role to a team's member and notify other clients
static async Task< bool > UnassignUserRole (string role, string userId, uint teamId)
Unassign a role from a team's member and notify other clients
static async Task< bool > GrantPermission (uint teamId, string role, Permissions permission)
static async Task< bool > RevokePermission (uint teamId, string role, Permissions permission)
Revoke a permission from a specified team's role and notify other clients
static async Task< uint?> StartChat (string userId, string targetUserId)
Start a private chat between two users and notify them
Properties
static SignalRService SignalRService [get]
The signalRService holding the connection and defined messages to send to the hub
static ILogger logger [get]
Detailed Description
Holds static wrappers around other Service's methods and adds Message passing to notify other clients of changes
Definition at line 19 of file MessengerService.cs.
Member Function Documentation
AssignUserRole()
static async Task<bool> Messenger.Core.Services.MessengerService.AssignUserRole (string role, string userId, uint teamId) inline static
Assign a role to a team's member and notify other clients
Parameters
role The name of the role to assign to the user
userId The id of the user to assign the role to
teamId The team to assign a role to a member in
Returns
True if successful, false otherwise
Definition at line 947 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.AssignRole(), Messenger.Core.Services.TeamService.GetTeam(), Messenger.Core.Services.UserService.GetUser(), Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.SignalRService.UpdateMember().
Referenced by Messenger.Commands.TeamManage.AssignTeamRoleCommand.Execute().
CreateChannel()
static async Task<uint?> Messenger.Core.Services.MessengerService.CreateChannel (string channelName, uint teamId) inline static
Add a channel to a specified team
Parameters
teamId Id of the team to add the channel to
channelName Name of the newly created channel
Returns
True if the channel was successfully created, false otherwise
Definition at line 514 of file MessengerService.cs.
References Messenger.Core.Services.SignalRService.CreateChannel(), Messenger.Core.Services.ChannelService.CreateChannel(), Messenger.Core.Services.ChannelService.GetChannel(), and Messenger.Core.Services.MessengerService.logger.
Referenced by Messenger.Commands.TeamManage.CreateChannelCommand.Execute().
CreateMessageReaction()
static async Task<Reaction> Messenger.Core.Services.MessengerService.CreateMessageReaction (uint messageId, string userId, uint teamId, string reaction) inline static
Add a reaction to a message and notify other clients
Parameters
messageId The id of the message to add a reaction to
userId The id of the user making the reaction
reaction The reaction to add to the message
Returns
Definition at line 249 of file MessengerService.cs.
References Messenger.Core.Services.MessageService.AddReaction(), Messenger.Core.Services.MessageService.GetMessage(), Messenger.Core.Services.MessengerService.logger, Messenger.Core.Services.MessageService.RetrieveReactions(), and Messenger.Core.Services.SignalRService.UpdateMessageReactions().
Referenced by Messenger.Commands.Messenger.ToggleReactionCommand.Execute().
CreateTeam()
static async Task<uint?> Messenger.Core.Services.MessengerService.CreateTeam (string creatorId, string teamName, string teamDescription = "") inline static
Saves new team to database, create a main channel and join the hub group of the team
Parameters
creatorId Creator user id
teamName Name of the team
teamDescription Description of the team(optional)
Returns
Id of the newly created team on success, null on fail (error will be handled in each service)
Definition at line 358 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.AddMember(), Messenger.Core.Services.TeamService.AddRole(), Messenger.Core.Services.TeamService.AssignRole(), Messenger.Core.Services.ChannelService.CreateChannel(), Messenger.Core.Services.TeamService.CreateTeam(), Messenger.Core.Services.SignalRService.CreateTeam(), Messenger.Core.Services.TeamService.GetTeam(), Messenger.Core.Services.TeamService.GrantPermission(), Messenger.Core.Models.Team.Id, Messenger.Core.Services.SignalRService.JoinTeam(), and Messenger.Core.Services.MessengerService.logger.
Referenced by Messenger.Commands.TeamManage.CreateTeamCommand.Execute().
CreateTeamRole()
static async Task<bool> Messenger.Core.Services.MessengerService.CreateTeamRole (string role, uint teamId, string colorCode) inline static
Add a role to a team with the specified teamId and notify other clients
Parameters
role The name of the role to add
teamId The id of the team to add the role to
colorCode Hex code of the color
Returns
True if successful, false otherwise
Definition at line 852 of file MessengerService.cs.
References Messenger.Core.Services.SignalRService.AddOrUpdateTeamRole(), Messenger.Core.Services.TeamService.AddRole(), Messenger.Core.Services.TeamService.GetRole(), and Messenger.Core.Services.MessengerService.logger.
Referenced by Messenger.Commands.TeamManage.CreateTeamRoleCommand.Execute().
DeleteChannel()
static async Task<Channel> Messenger.Core.Services.MessengerService.DeleteChannel (uint channelId) inline static
Remove a specified channel from it's team
Parameters
channelId Id of the channel to delete
Returns
An awaitable task
Definition at line 544 of file MessengerService.cs.
References Messenger.Core.Services.SignalRService.DeleteChannel(), Messenger.Core.Services.ChannelService.GetChannel(), Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.ChannelService.RemoveChannel().
Referenced by Messenger.Commands.TeamManage.RemoveChannelCommand.Execute().
DeleteMessage()
static async Task<bool> Messenger.Core.Services.MessengerService.DeleteMessage (uint messageId, uint teamId) inline static
Delete a Message and notify other clients
Parameters
messageId The id of the message to delete
Returns
True if the team was successfully deleted, false otherwise
Definition at line 176 of file MessengerService.cs.
References Messenger.Core.Services.FileSharingService.Delete(), Messenger.Core.Services.SignalRService.DeleteMessage(), Messenger.Core.Services.MessageService.DeleteMessage(), Messenger.Core.Services.MessageService.GetBlobFileNamesOfAttachments(), Messenger.Core.Services.MessageService.GetMessage(), and Messenger.Core.Services.MessengerService.logger.
Referenced by Messenger.Commands.Messenger.DeleteMessageCommand.Execute().
DeleteMessageReaction()
static async Task<Reaction> Messenger.Core.Services.MessengerService.DeleteMessageReaction (uint messageId, string userId, uint teamId, string reaction) inline static
Remove a reaction from a message and notify other clients
Parameters
messageId The id of the message to remove a reaction from
userId The id of the user whose reaction to remove
reaction The reaction to remove from the message
Returns
Whetever or not to the reaction was successfully removed
Definition at line 282 of file MessengerService.cs.
References Messenger.Core.Services.MessageService.GetMessage(), Messenger.Core.Models.Message.Id, Messenger.Core.Services.MessengerService.logger, Messenger.Core.Services.MessageService.RemoveReaction(), Messenger.Core.Services.MessageService.RetrieveReactions(), and Messenger.Core.Services.SignalRService.UpdateMessageReactions().
Referenced by Messenger.Commands.Messenger.ToggleReactionCommand.Execute().
DeleteTeam()
static async Task<Team> Messenger.Core.Services.MessengerService.DeleteTeam (uint teamId) inline static
Delete a team alongside it's channels and memberships
Parameters
teamId The id of the team to delete
Returns
The deleted Team on success, null otherwise
Definition at line 456 of file MessengerService.cs.
References Messenger.Core.Services.SignalRService.DeleteTeam(), Messenger.Core.Services.TeamService.DeleteTeam(), Messenger.Core.Services.TeamService.GetTeam(), Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.ChannelService.RemoveAllChannels().
Referenced by Messenger.Commands.PrivateChat.RemoveChatCommand.Execute(), and Messenger.Commands.TeamManage.RemoveTeamCommand.Execute().
DeleteTeamRole()
static async Task<bool> Messenger.Core.Services.MessengerService.DeleteTeamRole (string role, uint teamId) inline static
Remove a role from a team's available roles and all members roles and notify other clients
Parameters
role The name of the role to remove
teamId The id of the team to remove the role from
Returns
True if successful, false otherwise
Definition at line 907 of file MessengerService.cs.
References Messenger.Core.Services.SignalRService.DeleteTeamRole(), Messenger.Core.Services.TeamService.GetRole(), Messenger.Core.Services.TeamService.GetUsersWithRole(), Messenger.Core.Services.MessengerService.logger, Messenger.Core.Services.TeamService.RemoveRole(), and Messenger.Core.Services.TeamService.UnAssignRole().
Referenced by Messenger.Commands.TeamManage.RemoveTeamRoleCommand.Execute().
GetChannelsForTeam()
static async Task<IEnumerable<Channel> > Messenger.Core.Services.MessengerService.GetChannelsForTeam (uint teamId) inline static
Gets all channels from a team
Parameters
teamId
Returns
Returns a list with all channels
Definition at line 590 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.GetAllChannelsByTeamId(), and Messenger.Core.Services.MessengerService.logger.
Referenced by Messenger.Helpers.TeamHelpers.TeamBuilder.WithChannels().
GetMessage()
static async Task<Message> Messenger.Core.Services.MessengerService.GetMessage (uint messageId) inline static
Definition at line 100 of file MessengerService.cs.
References Messenger.Core.Services.MessageService.GetMessage(), and Messenger.Core.Services.MessengerService.logger.
GetMessages()
static async Task<IEnumerable<Message> > Messenger.Core.Services.MessengerService.GetMessages (uint channelId) inline static
Gets all messages of the team
Parameters
teamId Id of the team to load messsages from
Returns
List of messages
Definition at line 86 of file MessengerService.cs.
References Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.MessageService.RetrieveMessages().
Referenced by Messenger.Helpers.MessageHelpers.MessageBuilder.GetMessagesFromDatabase().
GetReactions()
static async Task<IEnumerable<Reaction> > Messenger.Core.Services.MessengerService.GetReactions (uint messageId) inline static
Definition at line 229 of file MessengerService.cs.
References Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.MessageService.RetrieveReactions().
Referenced by Messenger.Helpers.MessageHelpers.MessageBuilder.WithReactions().
GetRolesList()
static async Task<IEnumerable<TeamRole> > Messenger.Core.Services.MessengerService.GetRolesList (uint teamId, string userId) inline static
Definition at line 831 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.GetUsersRoles().
GetTeam()
static async Task<Team> Messenger.Core.Services.MessengerService.GetTeam (uint teamId) inline static
Gets the team with the given team id
Parameters
teamId Id of the team to retrieve
Returns
A complete Team object
Definition at line 338 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.GetTeam(), and Messenger.Core.Services.MessengerService.logger.
GetTeamMembers()
static async Task<IEnumerable<User> > Messenger.Core.Services.MessengerService.GetTeamMembers (uint teamId) inline static
Gets all users in current Team
Parameters
teamId Id of the team to load members from
Returns
List of teams
Definition at line 612 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.GetAllMembers(), and Messenger.Core.Services.MessengerService.logger.
Referenced by Messenger.Helpers.TeamHelpers.TeamBuilder.WithMembers().
GetTeams()
static async Task<IEnumerable<Team> > Messenger.Core.Services.MessengerService.GetTeams (string userId) inline static
Gets all teams the current user has membership of
Parameters
userId Current user id
Returns
List of teams
Definition at line 320 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.GetAllTeamsByUserId(), and Messenger.Core.Services.MessengerService.logger.
Referenced by Messenger.Helpers.TeamHelpers.TeamBuilder.GetTeamsFromDatabase().
GetUserWithNameId()
static async Task<User> Messenger.Core.Services.MessengerService.GetUserWithNameId (string username, uint nameId) inline static
Returns a user by username and nameId
Parameters
username DisplayName of the user
nameId NameId of the user
Returns
A complete User object on success, null if the user was not found
Definition at line 632 of file MessengerService.cs.
References Messenger.Core.Services.UserService.GetUser(), and Messenger.Core.Services.MessengerService.logger.
GrantPermission()
static async Task<bool> Messenger.Core.Services.MessengerService.GrantPermission (uint teamId, string role, Permissions permission) inline static
Grant a team's role a specified permissions and notify other clients
Parameters
teamId The id of the team to change permissions in
role The role of the team to grant a permission
permission The permission to grant a team's role
Returns
True on success, false otherwise
Definition at line 1018 of file MessengerService.cs.
References Messenger.Core.Services.SignalRService.AddOrUpdateTeamRole(), Messenger.Core.Services.TeamService.GetRole(), Messenger.Core.Services.TeamService.GrantPermission(), and Messenger.Core.Services.MessengerService.logger.
Referenced by Messenger.Commands.TeamManage.UpdateTeamRoleCommand.Execute().
Initialize()
static async Task<IList<Team> > Messenger.Core.Services.MessengerService.Initialize (string userId, string connectionString = null) inline static
Connects the given user to the teams he is a member of
Parameters
userId The user to connect to his teams
connectionString (optional)connection string to initialize with
Returns
List of teams the user has membership of, null if none exists
REGISTER USER TO SIGNAL-R HUB
LOAD TEAMS
CONNECT TO EACH SIGNAL-R GROUPS
Definition at line 36 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.GetAllTeamsByUserId(), Messenger.Core.Models.Team.Id, Messenger.Core.Services.SignalRService.Initialize(), Messenger.Core.Services.SignalRService.JoinTeam(), Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.SignalRService.OpenConnection().
RemoveMember()
static async Task<bool> Messenger.Core.Services.MessengerService.RemoveMember (string userId, uint teamId) inline static
Removes a user from a specific team
Parameters
userId User id to add
teamId Id of the team to add the user to
Returns
true on success, false on invalid message (error will be handled in each service)
Definition at line 713 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.GetTeam(), Messenger.Core.Services.UserService.GetUser(), Messenger.Core.Services.MessengerService.logger, Messenger.Core.Services.TeamService.RemoveMember(), and Messenger.Core.Services.SignalRService.RemoveMember().
Referenced by Messenger.Commands.TeamManage.RemoveUserCommand.Execute().
RenameChannel()
static async Task<bool> Messenger.Core.Services.MessengerService.RenameChannel (string channelName, uint channelId) inline static
Rename A channel and notify other clients
Parameters
channelId Id of the channel to rename
channelName The new name of the channel
Returns
True if the channel was successfully renamed, false otherwise
Definition at line 567 of file MessengerService.cs.
References Messenger.Core.Services.ChannelService.GetChannel(), Messenger.Core.Services.MessengerService.logger, Messenger.Core.Services.ChannelService.RenameChannel(), and Messenger.Core.Services.SignalRService.UpdateChannel().
RevokePermission()
static async Task<bool> Messenger.Core.Services.MessengerService.RevokePermission (uint teamId, string role, Permissions permission) inline static
Revoke a permission from a specified team's role and notify other clients
Parameters
teamId The id of the team to change permissions in
role The role of the team to revoke a permission from
permission The permission to revoke from a team's role
Returns
True on success, false otherwise
Definition at line 1047 of file MessengerService.cs.
References Messenger.Core.Services.SignalRService.AddOrUpdateTeamRole(), Messenger.Core.Services.TeamService.GetRole(), Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.TeamService.RevokePermission().
Referenced by Messenger.Commands.TeamManage.RevokePermissionCommand.Execute().
SendInvitation()
static async Task<bool> Messenger.Core.Services.MessengerService.SendInvitation (string userId, uint teamId) inline static
Saves new membership to database and add the user to the hub group of the team
Parameters
userId User id to add
teamId Id of the team to add the user to
Returns
true on success, false on invalid message (error will be handled in each service)
Definition at line 652 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.AddMember(), Messenger.Core.Services.TeamService.GetTeam(), Messenger.Core.Services.UserService.GetUser(), Messenger.Core.Services.MessengerService.logger, Messenger.Core.Helpers.NotificationMessageBuilder.MakeInvitedToTeamNotificationMessage(), Messenger.Core.Services.SignalRService.SendInvitation(), Messenger.Core.Services.NotificationService.SendNotification(), and Messenger.Core.Services.SignalRService.SendNotificationToUser().
Referenced by Messenger.Commands.TeamManage.InviteUserCommand.Execute().
SendMessage()
static async Task<bool> Messenger.Core.Services.MessengerService.SendMessage (Message message, uint teamId) inline static
Saves the message to the database and simultaneously broadcasts to the connected Signal-R hub
Parameters
message A complete message object to send
Returns
true on success, false on invalid message (error will be handled in each service)
Definition at line 119 of file MessengerService.cs.
References Messenger.Core.Models.Message.Content, Messenger.Core.Services.MessageService.CreateMessage(), Messenger.Core.Models.Message.Id, Messenger.Core.Services.MessengerService.logger, Messenger.Core.Models.Message.ParentMessageId, Messenger.Core.Models.Message.RecipientId, Messenger.Core.Models.Message.SenderId, Messenger.Core.Services.SignalRService.SendMessage(), Messenger.Core.Services.FileSharingService.Upload(), and Messenger.Core.Models.Message.UploadFileData.
Referenced by Messenger.Commands.Messenger.SendMessageCommand.Execute().
StartChat()
static async Task<uint?> Messenger.Core.Services.MessengerService.StartChat (string userId, string targetUserId) inline static
Start a private chat between two users and notify them
Parameters
userId The first(ego) participant of the chat
targetUserid The second(other) participant of the chat
Returns
The id of the created chat's team on success, null otherwise
Definition at line 1084 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.AddRole(), Messenger.Core.Services.TeamService.AssignRole(), Messenger.Core.Services.ChannelService.CreateChannel(), Messenger.Core.Services.PrivateChatService.CreatePrivateChat(), Messenger.Core.Services.SignalRService.CreateTeam(), Messenger.Core.Services.TeamService.GetTeam(), Messenger.Core.Services.TeamService.GrantPermission(), Messenger.Core.Models.Team.Id, Messenger.Core.Services.SignalRService.JoinTeam(), and Messenger.Core.Services.MessengerService.logger.
Referenced by Messenger.Commands.PrivateChat.StartChatCommand.Execute(), and Messenger.Commands.PrivateChat.StartChatWithUserCommand.Execute().
UnassignUserRole()
static async Task<bool> Messenger.Core.Services.MessengerService.UnassignUserRole (string role, string userId, uint teamId) inline static
Unassign a role from a team's member and notify other clients
Parameters
role The name of the role to unassign from the user
userId The id of the user to unassign the role from
teamId The team to unassign a role from a member in
Returns
True if successful, false otherwise
Definition at line 983 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.GetTeam(), Messenger.Core.Services.UserService.GetUser(), Messenger.Core.Services.MessengerService.logger, Messenger.Core.Services.TeamService.UnAssignRole(), and Messenger.Core.Services.SignalRService.UpdateMember().
Referenced by Messenger.Commands.TeamManage.UnassignTeamRoleCommand.Execute().
UpdateMessage()
static async Task<bool> Messenger.Core.Services.MessengerService.UpdateMessage (uint messageId, string newContent, uint teamId) inline static
Change a messages content and notify other clients
Parameters
messageId Id of the message to edit
newContent New content of the message
Returns
True if the channel was successfully renamed, false otherwise
Definition at line 212 of file MessengerService.cs.
References Messenger.Core.Services.MessageService.EditMessage(), Messenger.Core.Services.MessageService.GetMessage(), Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.SignalRService.UpdateMessage().
Referenced by Messenger.Commands.Messenger.UpdateMessageCommand.Execute().
UpdateTeamDescription()
static async Task<bool> Messenger.Core.Services.MessengerService.UpdateTeamDescription (string teamDescription, uint teamId) inline static
Change a specified team's description and notify other clients
Parameters
teamDescription New description of the team
teamId Id of the team to rename
Returns
True if the team's description was successfully changed, false otherwise
Definition at line 491 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.ChangeTeamDescription(), Messenger.Core.Services.TeamService.GetTeam(), Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.SignalRService.UpdateTeam().
Referenced by Messenger.Commands.TeamManage.UpdateTeamDetailsCommand.Execute().
UpdateTeamName()
static async Task<bool> Messenger.Core.Services.MessengerService.UpdateTeamName (string teamName, uint teamId) inline static
Rename A team and notify other clients
Parameters
teamId Id of the team to rename
teamName The new team name
Returns
True if the team was successfully renamed, false otherwise
Definition at line 434 of file MessengerService.cs.
References Messenger.Core.Services.TeamService.ChangeTeamName(), Messenger.Core.Services.TeamService.GetTeam(), Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.SignalRService.UpdateTeam().
Referenced by Messenger.Commands.TeamManage.UpdateTeamDetailsCommand.Execute().
UpdateTeamRole()
static async Task<bool> Messenger.Core.Services.MessengerService.UpdateTeamRole (uint roleId, string role, string colorCode) inline static
Update team's role with the specified teamId and notify other clients
Parameters
role The name of the role to update
teamId The id of the team the role belongs to
colorCode Hex code of the color used to display the role
Returns
True if successful, false otherwise
Definition at line 880 of file MessengerService.cs.
References Messenger.Core.Services.SignalRService.AddOrUpdateTeamRole(), Messenger.Core.Services.TeamService.GetRole(), Messenger.Core.Services.MessengerService.logger, and Messenger.Core.Services.TeamService.UpdateRole().
Referenced by Messenger.Commands.TeamManage.UpdateTeamRoleCommand.Execute().
UpdateUserBio()
static async Task<bool> Messenger.Core.Services.MessengerService.UpdateUserBio (string userId, string newBio) inline static
Update A user's bio
Parameters
userId Id of the user whos Bio should be updated
newBio The new bio of the user
Returns
True if the bio was successfully updated, false otherwise
Definition at line 792 of file MessengerService.cs.
References Messenger.Core.Services.UserService.GetUser(), Messenger.Core.Services.MessengerService.logger, Messenger.Core.Services.SignalRService.UpdateUser(), and Messenger.Core.Services.UserService.UpdateUserBio().
Referenced by Messenger.Commands.UserData.UpdateUserBioCommand.Execute().
UpdateUserEmail()
static async Task<bool> Messenger.Core.Services.MessengerService.UpdateUserEmail (string userId, string newEmail) inline static
Update A user's email
Parameters
userId Id of the user whos email should be updated
newEmail The new email of the user
Returns
True if the email was successfully updated, false otherwise
Definition at line 746 of file MessengerService.cs.
References Messenger.Core.Services.UserService.GetUser(), Messenger.Core.Services.MessengerService.logger, Messenger.Core.Services.SignalRService.UpdateUser(), and Messenger.Core.Services.UserService.UpdateUserMail().
UpdateUserPhoto()
static async Task<bool> Messenger.Core.Services.MessengerService.UpdateUserPhoto (string userId, string newPhotoURL) inline static
Update A user's Photo
Parameters
userId Id of the user whos photo should be updated
newPhotoURL The new photo of the user
Returns
True if the photo was successfully updated, false otherwise
Definition at line 814 of file MessengerService.cs.
References Messenger.Core.Services.UserService.GetUser(), Messenger.Core.Services.MessengerService.logger, Messenger.Core.Services.SignalRService.UpdateUser(), and Messenger.Core.Services.UserService.UpdateUserPhoto().
UpdateUserUsername()
static async Task<bool> Messenger.Core.Services.MessengerService.UpdateUserUsername (string userId, string newUsername) inline static
Update A user's username
Parameters
userId Id of the user whos username should be updated
newUsername The new username of the user
Returns
True if the username was successfully updated, false otherwise
Definition at line 769 of file MessengerService.cs.
References Messenger.Core.Services.UserService.GetUser(), Messenger.Core.Services.MessengerService.logger, Messenger.Core.Services.SignalRService.UpdateUser(), and Messenger.Core.Services.UserService.UpdateUsername().
Referenced by Messenger.Commands.UserData.UpdateUserNameCommand.Execute().
Property Documentation
logger
ILogger Messenger.Core.Services.MessengerService.logger static get
Definition at line 26 of file MessengerService.cs.
Referenced by Messenger.Core.Services.MessengerService.AssignUserRole(), Messenger.Core.Services.MessengerService.CreateChannel(), Messenger.Core.Services.MessengerService.CreateMessageReaction(), Messenger.Core.Services.MessengerService.CreateTeam(), Messenger.Core.Services.MessengerService.CreateTeamRole(), Messenger.Core.Services.MessengerService.DeleteChannel(), Messenger.Core.Services.MessengerService.DeleteMessage(), Messenger.Core.Services.MessengerService.DeleteMessageReaction(), Messenger.Core.Services.MessengerService.DeleteTeam(), Messenger.Core.Services.MessengerService.DeleteTeamRole(), Messenger.Core.Services.MessengerService.GetChannelsForTeam(), Messenger.Core.Services.MessengerService.GetMessage(), Messenger.Core.Services.MessengerService.GetMessages(), Messenger.Core.Services.MessengerService.GetReactions(), Messenger.Core.Services.MessengerService.GetTeam(), Messenger.Core.Services.MessengerService.GetTeamMembers(), Messenger.Core.Services.MessengerService.GetTeams(), Messenger.Core.Services.MessengerService.GetUserWithNameId(), Messenger.Core.Services.MessengerService.GrantPermission(), Messenger.Core.Services.MessengerService.Initialize(), Messenger.Core.Services.MessengerService.RemoveMember(), Messenger.Core.Services.MessengerService.RenameChannel(), Messenger.Core.Services.MessengerService.RevokePermission(), Messenger.Core.Services.MessengerService.SendInvitation(), Messenger.Core.Services.MessengerService.SendMessage(), Messenger.Core.Services.MessengerService.StartChat(), Messenger.Core.Services.MessengerService.UnassignUserRole(), Messenger.Core.Services.MessengerService.UpdateMessage(), Messenger.Core.Services.MessengerService.UpdateTeamDescription(), Messenger.Core.Services.MessengerService.UpdateTeamName(), Messenger.Core.Services.MessengerService.UpdateTeamRole(), Messenger.Core.Services.MessengerService.UpdateUserBio(), Messenger.Core.Services.MessengerService.UpdateUserEmail(), Messenger.Core.Services.MessengerService.UpdateUserPhoto(), and Messenger.Core.Services.MessengerService.UpdateUserUsername().
SignalRService
SignalRService Messenger.Core.Services.MessengerService.SignalRService static get
The signalRService holding the connection and defined messages to send to the hub
Definition at line 24 of file MessengerService.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger.Core/Services/MessengerService.cs