VPR_Messenger: Messenger.Core.Services.PrivateChatService Class Reference
Messenger.Core.Services.PrivateChatService Class Reference
Holds helpers and static methods to interact with private chats on the DB
Static Public Member Functions
static async Task< uint?> CreatePrivateChat (string myUserId, string otherUserId)
Create a private chat between the users identified by myUserId and otherUserId.
static async Task< IEnumerable< Team > > GetAllPrivateChatsFromUser (string userId)
Lists all private chats of a specified user
static async Task< string > GetPartner (uint teamId)
In a private chat, retrieve the conversation partner's user id
static async Task< uint?> CreateTeam (string teamName, string teamDescription="")
Creates a team with the given name and description and retrieve the new team's id.
static async Task< bool > DeleteTeam (uint teamId)
Deletes a team with a given team id.
static async Task< bool > UpdateTeam (string teamName, string teamDescription, uint teamId)
static async Task< bool > ChangeTeamName (uint teamId, string teamName)
Change the specified teams name
static async Task< bool > ChangeTeamDescription (uint teamId, string description)
Change the specified teams description
static async Task< IEnumerable< Team > > GetAllTeams ()
Gets the list of all existing teams.
static async Task< Team > GetTeam (uint teamId)
Gets the team with the given team id
static async Task< IEnumerable< Team > > GetAllTeamsByUserId (string userId)
Gets the list of teams the user has a membership of.
static async Task< bool > AddMember (string userId, uint teamId)
Adds a new member to the team
static async Task< bool > RemoveMember (string userId, uint teamId)
Removes a member from the team
static async Task< IList< Membership > > GetAllMembershipByUserId (string userId)
Gets all memberships of a user
static async Task< IEnumerable< User > > GetAllMembers (uint teamId)
Retrieve all user who are members of the specified team
static async Task< IList< Channel > > GetAllChannelsByTeamId (uint teamId)
Retrieve all channels of a team
static async Task< uint?> AddRole (string role, uint teamId, string colorCode)
Add a role to a team with the specified teamId
static async Task< bool > UpdateRole (uint roleId, string role, string colorCode)
static async Task< uint?> RemoveRole (string role, uint teamId)
Remove a role from a team's available roles
static async Task< TeamRole > GetRole (uint roleId)
Build a role object from a specified roleId
static async Task< bool > AssignRole (string role, string userId, uint teamId)
Assign a team's member a role
static async Task< bool > UnAssignRole (string role, string userId, uint teamId)
Unassign a team's member a role
static async Task< IList< TeamRole > > ListRoles (uint teamId)
List all roles available in a specified team
static async Task< IList< User > > GetUsersWithRole (uint teamId, string role)
Retrieve a team's users that have a specified role
static async Task< IList< TeamRole > > GetUsersRoles (uint teamId, string userId)
Retrieve a users roles in a specified team
static async Task< uint?> GrantPermission (uint teamId, string role, Permissions permission)
Grant a team's role a specified permissions
static async Task< uint?> RevokePermission (uint teamId, string role, Permissions permission)
Revoke a permission from a specified team's role
static async Task< bool > HasPermission (uint teamId, string role, Permissions permission)
Check if a role has a permission in a team
static async Task< IList< Permissions > > GetPermissionsOfRole (uint teamId, string role)
List all permissions a role has
Detailed Description
Holds helpers and static methods to interact with private chats on the DB
Returns
Definition at line 18 of file PrivateChatService.cs.
Member Function Documentation
AddMember()
static async Task<bool> Messenger.Core.Services.TeamService.AddMember (string userId, uint teamId) inline static inherited
Adds a new member to the team
Parameters
userId The id of the user to add to the specified team
teamId The id of the team to add the specified user to
Returns
True if no exceptions occured while executing the query and it affected at least one entry, false otherwise
Definition at line 273 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.PrivateChatService.CreatePrivateChat(), Messenger.Core.Services.MessengerService.CreateTeam(), and Messenger.Core.Services.MessengerService.SendInvitation().
AddRole()
static async Task<uint?> Messenger.Core.Services.TeamService.AddRole (string role, uint teamId, string colorCode) inline static inherited
Add a role to a team with the specified teamId
Parameters
role The name of the role to add
teamId The id of the team to add the role to
colorCode Hex code of the color
Returns
Id of the added team role
Definition at line 443 of file TeamService.cs.
Referenced by Messenger.Core.Services.MessengerService.CreateTeam(), Messenger.Core.Services.MessengerService.CreateTeamRole(), and Messenger.Core.Services.MessengerService.StartChat().
AssignRole()
static async Task<bool> Messenger.Core.Services.TeamService.AssignRole (string role, string userId, uint teamId) inline static inherited
Assign a team's member a role
Parameters
role The name of the role to assign to the user
userId The id of the user to assign the role to
teamId The team to assign a role to a member in
Returns
True if successful, false otherwise
Definition at line 548 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.AssignUserRole(), Messenger.Core.Services.MessengerService.CreateTeam(), and Messenger.Core.Services.MessengerService.StartChat().
ChangeTeamDescription()
static async Task<bool> Messenger.Core.Services.TeamService.ChangeTeamDescription (uint teamId, string description) inline static inherited
Change the specified teams description
Parameters
teamId Id of the team which's should be changed
description New description of the team
Returns
True, if the teams name was changed, false otherwise
Definition at line 171 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.UpdateTeamDescription().
ChangeTeamName()
static async Task<bool> Messenger.Core.Services.TeamService.ChangeTeamName (uint teamId, string teamName) inline static inherited
Change the specified teams name
Parameters
teamId Id of the team which's should be changed
teamName New name of the team
Returns
True, if the teams name was changed, false otherwise
Definition at line 139 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.UpdateTeamName().
CreatePrivateChat()
static async Task<uint?> Messenger.Core.Services.PrivateChatService.CreatePrivateChat (string myUserId, string otherUserId) inline static
Create a private chat between the users identified by myUserId and otherUserId.
Parameters
myUserId user-Id of the Creator
otherUserId user-Id of the other Person
Returns
The teamId of the created Team
Definition at line 26 of file PrivateChatService.cs.
References Messenger.Core.Services.TeamService.AddMember().
Referenced by Messenger.Core.Services.MessengerService.StartChat().
CreateTeam()
static async Task<uint?> Messenger.Core.Services.TeamService.CreateTeam (string teamName, string teamDescription = "") inline static inherited
Creates a team with the given name and description and retrieve the new team's id.
Parameters
teamName Name of the team
teamDescription Description of the team
Returns
The id of the created team if it was created successfully, null otherwise
Definition at line 26 of file TeamService.cs.
Referenced by Messenger.Core.Services.MessengerService.CreateTeam().
DeleteTeam()
static async Task<bool> Messenger.Core.Services.TeamService.DeleteTeam (uint teamId) inline static inherited
Deletes a team with a given team id.
Parameters
teamId The id of the team to delete
Returns
True if no exceptions occured while executing the query and it affected at least one query, false otherwise
Definition at line 79 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.DeleteTeam().
GetAllChannelsByTeamId()
static async Task<IList<Channel> > Messenger.Core.Services.TeamService.GetAllChannelsByTeamId (uint teamId) inline static inherited
Retrieve all channels of a team
Parameters
teamId The id of the team to retrieve channels from
Returns
A list of channel objects
Definition at line 420 of file TeamService.cs.
References Messenger.Core.Helpers.Mapper.ChannelFromDataRow().
Referenced by Messenger.Core.Services.MessengerService.GetChannelsForTeam().
GetAllMembers()
static async Task<IEnumerable<User> > Messenger.Core.Services.TeamService.GetAllMembers (uint teamId) inline static inherited
Retrieve all user who are members of the specified team
Parameters
teamId The id of a team to retrieve users from
returns>Enumerable of User objects representing the teams members
Definition at line 390 of file TeamService.cs.
References Messenger.Core.Helpers.Mapper.UserFromDataRow().
Referenced by Messenger.Core.Services.MessengerService.GetTeamMembers().
GetAllMembershipByUserId()
static async Task<IList<Membership> > Messenger.Core.Services.TeamService.GetAllMembershipByUserId (string userId) inline static inherited
Gets all memberships of a user
Parameters
userId User id for the current user
Returns
A list of membership objects
Definition at line 367 of file TeamService.cs.
References Messenger.Core.Helpers.Mapper.MembershipFromDataRow().
GetAllPrivateChatsFromUser()
static async Task<IEnumerable<Team> > Messenger.Core.Services.PrivateChatService.GetAllPrivateChatsFromUser (string userId) inline static
Lists all private chats of a specified user
Parameters
userId the id of a user to retrieve private chats of
Returns
An enumerable of Team objects
Definition at line 78 of file PrivateChatService.cs.
References Messenger.Core.Services.TeamService.GetAllTeamsByUserId().
GetAllTeams()
static async Task<IEnumerable<Team> > Messenger.Core.Services.TeamService.GetAllTeams () inline static inherited
Gets the list of all existing teams.
Returns
An enumerable of Team objects
Definition at line 194 of file TeamService.cs.
References Messenger.Core.Helpers.Mapper.TeamFromDataRow().
GetAllTeamsByUserId()
static async Task<IEnumerable<Team> > Messenger.Core.Services.TeamService.GetAllTeamsByUserId (string userId) inline static inherited
Gets the list of teams the user has a membership of.
Parameters
userId The id of the user whose teams to list
Returns
An enumerable of Team objects
Definition at line 243 of file TeamService.cs.
References Messenger.Core.Helpers.Mapper.TeamFromDataRow().
Referenced by Messenger.Core.Services.PrivateChatService.GetAllPrivateChatsFromUser(), Messenger.Core.Services.MessengerService.GetTeams(), and Messenger.Core.Services.MessengerService.Initialize().
GetPartner()
static async Task<string> Messenger.Core.Services.PrivateChatService.GetPartner (uint teamId) inline static
In a private chat, retrieve the conversation partner's user id
Parameters
teamId the id of the team belonging to the private chat
Returns
The user id of the conversation partner
Definition at line 93 of file PrivateChatService.cs.
GetPermissionsOfRole()
static async Task<IList<Permissions> > Messenger.Core.Services.TeamService.GetPermissionsOfRole (uint teamId, string role) inline static inherited
List all permissions a role has
Parameters
teamId The id of the team list permissions of
role The role of the team to list permission of
Returns
A list of Permissions the role has
Definition at line 915 of file TeamService.cs.
Referenced by Messenger.ViewModels.DialogBoxes.ManageMemberRolesDialogViewModel.Initialize(), and Messenger.Helpers.TeamHelpers.TeamBuilder.WithPermissions().
GetRole()
static async Task<TeamRole> Messenger.Core.Services.TeamService.GetRole (uint roleId) inline static inherited
Build a role object from a specified roleId
Parameters
roleId The id of the role to build an object from
Returns
The built role object on success, null otherwise
Definition at line 512 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.GetRows(), and Messenger.Core.Helpers.Mapper.TeamRoleFromDataRow().
Referenced by Messenger.Core.Services.MessengerService.CreateTeamRole(), Messenger.Core.Services.MessengerService.DeleteTeamRole(), Messenger.Core.Services.MessengerService.GrantPermission(), Messenger.Core.Services.MentionService.ResolveMentions(), Messenger.Core.Services.MessengerService.RevokePermission(), and Messenger.Core.Services.MessengerService.UpdateTeamRole().
GetTeam()
static async Task<Team> Messenger.Core.Services.TeamService.GetTeam (uint teamId) inline static inherited
Gets the team with the given team id
Parameters
teamId Id of the team to retrieve
Returns
A complete Team object
Definition at line 216 of file TeamService.cs.
References Messenger.Core.Helpers.Mapper.TeamFromDataRow().
Referenced by Messenger.Core.Services.MessengerService.AssignUserRole(), Messenger.Core.Services.MessengerService.CreateTeam(), Messenger.Core.Services.MessengerService.DeleteTeam(), Messenger.Core.Services.MessengerService.GetTeam(), Messenger.Core.Services.MessengerService.RemoveMember(), Messenger.Core.Services.MessengerService.SendInvitation(), Messenger.Core.Services.MessengerService.StartChat(), Messenger.Core.Services.MessengerService.UnassignUserRole(), Messenger.Core.Services.MessengerService.UpdateTeamDescription(), and Messenger.Core.Services.MessengerService.UpdateTeamName().
GetUsersRoles()
static async Task<IList<TeamRole> > Messenger.Core.Services.TeamService.GetUsersRoles (uint teamId, string userId) inline static inherited
Retrieve a users roles in a specified team
Parameters
teamId The id of the team to retrieve users from
userId The id of the user to retrieve roles from
Returns
The list of role names of the user in the specified team
Definition at line 679 of file TeamService.cs.
References Messenger.Core.Helpers.Mapper.TeamRoleFromDataRow().
Referenced by Messenger.Core.Services.MessengerService.GetRolesList(), and Messenger.Helpers.TeamHelpers.TeamBuilder.WithMemberRoles().
GetUsersWithRole()
static async Task<IList<User> > Messenger.Core.Services.TeamService.GetUsersWithRole (uint teamId, string role) inline static inherited
Retrieve a team's users that have a specified role
Parameters
teamId The id of the team to retrieve users from
role The role of users to retrieve from the team
Returns
A list of user objects belonging to users with the specified role
Definition at line 650 of file TeamService.cs.
References Messenger.Core.Helpers.Mapper.UserFromDataRow().
Referenced by Messenger.Core.Services.MessengerService.DeleteTeamRole().
GrantPermission()
static async Task<uint?> Messenger.Core.Services.TeamService.GrantPermission (uint teamId, string role, Permissions permission) inline static inherited
Grant a team's role a specified permissions
Parameters
teamId The id of the team to change permissions in
role The role of the team to grant a permission
permission The permission to grant a team's role
Returns
True on success, false otherwise
Definition at line 713 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.CreateTeam(), Messenger.Core.Services.MessengerService.GrantPermission(), and Messenger.Core.Services.MessengerService.StartChat().
HasPermission()
static async Task<bool> Messenger.Core.Services.TeamService.HasPermission (uint teamId, string role, Permissions permission) inline static inherited
Check if a role has a permission in a team
Parameters
teamId The id of the team check permissions in
role The role of the team to check permission
permission The permission to check for a team's role
Returns
True if the role has the permission, false otherwise
Definition at line 849 of file TeamService.cs.
ListRoles()
static async Task<IList<TeamRole> > Messenger.Core.Services.TeamService.ListRoles (uint teamId) inline static inherited
List all roles available in a specified team
Parameters
teamId The id of the team to retrieve roles from
Returns
A list of available role names
Definition at line 624 of file TeamService.cs.
References Messenger.Core.Helpers.Mapper.TeamRoleFromDataRow().
Referenced by Messenger.Helpers.TeamHelpers.TeamBuilder.WithMemberRoles(), and Messenger.Helpers.TeamHelpers.TeamBuilder.WithTeamRoles().
RemoveMember()
static async Task<bool> Messenger.Core.Services.TeamService.RemoveMember (string userId, uint teamId) inline static inherited
Removes a member from the team
Parameters
userId The id of the user to remove from the specified team
teamId The id of the team to remove the specified user from
Returns
True if no exceptions occured while executing the query and it affected at least one entry, false otherwise
Definition at line 336 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.RemoveMember().
RemoveRole()
static async Task<uint?> Messenger.Core.Services.TeamService.RemoveRole (string role, uint teamId) inline static inherited
Remove a role from a team's available roles
Parameters
role The name of the role to remove
teamId The id of the team to remove the role from
Returns
True if successful, false otherwise
Definition at line 488 of file TeamService.cs.
Referenced by Messenger.Core.Services.MessengerService.DeleteTeamRole().
RevokePermission()
static async Task<uint?> Messenger.Core.Services.TeamService.RevokePermission (uint teamId, string role, Permissions permission) inline static inherited
Revoke a permission from a specified team's role
Parameters
teamId The id of the team to change permissions in
role The role of the team to revoke a permission from
permission The permission to revoke from a team's role
Returns
True on success, false otherwise
Definition at line 780 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.RevokePermission().
UnAssignRole()
static async Task<bool> Messenger.Core.Services.TeamService.UnAssignRole (string role, string userId, uint teamId) inline static inherited
Unassign a team's member a role
Parameters
role The name of the role to unassign from the user
userId The id of the user to unassign the role from
teamId The team to unassign a role from a member in
Returns
True if successful, false otherwise
Definition at line 588 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.DeleteTeamRole(), and Messenger.Core.Services.MessengerService.UnassignUserRole().
UpdateRole()
static async Task<bool> Messenger.Core.Services.TeamService.UpdateRole (uint roleId, string role, string colorCode) inline static inherited
Definition at line 463 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
Referenced by Messenger.Core.Services.MessengerService.UpdateTeamRole().
UpdateTeam()
static async Task<bool> Messenger.Core.Services.TeamService.UpdateTeam (string teamName, string teamDescription, uint teamId) inline static inherited
Parameters
teamName
teamDescription
teamId
Returns
Definition at line 111 of file TeamService.cs.
References Messenger.Core.Helpers.SqlHelpers.NonQueryAsync().
The documentation for this class was generated from the following file:
Messenger/Messenger.Core/Services/PrivateChatService.cs