VPR_Messenger: Messenger.Services.Providers.EventProvider Class Reference
Messenger.Services.Providers.EventProvider Class Reference
Public Member Functions
EventProvider ()
void Broadcast (BroadcastOptions target, BroadcastReasons reason=BroadcastReasons.Loaded, object parameter=null)
Called to raise events from outside of the provider
Properties
SignalRService SignalRService [get]
ToastNotificationsService Toast [get]
Events
EventHandler< BroadcastArgs > TeamsLoaded
Events with the payload of a list of objects Fires on 'loaded' events including: • Loaded from DB (initialize) • Loaded from cache (switch channel/chats, etc.)
EventHandler< BroadcastArgs > ChatsLoaded
EventHandler< BroadcastArgs > MessagesLoaded
EventHandler< BroadcastArgs > NotificationsLoaded
EventHandler< BroadcastArgs > TeamUpdated
Events with the payload of a single object, mostly fired by Signal-R to trigger data update
EventHandler< BroadcastArgs > ChannelUpdated
EventHandler< BroadcastArgs > PrivateChatUpdated
EventHandler< BroadcastArgs > MessageUpdated
EventHandler< BroadcastArgs > UserUpdated
EventHandler< BroadcastArgs > NotificationReceived
EventHandler< BroadcastArgs > MessagesSwitched
Private Member Functions
void SubscribeEvents ()
void OnReceiveNotification (object sender, SignalREventArgs< Notification > e)
async void OnReceiveMessage (object sender, SignalREventArgs< Message > args)
async void OnMessageUpdated (object sender, SignalREventArgs< Message > args)
void OnMessageDeleted (object sender, SignalREventArgs< Message > args)
async void OnMessageReactionsUpdated (object sender, SignalREventArgs< Message > args)
async void OnReceiveInvitation (object sender, SignalREventArgs< Team > e)
async void OnTeamCreated (object sender, SignalREventArgs< Team > e)
async void OnTeamUpdated (object sender, SignalREventArgs< Team > e)
void OnTeamDeleted (object sender, SignalREventArgs< Team > e)
async void OnTeamRoleUpdated (object sender, SignalREventArgs< TeamRole > e)
void OnTeamRoleDeleted (object sender, SignalREventArgs< TeamRole > e)
async void OnChannelCreated (object sender, SignalREventArgs< Channel > e)
async void OnChannelUpdated (object sender, SignalREventArgs< Channel > e)
void OnChannelDeleted (object sender, SignalREventArgs< Channel > e)
async void OnMemberAdded (object sender, SignalREventArgs< User, Team > e)
async void OnMemberUpdated (object sender, SignalREventArgs< User, Team > e)
void OnMemberRemoved (object sender, SignalREventArgs< User, Team > e)
void OnUserUpdated (object sender, SignalREventArgs< User > e)
void UpdateSelectedTeam (TeamViewModel updatedViewModel)
Detailed Description
Definition at line 13 of file EventProvider.cs.
Constructor & Destructor Documentation
EventProvider()
Messenger.Services.Providers.EventProvider.EventProvider () inline
Definition at line 63 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.SubscribeEvents().
Member Function Documentation
Broadcast()
void Messenger.Services.Providers.EventProvider.Broadcast (BroadcastOptions target, BroadcastReasons reason = BroadcastReasons.Loaded, object parameter = null) inline
Called to raise events from outside of the provider
Parameters
target Target event to raise
reason Reason of the event raise
parameter Parameter to raise the event with
ARGUMENT TO BE PASSED ON
STATIC PAYLOADS FOR LOADED EVENTS
EVENT TRIGGERS
Definition at line 97 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.ChannelUpdated, Messenger.Services.Providers.EventProvider.ChatsLoaded, Messenger.Helpers.CacheQuery.GetMyChats(), Messenger.Helpers.CacheQuery.GetMyTeams(), Messenger.Helpers.CacheQuery.GetNotifications(), Messenger.Services.Providers.EventProvider.MessagesLoaded, Messenger.Services.Providers.EventProvider.MessageUpdated, Messenger.Services.Providers.EventProvider.NotificationReceived, Messenger.Services.Providers.EventProvider.NotificationsLoaded, Messenger.Models.BroadcastArgs.Payload, Messenger.Services.Providers.EventProvider.PrivateChatUpdated, Messenger.Services.Providers.EventProvider.TeamsLoaded, Messenger.Services.Providers.EventProvider.TeamUpdated, and Messenger.Helpers.CacheQuery.TryGetMessages().
Referenced by Messenger.Services.Providers.EventProvider.OnChannelCreated(), Messenger.Services.Providers.EventProvider.OnChannelDeleted(), Messenger.Services.Providers.EventProvider.OnChannelUpdated(), Messenger.Services.Providers.EventProvider.OnMemberAdded(), Messenger.Services.Providers.EventProvider.OnMemberRemoved(), Messenger.Services.Providers.EventProvider.OnMemberUpdated(), Messenger.Services.Providers.EventProvider.OnMessageDeleted(), Messenger.Services.Providers.EventProvider.OnMessageReactionsUpdated(), Messenger.Services.Providers.EventProvider.OnMessageUpdated(), Messenger.Services.Providers.EventProvider.OnReceiveInvitation(), Messenger.Services.Providers.EventProvider.OnReceiveMessage(), Messenger.Services.Providers.EventProvider.OnReceiveNotification(), Messenger.Services.Providers.EventProvider.OnTeamCreated(), Messenger.Services.Providers.EventProvider.OnTeamDeleted(), Messenger.Services.Providers.EventProvider.OnTeamRoleDeleted(), Messenger.Services.Providers.EventProvider.OnTeamRoleUpdated(), Messenger.Services.Providers.EventProvider.OnTeamUpdated(), Messenger.Services.Providers.EventProvider.OnUserUpdated(), and Messenger.Helpers.CacheQuery.Reload().
OnChannelCreated()
async void Messenger.Services.Providers.EventProvider.OnChannelCreated (object sender, SignalREventArgs< Channel > e) inline private
EXIT IF TEAM IS NOT VALID
ADD TO CACHE
TRIGGER CHANNEL UPDATED (UPDATED)
Definition at line 483 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnChannelDeleted()
void Messenger.Services.Providers.EventProvider.OnChannelDeleted (object sender, SignalREventArgs< Channel > e) inline private
EXIT IF TEAM IS NOT VALID
REMOVE FROM CACHE
TRIGGER CHANNEL UPDATED (UPDATED)
Definition at line 533 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnChannelUpdated()
async void Messenger.Services.Providers.EventProvider.OnChannelUpdated (object sender, SignalREventArgs< Channel > e) inline private
EXIT IF TEAM IS NOT VALID
ADD OR UPDATE TO CACHE
UPDATE STATE IF SELECTED
TRIGGER CHANNEL UPDATED (UPDATED)
Definition at line 505 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnMemberAdded()
async void Messenger.Services.Providers.EventProvider.OnMemberAdded (object sender, SignalREventArgs< User, Team > e) inline private
EXIT IF INVITATION IS NOT VALID
TRIGGER TEAM UPDATED (UPDATED)
Definition at line 559 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.FirstValue, Messenger.Core.Models.Team.Id, Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.SecondValue, and Messenger.Services.Providers.EventProvider.UpdateSelectedTeam().
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnMemberRemoved()
void Messenger.Services.Providers.EventProvider.OnMemberRemoved (object sender, SignalREventArgs< User, Team > e) inline private
EXIT IF INVITATION IS NOT VALID
TRIGGER TEAM UPDATED (UPDATED)
Definition at line 611 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.FirstValue, Messenger.Core.Models.Team.Id, Messenger.Core.Models.User.Id, Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.SecondValue, and Messenger.Services.Providers.EventProvider.UpdateSelectedTeam().
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnMemberUpdated()
async void Messenger.Services.Providers.EventProvider.OnMemberUpdated (object sender, SignalREventArgs< User, Team > e) inline private
EXIT IF INVITATION IS NOT VALID
TRIGGER TEAM UPDATED (UPDATED)
Definition at line 585 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.FirstValue, Messenger.Core.Models.Team.Id, Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.SecondValue, and Messenger.Services.Providers.EventProvider.UpdateSelectedTeam().
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnMessageDeleted()
void Messenger.Services.Providers.EventProvider.OnMessageDeleted (object sender, SignalREventArgs< Message > args) inline private
EXIT IF MESSAGE IS NOT VALID
REMOVE FROM CACHE
TRIGGER MESSAGE UPDATED (DELETED)
Definition at line 255 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnMessageReactionsUpdated()
async void Messenger.Services.Providers.EventProvider.OnMessageReactionsUpdated (object sender, SignalREventArgs< Message > args) inline private
RELOAD FROM DB
TRIGGER MESSAGE UPDATED (DELETED)
Definition at line 277 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnMessageUpdated()
async void Messenger.Services.Providers.EventProvider.OnMessageUpdated (object sender, SignalREventArgs< Message > args) inline private
EXIT IF MESSAGE IS NOT VALID
UPDATE IN CACHE
TRIGGER MESSAGE UPDATED (UPDATED)
Definition at line 233 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnReceiveInvitation()
async void Messenger.Services.Providers.EventProvider.OnReceiveInvitation (object sender, SignalREventArgs< Team > e) inline private
Definition at line 302 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Core.Models.Team.Name, Messenger.Services.Providers.EventProvider.Toast, and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnReceiveMessage()
async void Messenger.Services.Providers.EventProvider.OnReceiveMessage (object sender, SignalREventArgs< Message > args) inline private
EXIT IF MESSAGE IS NOT VALID
ADD TO CACHE
SEND TOAST IF CHANNEL CURRENTLY NOT SELECTED
TRIGGER MESSAGE UPDATED (CREATED)
Definition at line 204 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Core.Models.Message.RecipientId, Messenger.Services.Providers.EventProvider.Toast, and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnReceiveNotification()
void Messenger.Services.Providers.EventProvider.OnReceiveNotification (object sender, SignalREventArgs< Notification > e) inline private
Definition at line 182 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnTeamCreated()
async void Messenger.Services.Providers.EventProvider.OnTeamCreated (object sender, SignalREventArgs< Team > e) inline private
Definition at line 337 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Core.Models.Team.Name, and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnTeamDeleted()
void Messenger.Services.Providers.EventProvider.OnTeamDeleted (object sender, SignalREventArgs< Team > e) inline private
Definition at line 404 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Core.Models.Team.Id, Messenger.Core.Models.Team.Name, and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnTeamRoleDeleted()
void Messenger.Services.Providers.EventProvider.OnTeamRoleDeleted (object sender, SignalREventArgs< TeamRole > e) inline private
Definition at line 459 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Core.Models.TeamRole.Id, Messenger.ViewModels.DataViewModels.TeamRoleViewModel.TeamId, Messenger.Services.Providers.EventProvider.UpdateSelectedTeam(), and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnTeamRoleUpdated()
async void Messenger.Services.Providers.EventProvider.OnTeamRoleUpdated (object sender, SignalREventArgs< TeamRole > e) inline private
Definition at line 439 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.ViewModels.DataViewModels.TeamRoleViewModel.TeamId, Messenger.Services.Providers.EventProvider.UpdateSelectedTeam(), and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnTeamUpdated()
async void Messenger.Services.Providers.EventProvider.OnTeamUpdated (object sender, SignalREventArgs< Team > e) inline private
ADD PRIVATE CHAT TO CACHE
ADD TEAM TO CACHE
Definition at line 365 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), Messenger.Core.Models.Team.Name, Messenger.Services.Providers.EventProvider.UpdateSelectedTeam(), and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
OnUserUpdated()
void Messenger.Services.Providers.EventProvider.OnUserUpdated (object sender, SignalREventArgs< User > e) inline private
Definition at line 641 of file EventProvider.cs.
References Messenger.Services.Providers.EventProvider.Broadcast(), and Messenger.Core.Models.SignalREventArgs< TOne, TTwo >.Value.
Referenced by Messenger.Services.Providers.EventProvider.SubscribeEvents().
SubscribeEvents()
void Messenger.Services.Providers.EventProvider.SubscribeEvents () inline private
Definition at line 68 of file EventProvider.cs.
References Messenger.Core.Services.SignalRService.ChannelCreated, Messenger.Core.Services.SignalRService.ChannelDeleted, Messenger.Core.Services.SignalRService.ChannelUpdated, Messenger.Core.Services.SignalRService.MemberAdded, Messenger.Core.Services.SignalRService.MemberRemoved, Messenger.Core.Services.SignalRService.MemberUpdated, Messenger.Core.Services.SignalRService.MessageDeleted, Messenger.Core.Services.SignalRService.MessageReactionsUpdated, Messenger.Core.Services.SignalRService.MessageUpdated, Messenger.Services.Providers.EventProvider.OnChannelCreated(), Messenger.Services.Providers.EventProvider.OnChannelDeleted(), Messenger.Services.Providers.EventProvider.OnChannelUpdated(), Messenger.Services.Providers.EventProvider.OnMemberAdded(), Messenger.Services.Providers.EventProvider.OnMemberRemoved(), Messenger.Services.Providers.EventProvider.OnMemberUpdated(), Messenger.Services.Providers.EventProvider.OnMessageDeleted(), Messenger.Services.Providers.EventProvider.OnMessageReactionsUpdated(), Messenger.Services.Providers.EventProvider.OnMessageUpdated(), Messenger.Services.Providers.EventProvider.OnReceiveInvitation(), Messenger.Services.Providers.EventProvider.OnReceiveMessage(), Messenger.Services.Providers.EventProvider.OnReceiveNotification(), Messenger.Services.Providers.EventProvider.OnTeamCreated(), Messenger.Services.Providers.EventProvider.OnTeamDeleted(), Messenger.Services.Providers.EventProvider.OnTeamRoleDeleted(), Messenger.Services.Providers.EventProvider.OnTeamRoleUpdated(), Messenger.Services.Providers.EventProvider.OnTeamUpdated(), Messenger.Services.Providers.EventProvider.OnUserUpdated(), Messenger.Core.Services.SignalRService.ReceiveInvitation, Messenger.Core.Services.SignalRService.ReceiveMessage, Messenger.Core.Services.SignalRService.ReceiveNotification, Messenger.Core.Services.SignalRService.TeamCreated, Messenger.Core.Services.SignalRService.TeamDeleted, Messenger.Core.Services.SignalRService.TeamRoleDeleted, Messenger.Core.Services.SignalRService.TeamRoleUpdated, Messenger.Core.Services.SignalRService.TeamUpdated, and Messenger.Core.Services.SignalRService.UserUpdated.
Referenced by Messenger.Services.Providers.EventProvider.EventProvider().
UpdateSelectedTeam()
void Messenger.Services.Providers.EventProvider.UpdateSelectedTeam (TeamViewModel updatedViewModel) inline private
Definition at line 659 of file EventProvider.cs.
References Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, Messenger.ViewModels.DataViewModels.TeamViewModel.Channels, and Messenger.ViewModels.DataViewModels.TeamViewModel.Id.
Referenced by Messenger.Services.Providers.EventProvider.OnMemberAdded(), Messenger.Services.Providers.EventProvider.OnMemberRemoved(), Messenger.Services.Providers.EventProvider.OnMemberUpdated(), Messenger.Services.Providers.EventProvider.OnTeamRoleDeleted(), Messenger.Services.Providers.EventProvider.OnTeamRoleUpdated(), and Messenger.Services.Providers.EventProvider.OnTeamUpdated().
Property Documentation
SignalRService
SignalRService Messenger.Services.Providers.EventProvider.SignalRService get private
Definition at line 15 of file EventProvider.cs.
Toast
ToastNotificationsService Messenger.Services.Providers.EventProvider.Toast get private
Definition at line 17 of file EventProvider.cs.
Referenced by Messenger.Services.Providers.EventProvider.OnReceiveInvitation(), and Messenger.Services.Providers.EventProvider.OnReceiveMessage().
Event Documentation
ChannelUpdated
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.ChannelUpdated
Definition at line 45 of file EventProvider.cs.
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
ChatsLoaded
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.ChatsLoaded
Definition at line 29 of file EventProvider.cs.
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
MessagesLoaded
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.MessagesLoaded
Definition at line 31 of file EventProvider.cs.
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
MessagesSwitched
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.MessagesSwitched
Definition at line 59 of file EventProvider.cs.
MessageUpdated
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.MessageUpdated
Definition at line 49 of file EventProvider.cs.
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
NotificationReceived
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.NotificationReceived
Definition at line 53 of file EventProvider.cs.
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
NotificationsLoaded
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.NotificationsLoaded
Definition at line 33 of file EventProvider.cs.
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
PrivateChatUpdated
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.PrivateChatUpdated
Definition at line 47 of file EventProvider.cs.
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
TeamsLoaded
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.TeamsLoaded
Events with the payload of a list of objects Fires on 'loaded' events including: • Loaded from DB (initialize) • Loaded from cache (switch channel/chats, etc.)
Definition at line 27 of file EventProvider.cs.
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
TeamUpdated
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.TeamUpdated
Events with the payload of a single object, mostly fired by Signal-R to trigger data update
Definition at line 43 of file EventProvider.cs.
Referenced by Messenger.Services.Providers.EventProvider.Broadcast().
UserUpdated
EventHandler<BroadcastArgs> Messenger.Services.Providers.EventProvider.UserUpdated
Definition at line 51 of file EventProvider.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/Services/Providers/EventProvider.cs