VPR_Messenger: Messenger.ViewModels.Pages.LogInViewModel Class Reference
Messenger.ViewModels.Pages.LogInViewModel Class Reference
Public Member Functions
LogInViewModel ()
Protected Member Functions
void Set< T > (ref T storage, T value, [CallerMemberName]string propertyName=null)
void OnPropertyChanged (string propertyName)
Properties
IdentityService IdentityService [get]
string StatusMessage [get, set]
bool IsBusy [get, set]
RelayCommand LoginCommand [get]
Events
PropertyChangedEventHandler PropertyChanged
Private Member Functions
async void OnLogin ()
string GetStatusMessage (LoginResultType loginResult)
Private Attributes
string _statusMessage
bool _isBusy
RelayCommand _loginCommand
Detailed Description
Definition at line 9 of file LogInViewModel.cs.
Constructor & Destructor Documentation
LogInViewModel()
Messenger.ViewModels.Pages.LogInViewModel.LogInViewModel () inline
Definition at line 35 of file LogInViewModel.cs.
References Messenger.ViewModels.Pages.LogInViewModel.OnLogin().
Member Function Documentation
GetStatusMessage()
string Messenger.ViewModels.Pages.LogInViewModel.GetStatusMessage (LoginResultType loginResult) inline private
Definition at line 49 of file LogInViewModel.cs.
Referenced by Messenger.ViewModels.Pages.LogInViewModel.OnLogin().
OnLogin()
async void Messenger.ViewModels.Pages.LogInViewModel.OnLogin () inline private
Definition at line 40 of file LogInViewModel.cs.
References Messenger.ViewModels.Pages.LogInViewModel.GetStatusMessage(), Messenger.ViewModels.Pages.LogInViewModel.IsBusy, Messenger.Core.Services.IdentityService.LoginAsync(), and Messenger.ViewModels.Pages.LogInViewModel.StatusMessage.
Referenced by Messenger.ViewModels.Pages.LogInViewModel.LogInViewModel().
OnPropertyChanged()
void Messenger.Helpers.Observable.OnPropertyChanged (string propertyName) protected inherited
Referenced by Messenger.Helpers.Observable.Set< T >().
Set< T >()
void Messenger.Helpers.Observable.Set< T > (ref T storage, T value, [CallerMemberName] string propertyName = null) inline protected inherited
Definition at line 11 of file Observable.cs.
References Messenger.Helpers.Observable.OnPropertyChanged().
Member Data Documentation
_isBusy
bool Messenger.ViewModels.Pages.LogInViewModel._isBusy private
Definition at line 12 of file LogInViewModel.cs.
_loginCommand
RelayCommand Messenger.ViewModels.Pages.LogInViewModel._loginCommand private
Definition at line 13 of file LogInViewModel.cs.
_statusMessage
string Messenger.ViewModels.Pages.LogInViewModel._statusMessage private
Definition at line 11 of file LogInViewModel.cs.
Property Documentation
IdentityService
IdentityService Messenger.ViewModels.Pages.LogInViewModel.IdentityService get private
Definition at line 15 of file LogInViewModel.cs.
IsBusy
bool Messenger.ViewModels.Pages.LogInViewModel.IsBusy get set
Definition at line 23 of file LogInViewModel.cs.
Referenced by Messenger.ViewModels.Pages.LogInViewModel.OnLogin().
LoginCommand
RelayCommand Messenger.ViewModels.Pages.LogInViewModel.LoginCommand get
Definition at line 33 of file LogInViewModel.cs.
StatusMessage
string Messenger.ViewModels.Pages.LogInViewModel.StatusMessage get set
Definition at line 17 of file LogInViewModel.cs.
Referenced by Messenger.ViewModels.Pages.LogInViewModel.OnLogin().
Event Documentation
PropertyChanged
PropertyChangedEventHandler Messenger.Helpers.Observable.PropertyChanged inherited
Definition at line 9 of file Observable.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/ViewModels/Pages/LogInViewModel.cs