VPR_Messenger: Messenger.Core.Helpers.SqlHelpers Class Reference
Messenger.Core.Helpers.SqlHelpers Class Reference
Holds static methods for common sql operations
Static Public Member Functions
static async Task< bool > NonQueryAsync (string query)
Run the specified query on the specified connection.
static async Task< T > ExecuteScalarAsync< T > (string query, Func< object, T > converter)
Run the specified query on the specified connection and retrieve a converterd scalar value.
static async Task< string > GetColumnType (string tableName, string columnName)
Return a string representing the SQL datatype of the specified column in the specified table.
static async Task< IEnumerable< DataRow > > GetRows (string tableName, string query)
Return an enumerable of data rows
static async Task< IList< T > > MapToList< T > (Func< DataRow, T > mapper, string query, string tableName="")
Maps to a list of target type instances
static async Task< IList< T > > MapToList< T > (Func< DataRow, string, T > mapper, string query, string tableName, string columnName)
Maps to a list of target type instances
static dynamic TryConvertDbValue< T > (object value, Func< object, T > converter)
Convert a value that can be DBNull using a specified converter
Detailed Description
Holds static methods for common sql operations
Definition at line 17 of file SqlHelpers.cs.
Member Function Documentation
ExecuteScalarAsync< T >()
static async Task<T> Messenger.Core.Helpers.SqlHelpers.ExecuteScalarAsync< T > (string query, Func< object, T > converter) inline static
Run the specified query on the specified connection and retrieve a converterd scalar value.
Template Parameters
T The type to map to
Parameters
query A query to run
connection An sql connection to run the query on
Returns
The converted scalar result on success, The default value of T on Failure
Type Constraints
T : IConvertible
Definition at line 64 of file SqlHelpers.cs.
GetColumnType()
static async Task<string> Messenger.Core.Helpers.SqlHelpers.GetColumnType (string tableName, string columnName) inline static
Return a string representing the SQL datatype of the specified column in the specified table.
Parameters
tableName A table to check a columns type of
columnName A column to check the type of
connection An sql connection to run the query on
Returns
Null if the specifid column does not exist in the table, it's type name otherwise
Definition at line 103 of file SqlHelpers.cs.
Referenced by Messenger.Core.Services.UserService.Update().
GetRows()
static async Task<IEnumerable<DataRow> > Messenger.Core.Helpers.SqlHelpers.GetRows (string tableName, string query) inline static
Return an enumerable of data rows
Parameters
tableName Name of the table to read from
query The query that returns the data rows
Returns
An enumerable of data rows
Definition at line 140 of file SqlHelpers.cs.
Referenced by Messenger.Core.Services.ChannelService.GetChannel(), Messenger.Core.Services.MessageService.GetMessage(), Messenger.Core.Services.UserService.GetOrCreateApplicationUser(), Messenger.Core.Services.TeamService.GetRole(), Messenger.Core.Services.UserService.GetUser(), Messenger.Core.Services.MentionService.RetrieveMention(), and Messenger.Core.Services.UserService.SearchUser().
MapToList< T >() [1/2]
static async Task<IList<T> > Messenger.Core.Helpers.SqlHelpers.MapToList< T > (Func< DataRow, string, T > mapper, string query, string tableName, string columnName) inline static
Maps to a list of target type instances
Infers the table name from the mapping type if tableName is not specified
Template Parameters
T The type to map to
Parameters
mapper Mapper function for the target type
query The query that returns the list
tableName The name of the table to retrieve data from, defaults to null
columnName The name of the column to retrieve data from, defaults to null
Returns
A list of converted table values
Definition at line 221 of file SqlHelpers.cs.
MapToList< T >() [2/2]
static async Task<IList<T> > Messenger.Core.Helpers.SqlHelpers.MapToList< T > (Func< DataRow, T > mapper, string query, string tableName = "") inline static
Maps to a list of target type instances
Infers the table name from the mapping type if tableName is not specified
Template Parameters
T The type to map to
Parameters
mapper Mapper function for the target type
query The query that returns the list
Returns
A list of converted table values
Definition at line 174 of file SqlHelpers.cs.
NonQueryAsync()
static async Task<bool> Messenger.Core.Helpers.SqlHelpers.NonQueryAsync (string query) inline static
Run the specified query on the specified connection.
Parameters
query A query to run
connection An sql connection to run the query on
Returns
True if no exceptions occured while executing the query and it affected at least one entry, false otherwise
Definition at line 25 of file SqlHelpers.cs.
Referenced by Messenger.Core.Services.TeamService.AddMember(), Messenger.Core.Services.TeamService.AssignRole(), Messenger.Core.Services.TeamService.ChangeTeamDescription(), Messenger.Core.Services.TeamService.ChangeTeamName(), Messenger.Core.Services.MessageService.DeleteMessage(), Messenger.Core.Services.TeamService.DeleteTeam(), Messenger.Core.Services.UserService.DeleteUser(), Messenger.Core.Services.MessageService.EditMessage(), Messenger.Core.Services.UserService.GetOrCreateApplicationUser(), Messenger.Core.Services.TeamService.GrantPermission(), Messenger.Core.Services.ChannelService.PinMessage(), Messenger.Core.Services.ChannelService.RemoveAllChannels(), Messenger.Core.Services.ChannelService.RemoveChannel(), Messenger.Core.Services.TeamService.RemoveMember(), Messenger.Core.Services.MentionService.RemoveMention(), Messenger.Core.Services.NotificationService.RemoveMute(), Messenger.Core.Services.NotificationService.RemoveNotification(), Messenger.Core.Services.MessageService.RemoveReaction(), Messenger.Core.Services.ChannelService.RenameChannel(), Messenger.Core.Services.TeamService.RevokePermission(), Messenger.Core.Services.TeamService.UnAssignRole(), Messenger.Core.Services.ChannelService.UnPinMessage(), Messenger.Core.Services.UserService.Update(), Messenger.Core.Services.TeamService.UpdateRole(), Messenger.Core.Services.TeamService.UpdateTeam(), Messenger.Core.Services.UserService.UpdateUserBio(), Messenger.Core.Services.UserService.UpdateUserMail(), Messenger.Core.Services.UserService.UpdateUsername(), and Messenger.Core.Services.UserService.UpdateUserPhoto().
TryConvertDbValue< T >()
static dynamic Messenger.Core.Helpers.SqlHelpers.TryConvertDbValue< T > (object value, Func< object, T > converter) inline static
Convert a value that can be DBNull using a specified converter
Parameters
value A value to convert to T
converter A converter function to use for converting value
Returns
a value of dynamic type(T or null)
Definition at line 264 of file SqlHelpers.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger.Core/Helpers/SqlHelpers.cs