VPR_Messenger: Messenger.ViewModels.Pages.ChatNavViewModel Class Reference
Messenger.ViewModels.Pages.ChatNavViewModel Class Reference
Public Member Functions
ChatNavViewModel ()
void OnChatsLoaded (object sender, BroadcastArgs e)
Fired by EventProvider on ChatsLoaded
void OnChatUpdated (object sender, BroadcastArgs e)
Fired by EventProvider on PrivateChatUpdated
void OnMessageUpdated (object sender, BroadcastArgs e)
Fired by EventProvider on MessageUpdated(for LastMessage)
Properties
ObservableCollection< PrivateChatViewModel > Chats [get, set]
Loaded chats list of the current user
bool IsBusy [get, set]
Shows loading spinner on true
UserViewModel CurrentUser [get, set]
Currently logged-in user
ICommand SwitchChatCommand [get]
Switches to another private chat
ICommand StartChatCommand [get]
Opens a start chat dialog to create a new private chat
ICommand ReloadCommand [get]
Manually reloads all chats and messages
Additional Inherited Members
Protected Member Functions inherited from Messenger.Helpers.Observable
void Set< T > (ref T storage, T value, [CallerMemberName]string propertyName=null)
void OnPropertyChanged (string propertyName)
Events inherited from Messenger.Helpers.Observable
PropertyChangedEventHandler PropertyChanged
Detailed Description
Definition at line 18 of file ChatNavViewModel.cs.
Constructor & Destructor Documentation
ChatNavViewModel()
Messenger.ViewModels.Pages.ChatNavViewModel.ChatNavViewModel () inline
Definition at line 88 of file ChatNavViewModel.cs.
References Messenger.ViewModels.Pages.ChatNavViewModel.OnChatsLoaded(), Messenger.ViewModels.Pages.ChatNavViewModel.OnChatUpdated(), and Messenger.ViewModels.Pages.ChatNavViewModel.OnMessageUpdated().
Member Function Documentation
OnChatsLoaded()
void Messenger.ViewModels.Pages.ChatNavViewModel.OnChatsLoaded (object sender, BroadcastArgs e) inline
Fired by EventProvider on ChatsLoaded
Definition at line 149 of file ChatNavViewModel.cs.
References Messenger.ViewModels.Pages.ChatNavViewModel.Chats, Messenger.ViewModels.Pages.ChatNavViewModel.IsBusy, and Messenger.Models.BroadcastArgs.Payload.
Referenced by Messenger.ViewModels.Pages.ChatNavViewModel.ChatNavViewModel().
OnChatUpdated()
void Messenger.ViewModels.Pages.ChatNavViewModel.OnChatUpdated (object sender, BroadcastArgs e) inline
Fired by EventProvider on PrivateChatUpdated
Definition at line 170 of file ChatNavViewModel.cs.
References Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Models.BroadcastArgs.Payload, and Messenger.Models.BroadcastArgs.Reason.
Referenced by Messenger.ViewModels.Pages.ChatNavViewModel.ChatNavViewModel().
OnMessageUpdated()
void Messenger.ViewModels.Pages.ChatNavViewModel.OnMessageUpdated (object sender, BroadcastArgs e) inline
Fired by EventProvider on MessageUpdated(for LastMessage)
Definition at line 204 of file ChatNavViewModel.cs.
References Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, Messenger.ViewModels.DataViewModels.PrivateChatViewModel.LastMessage, Messenger.ViewModels.DataViewModels.PrivateChatViewModel.MainChannel, Messenger.Models.BroadcastArgs.Payload, and Messenger.Models.BroadcastArgs.Reason.
Referenced by Messenger.ViewModels.Pages.ChatNavViewModel.ChatNavViewModel().
Property Documentation
Chats
ObservableCollection<PrivateChatViewModel> Messenger.ViewModels.Pages.ChatNavViewModel.Chats get set
Loaded chats list of the current user
Definition at line 35 of file ChatNavViewModel.cs.
Referenced by Messenger.ViewModels.Pages.ChatNavViewModel.OnChatsLoaded().
CurrentUser
UserViewModel Messenger.ViewModels.Pages.ChatNavViewModel.CurrentUser get set
Currently logged-in user
Definition at line 65 of file ChatNavViewModel.cs.
IsBusy
bool Messenger.ViewModels.Pages.ChatNavViewModel.IsBusy get set
Shows loading spinner on true
Definition at line 50 of file ChatNavViewModel.cs.
Referenced by Messenger.ViewModels.Pages.ChatNavViewModel.OnChatsLoaded().
ReloadCommand
ICommand Messenger.ViewModels.Pages.ChatNavViewModel.ReloadCommand get
Manually reloads all chats and messages
Definition at line 84 of file ChatNavViewModel.cs.
StartChatCommand
ICommand Messenger.ViewModels.Pages.ChatNavViewModel.StartChatCommand get
Opens a start chat dialog to create a new private chat
Definition at line 79 of file ChatNavViewModel.cs.
SwitchChatCommand
ICommand Messenger.ViewModels.Pages.ChatNavViewModel.SwitchChatCommand get
Switches to another private chat
Definition at line 74 of file ChatNavViewModel.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/ViewModels/Pages/ChatNavViewModel.cs