VPR_Messenger: Messenger.Core.Helpers.Mapper Class Reference
Messenger.Core.Helpers.Mapper Class Reference
Holds static methods to convert (mostly) from data rows to other types or classes
Static Public Member Functions
static User UserFromDataRow (DataRow row)
Maps to a full user model from the data rows
static User UserFromMSGraph (User userdata)
Maps to a user model with minimal information from the MS-Graph service
static Team TeamFromDataRow (DataRow row)
Maps to a full team model from the data rows
static Message MessageFromDataRow (DataRow row)
Maps to a full message model from the data rows
static Membership MembershipFromDataRow (DataRow row)
Maps to a full membership model from the data rows
static Channel ChannelFromDataRow (DataRow row)
Maps to a full Channel model from the data rows
static Reaction ReactionFromDataRow (DataRow row)
Maps to a full Reaction model from the data rows
static Notification NotificationFromDataRow (DataRow row)
Maps to a full Notification model from the data rows
static Mention MentionFromDataRow (DataRow row)
Maps to a full Mention model from the data rows
static Mentionable MentionableFromDataRow (DataRow row)
Maps to a full Mentionable model from the data rows
static T StringToEnum< T > (object value)
static TeamRole TeamRoleFromDataRow (DataRow row)
Maps to a full TeamRole model from the data rows
static NotificationMute NotificationMuteFromDataRow (DataRow row)
Maps to a full NotificationMute model from the data rows
static string StringFromDataRow (DataRow row, string columnName)
Convert a DataRows column to a string
static JObject strToJObject (object str)
Parse a json encoded string to a JObject
static T EnumFromDataRow< T > (DataRow row, string columnName)
Convert a specified column of a dataRow to an enum
Properties
static ILogger logger [get]
Detailed Description
Holds static methods to convert (mostly) from data rows to other types or classes
Definition at line 17 of file Mapper.cs.
Member Function Documentation
ChannelFromDataRow()
static Channel Messenger.Core.Helpers.Mapper.ChannelFromDataRow (DataRow row) inline static
Maps to a full Channel model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully-mapped Channel object
Definition at line 119 of file Mapper.cs.
Referenced by Messenger.Core.Services.TeamService.GetAllChannelsByTeamId(), and Messenger.Core.Services.ChannelService.GetChannel().
EnumFromDataRow< T >()
static T Messenger.Core.Helpers.Mapper.EnumFromDataRow< T > (DataRow row, string columnName) inline static
Convert a specified column of a dataRow to an enum
Template Parameters
T The type of the enum to convert to
Parameters
row DataRow to convert
columnName Column of the row to convert
Returns
The value of columnName of row as an enum
Type Constraints
T : Enum
Definition at line 257 of file Mapper.cs.
MembershipFromDataRow()
static Membership Messenger.Core.Helpers.Mapper.MembershipFromDataRow (DataRow row) inline static
Maps to a full membership model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully-mapped membership object
Definition at line 103 of file Mapper.cs.
Referenced by Messenger.Core.Services.TeamService.GetAllMembershipByUserId().
MentionableFromDataRow()
static Mentionable Messenger.Core.Helpers.Mapper.MentionableFromDataRow (DataRow row) inline static
Maps to a full Mentionable model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully mapped Mentionable object
Definition at line 180 of file Mapper.cs.
MentionFromDataRow()
static Mention Messenger.Core.Helpers.Mapper.MentionFromDataRow (DataRow row) inline static
Maps to a full Mention model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully mapped Mention object
Definition at line 165 of file Mapper.cs.
Referenced by Messenger.Core.Services.MentionService.RetrieveMention().
MessageFromDataRow()
static Message Messenger.Core.Helpers.Mapper.MessageFromDataRow (DataRow row) inline static
Maps to a full message model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully-mapped message object
Definition at line 77 of file Mapper.cs.
Referenced by Messenger.Core.Services.MessageService.GetMessage(), Messenger.Core.Services.MessageService.RetrieveMessages(), Messenger.Core.Services.ChannelService.RetrievePinnedMessages(), and Messenger.Core.Services.MessageService.RetrieveReplies().
NotificationFromDataRow()
static Notification Messenger.Core.Helpers.Mapper.NotificationFromDataRow (DataRow row) inline static
Maps to a full Notification model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully mapped Notification object
Definition at line 149 of file Mapper.cs.
References Messenger.Core.Helpers.Mapper.strToJObject().
Referenced by Messenger.Core.Services.NotificationService.RetrieveNotifications().
NotificationMuteFromDataRow()
static NotificationMute Messenger.Core.Helpers.Mapper.NotificationMuteFromDataRow (DataRow row) inline static
Maps to a full NotificationMute model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully mapped NotificationMute object
Definition at line 216 of file Mapper.cs.
Referenced by Messenger.Core.Services.NotificationService.GetUsersMutes().
ReactionFromDataRow()
static Reaction Messenger.Core.Helpers.Mapper.ReactionFromDataRow (DataRow row) inline static
Maps to a full Reaction model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully mapped Reaction object
Definition at line 133 of file Mapper.cs.
Referenced by Messenger.Core.Services.MessageService.GetReaction(), and Messenger.Core.Services.MessageService.RetrieveReactions().
StringFromDataRow()
static string Messenger.Core.Helpers.Mapper.StringFromDataRow (DataRow row, string columnName) inline static
Convert a DataRows column to a string
Parameters
row the row to convert
columnName The column of the row to convert
Returns
A string representation of the selected column
Definition at line 235 of file Mapper.cs.
StringToEnum< T >()
static T Messenger.Core.Helpers.Mapper.StringToEnum< T > (object value) inline static
Definition at line 190 of file Mapper.cs.
strToJObject()
static JObject Messenger.Core.Helpers.Mapper.strToJObject (object str) inline static
Parse a json encoded string to a JObject
Parameters
str The json encoded string to convert
Returns
A JObject representing the input
Definition at line 245 of file Mapper.cs.
Referenced by Messenger.Core.Helpers.Mapper.NotificationFromDataRow().
TeamFromDataRow()
static Team Messenger.Core.Helpers.Mapper.TeamFromDataRow (DataRow row) inline static
Maps to a full team model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully-mapped team object
Definition at line 61 of file Mapper.cs.
Referenced by Messenger.Core.Services.TeamService.GetAllTeams(), Messenger.Core.Services.TeamService.GetAllTeamsByUserId(), and Messenger.Core.Services.TeamService.GetTeam().
TeamRoleFromDataRow()
static TeamRole Messenger.Core.Helpers.Mapper.TeamRoleFromDataRow (DataRow row) inline static
Maps to a full TeamRole model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully mapped TeamRole object
Definition at line 200 of file Mapper.cs.
References Messenger.Core.Models.Role.
Referenced by Messenger.Core.Services.TeamService.GetRole(), Messenger.Core.Services.TeamService.GetUsersRoles(), and Messenger.Core.Services.TeamService.ListRoles().
UserFromDataRow()
static User Messenger.Core.Helpers.Mapper.UserFromDataRow (DataRow row) inline static
Maps to a full user model from the data rows
Parameters
row DataRow from the DataSet
Returns
A fully-mapped user object
Definition at line 25 of file Mapper.cs.
Referenced by Messenger.Core.Services.TeamService.GetAllMembers(), Messenger.Core.Services.UserService.GetOrCreateApplicationUser(), Messenger.Core.Services.UserService.GetUser(), and Messenger.Core.Services.TeamService.GetUsersWithRole().
UserFromMSGraph()
static User Messenger.Core.Helpers.Mapper.UserFromMSGraph (User userdata) inline static
Maps to a user model with minimal information from the MS-Graph service
Parameters
userdata User object from the MS-Graph service
Returns
An user object with the information from MS-Graph
Definition at line 43 of file Mapper.cs.
References Messenger.Core.Models.User.Bio, Messenger.Core.Models.User.DisplayName, Messenger.Core.Models.User.Id, Messenger.Core.Models.User.Mail, Messenger.Core.Models.User.NameId, and Messenger.Core.Models.User.Photo.
Referenced by Messenger.Core.Services.UserService.GetOrCreateApplicationUser().
Property Documentation
logger
ILogger Messenger.Core.Helpers.Mapper.logger static get
Definition at line 19 of file Mapper.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger.Core/Helpers/Mapper.cs