VPR_Messenger: Messenger.ViewModels.Pages.ChatViewModel Class Reference
Messenger.ViewModels.Pages.ChatViewModel Class Reference
Public Member Functions
ChatViewModel ()
Defines data to be bound to 'Chat Page', also serves as a shared data pool between MessagesListControl and SendMessageControl
Protected Member Functions
void Set< T > (ref T storage, T value, [CallerMemberName]string propertyName=null)
void OnPropertyChanged (string propertyName)
Properties
MessageViewModel ReplyMessage [get, set]
Message that the user is replying to, update is triggered by MessageView, data is injected to SendMessageControl
Message MessageToSend [get, set]
Message object to be sent, update is triggered by SendMessageControl, data is injected to SendMessageCommand
TeamViewModel SelectedTeam [get, set]
ChannelViewModel SelectedChannel [get, set]
UserViewModel CurrentUser [get]
MessagesListControlViewModel MessagesListViewModel [get, set]
SendMessageControlViewModel SendMessageControlViewModel [get, set]
Events
PropertyChangedEventHandler PropertyChanged
Private Member Functions
void OnTeamUpdated (object sender, BroadcastArgs e)
void OnChannelUpdated (object sender, BroadcastArgs e)
Private Attributes
MessageViewModel _replyMessage
Message _messageToSend
TeamViewModel _selectedTeam
ChannelViewModel _selectedChannel
Detailed Description
Definition at line 10 of file ChatViewModel.cs.
Constructor & Destructor Documentation
ChatViewModel()
Messenger.ViewModels.Pages.ChatViewModel.ChatViewModel () inline
Defines data to be bound to 'Chat Page', also serves as a shared data pool between MessagesListControl and SendMessageControl
REFERENCE TO GLOBAL STATE
EVENTS REGISLATION
Definition at line 82 of file ChatViewModel.cs.
References Messenger.ViewModels.Pages.ChatViewModel.MessagesListViewModel, Messenger.ViewModels.Pages.ChatViewModel.MessageToSend, Messenger.ViewModels.Pages.ChatViewModel.OnChannelUpdated(), Messenger.ViewModels.Controls.MessagesListControlViewModel.OnMessagesSwitched(), Messenger.ViewModels.Controls.MessagesListControlViewModel.OnMessageUpdated(), Messenger.ViewModels.Pages.ChatViewModel.OnTeamUpdated(), Messenger.ViewModels.Pages.ChatViewModel.SelectedChannel, Messenger.ViewModels.Pages.ChatViewModel.SelectedTeam, and Messenger.ViewModels.Pages.ChatViewModel.SendMessageControlViewModel.
Member Function Documentation
OnChannelUpdated()
void Messenger.ViewModels.Pages.ChatViewModel.OnChannelUpdated (object sender, BroadcastArgs e) inline private
Definition at line 117 of file ChatViewModel.cs.
References Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, Messenger.Models.BroadcastArgs.Payload, Messenger.Models.BroadcastArgs.Reason, and Messenger.ViewModels.Pages.ChatViewModel.SelectedChannel.
Referenced by Messenger.ViewModels.Pages.ChatViewModel.ChatViewModel().
OnPropertyChanged()
void Messenger.Helpers.Observable.OnPropertyChanged (string propertyName) protected inherited
Referenced by Messenger.Helpers.Observable.Set< T >().
OnTeamUpdated()
void Messenger.ViewModels.Pages.ChatViewModel.OnTeamUpdated (object sender, BroadcastArgs e) inline private
Definition at line 101 of file ChatViewModel.cs.
References Messenger.ViewModels.DataViewModels.ChannelViewModel.ChannelId, Messenger.ViewModels.DataViewModels.TeamViewModel.Channels, Messenger.ViewModels.DataViewModels.TeamViewModel.Id, Messenger.Models.BroadcastArgs.Payload, Messenger.Models.BroadcastArgs.Reason, Messenger.ViewModels.Pages.ChatViewModel.SelectedChannel, and Messenger.ViewModels.Pages.ChatViewModel.SelectedTeam.
Referenced by Messenger.ViewModels.Pages.ChatViewModel.ChatViewModel().
Set< T >()
void Messenger.Helpers.Observable.Set< T > (ref T storage, T value, [CallerMemberName] string propertyName = null) inline protected inherited
Definition at line 11 of file Observable.cs.
References Messenger.Helpers.Observable.OnPropertyChanged().
Member Data Documentation
_messageToSend
Message Messenger.ViewModels.Pages.ChatViewModel._messageToSend private
Definition at line 16 of file ChatViewModel.cs.
_replyMessage
MessageViewModel Messenger.ViewModels.Pages.ChatViewModel._replyMessage private
Definition at line 14 of file ChatViewModel.cs.
_selectedChannel
ChannelViewModel Messenger.ViewModels.Pages.ChatViewModel._selectedChannel private
Definition at line 20 of file ChatViewModel.cs.
_selectedTeam
TeamViewModel Messenger.ViewModels.Pages.ChatViewModel._selectedTeam private
Definition at line 18 of file ChatViewModel.cs.
Property Documentation
CurrentUser
UserViewModel Messenger.ViewModels.Pages.ChatViewModel.CurrentUser get
Definition at line 70 of file ChatViewModel.cs.
MessagesListViewModel
MessagesListControlViewModel Messenger.ViewModels.Pages.ChatViewModel.MessagesListViewModel get set
Definition at line 72 of file ChatViewModel.cs.
Referenced by Messenger.ViewModels.Pages.ChatViewModel.ChatViewModel().
MessageToSend
Message Messenger.ViewModels.Pages.ChatViewModel.MessageToSend get set
Message object to be sent, update is triggered by SendMessageControl, data is injected to SendMessageCommand
Definition at line 46 of file ChatViewModel.cs.
Referenced by Messenger.Commands.Messenger.AttachFileCommand.CanExecute(), Messenger.ViewModels.Pages.ChatViewModel.ChatViewModel(), Messenger.Commands.Messenger.AttachFileCommand.Execute(), Messenger.Commands.Messenger.ReplyMessageCommand.Execute(), and Messenger.Commands.Messenger.SendMessageCommand.Execute().
ReplyMessage
MessageViewModel Messenger.ViewModels.Pages.ChatViewModel.ReplyMessage get set
Message that the user is replying to, update is triggered by MessageView, data is injected to SendMessageControl
Definition at line 30 of file ChatViewModel.cs.
Referenced by Messenger.Commands.Messenger.ReplyMessageCommand.Execute(), and Messenger.Commands.Messenger.SendMessageCommand.Execute().
SelectedChannel
ChannelViewModel Messenger.ViewModels.Pages.ChatViewModel.SelectedChannel get set
Definition at line 64 of file ChatViewModel.cs.
Referenced by Messenger.ViewModels.Pages.ChatViewModel.ChatViewModel(), Messenger.ViewModels.Pages.ChatViewModel.OnChannelUpdated(), and Messenger.ViewModels.Pages.ChatViewModel.OnTeamUpdated().
SelectedTeam
TeamViewModel Messenger.ViewModels.Pages.ChatViewModel.SelectedTeam get set
Definition at line 58 of file ChatViewModel.cs.
Referenced by Messenger.ViewModels.Pages.ChatViewModel.ChatViewModel(), and Messenger.ViewModels.Pages.ChatViewModel.OnTeamUpdated().
SendMessageControlViewModel
SendMessageControlViewModel Messenger.ViewModels.Pages.ChatViewModel.SendMessageControlViewModel get set
Definition at line 74 of file ChatViewModel.cs.
Referenced by Messenger.ViewModels.Pages.ChatViewModel.ChatViewModel().
Event Documentation
PropertyChanged
PropertyChangedEventHandler Messenger.Helpers.Observable.PropertyChanged inherited
Definition at line 9 of file Observable.cs.
The documentation for this class was generated from the following file:
Messenger/Messenger/ViewModels/Pages/ChatViewModel.cs