var searchData=
[
  ['unassignteamrolecommand_2ecs_1593',['UnassignTeamRoleCommand.cs',['../UnassignTeamRoleCommand_8cs.html',1,'']]],
  ['updatemessagecommand_2ecs_1594',['UpdateMessageCommand.cs',['../UpdateMessageCommand_8cs.html',1,'']]],
  ['updateteamdetailscommand_2ecs_1595',['UpdateTeamDetailsCommand.cs',['../UpdateTeamDetailsCommand_8cs.html',1,'']]],
  ['updateteamrolecommand_2ecs_1596',['UpdateTeamRoleCommand.cs',['../UpdateTeamRoleCommand_8cs.html',1,'']]],
  ['updateuserbiocommand_2ecs_1597',['UpdateUserBioCommand.cs',['../UpdateUserBioCommand_8cs.html',1,'']]],
  ['updateusernamecommand_2ecs_1598',['UpdateUserNameCommand.cs',['../UpdateUserNameCommand_8cs.html',1,'']]],
  ['uploaddata_2ecs_1599',['UploadData.cs',['../UploadData_8cs.html',1,'']]],
  ['user_2ecs_1600',['User.cs',['../User_8cs.html',1,'']]],
  ['useractivitydata_2ecs_1601',['UserActivityData.cs',['../UserActivityData_8cs.html',1,'']]],
  ['useractivityservice_2ecs_1602',['UserActivityService.cs',['../UserActivityService_8cs.html',1,'']]],
  ['useractivityservice_2esample_2ecs_1603',['UserActivityService.Sample.cs',['../UserActivityService_8Sample_8cs.html',1,'']]],
  ['userdataservice_2ecs_1604',['UserDataService.cs',['../UserDataService_8cs.html',1,'']]],
  ['userprofileflyout_2examl_2ecs_1605',['UserProfileFlyout.xaml.cs',['../UserProfileFlyout_8xaml_8cs.html',1,'']]],
  ['usersearchpanel_2examl_2ecs_1606',['UserSearchPanel.xaml.cs',['../UserSearchPanel_8xaml_8cs.html',1,'']]],
  ['usersearchpanelviewmodel_2ecs_1607',['UserSearchPanelViewModel.cs',['../UserSearchPanelViewModel_8cs.html',1,'']]],
  ['userservice_2ecs_1608',['UserService.cs',['../UserService_8cs.html',1,'']]],
  ['userviewmodel_2ecs_1609',['UserViewModel.cs',['../UserViewModel_8cs.html',1,'']]]
];
