name: .NET

on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main, unstable ]

jobs:
  build:

    runs-on: windows-latest

    defaults:
        run:
            working-directory: Messenger/Messenger.Core.Tests.MSTest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
          
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
