name: Doxygen
on:
  push:
    branches: [ main ]
jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Doxygen
      uses: mattnotmitt/doxygen-action@v1.3.1
      

