name: Doxygen
on:
  push:
    branches: [ main ]
jobs:
  Doxygen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git submodule update --init --remote
    - name: Build docs
      uses: mattnotmitt/doxygen-action@v1.3.1
      
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./html
